"use strict";
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.Workbench = void 0;
exports.createWorkbenchFromPage = createWorkbenchFromPage;
const code_1 = require("./code");
const dialog_modals_1 = require("../pages/dialog-modals");
const dialog_toasts_1 = require("../pages/dialog-toasts");
const dialog_popups_js_1 = require("../pages/dialog-popups.js");
const dialog_contextMenu_js_1 = require("../pages/dialog-contextMenu.js");
const console_1 = require("../pages/console");
const variables_1 = require("../pages/variables");
const dataExplorer_1 = require("../pages/dataExplorer");
const sideBar_1 = require("../pages/sideBar");
const plots_1 = require("../pages/plots");
const newFolderFlow_1 = require("../pages/newFolderFlow");
const explorer_1 = require("../pages/explorer");
const connections_1 = require("../pages/connections");
const help_1 = require("../pages/help");
const topActionBar_1 = require("../pages/topActionBar");
const layouts_1 = require("../pages/layouts");
const output_1 = require("../pages/output");
const welcome_1 = require("../pages/welcome");
const terminal_1 = require("../pages/terminal");
const viewer_1 = require("../pages/viewer");
const editor_1 = require("../pages/editor");
const editors_1 = require("../pages/editors");
const testExplorer_1 = require("../pages/testExplorer");
const quickaccess_1 = require("../pages/quickaccess");
const outline_1 = require("../pages/outline");
const clipboard_1 = require("../pages/clipboard");
const quickInput_1 = require("../pages/quickInput");
const extensions_1 = require("../pages/extensions");
const userSettings_1 = require("../pages/userSettings");
const debug_1 = require("../pages/debug");
const editorActionBar_1 = require("../pages/editorActionBar");
const problems_1 = require("../pages/problems");
const references_1 = require("../pages/references");
const scm_1 = require("../pages/scm");
const sessions_1 = require("../pages/sessions");
const search_js_1 = require("../pages/search.js");
const positronAssistant_js_1 = require("../pages/positronAssistant.js");
const hotKeys_js_1 = require("../pages/hotKeys.js");
const connect_js_1 = require("../pages/connect.js");
const notebooks_js_1 = require("../pages/notebooks.js");
const notebooksPositron_js_1 = require("../pages/notebooksPositron.js");
const notebooksVscode_js_1 = require("../pages/notebooksVscode.js");
const databot_js_1 = require("../pages/databot.js");
const inlineDataExplorer_js_1 = require("../pages/inlineDataExplorer.js");
const inlineQuarto_js_1 = require("../pages/inlineQuarto.js");
class Workbench {
    modals;
    toasts;
    popups;
    contextMenu;
    console;
    variables;
    dataExplorer;
    sideBar;
    plots;
    notebooks;
    notebooksVscode;
    notebooksPositron;
    newFolderFlow;
    explorer;
    connections;
    help;
    topActionBar;
    layouts;
    output;
    welcome;
    terminal;
    viewer;
    editor;
    testExplorer;
    quickaccess;
    outline;
    clipboard;
    quickInput;
    extensions;
    editors;
    settings;
    debug;
    editorActionBar;
    problems;
    references;
    scm;
    sessions;
    search;
    assistant;
    hotKeys;
    positConnect;
    databot;
    inlineDataExplorer;
    inlineQuarto;
    constructor(code) {
        this.hotKeys = new hotKeys_js_1.HotKeys(code);
        this.toasts = new dialog_toasts_1.Toasts(code);
        this.popups = new dialog_popups_js_1.Popups(code);
        this.contextMenu = new dialog_contextMenu_js_1.ContextMenu(code);
        this.variables = new variables_1.Variables(code, this.hotKeys, this.contextMenu);
        this.dataExplorer = new dataExplorer_1.DataExplorer(code, this);
        this.sideBar = new sideBar_1.SideBar(code);
        this.plots = new plots_1.Plots(code, this.contextMenu);
        this.explorer = new explorer_1.Explorer(code);
        this.help = new help_1.Help(code);
        this.topActionBar = new topActionBar_1.TopActionBar(code);
        this.layouts = new layouts_1.Layouts(code, this);
        this.quickInput = new quickInput_1.QuickInput(code);
        this.editors = new editors_1.Editors(code);
        this.quickaccess = new quickaccess_1.QuickAccess(code, this.editors, this.quickInput);
        this.connections = new connections_1.Connections(code, this.quickaccess);
        this.newFolderFlow = new newFolderFlow_1.NewFolderFlow(code, this.quickaccess);
        this.output = new output_1.Output(code, this.quickaccess, this.quickInput);
        this.console = new console_1.Console(code, this.quickInput, this.hotKeys, this.contextMenu);
        this.modals = new dialog_modals_1.Modals(code, this.toasts, this.console);
        this.clipboard = new clipboard_1.Clipboard(code, this.hotKeys);
        this.sessions = new sessions_1.Sessions(code, this.quickaccess, this.quickInput, this.console, this.contextMenu, this.modals);
        this.notebooks = new notebooks_js_1.Notebooks(code, this.quickInput, this.quickaccess, this.hotKeys);
        this.notebooksVscode = new notebooksVscode_js_1.VsCodeNotebooks(code, this.quickInput, this.quickaccess, this.hotKeys);
        this.notebooksPositron = new notebooksPositron_js_1.PositronNotebooks(code, this.quickInput, this.quickaccess, this.hotKeys, this.contextMenu);
        this.welcome = new welcome_1.Welcome(code);
        this.terminal = new terminal_1.Terminal(code, this.quickaccess, this.clipboard);
        this.viewer = new viewer_1.Viewer(code);
        this.editor = new editor_1.Editor(code);
        this.testExplorer = new testExplorer_1.TestExplorer(code);
        this.outline = new outline_1.Outline(code, this.quickaccess);
        this.extensions = new extensions_1.Extensions(code, this.quickaccess);
        this.settings = new userSettings_1.UserSettings(code, this.hotKeys);
        this.debug = new debug_1.Debug(code, this.hotKeys, this.quickaccess);
        this.editorActionBar = new editorActionBar_1.EditorActionBar(code.driver.currentPage, this.viewer, this.quickaccess);
        this.problems = new problems_1.Problems(code, this.quickaccess);
        this.references = new references_1.References(code);
        this.scm = new scm_1.SCM(code, this.layouts);
        this.search = new search_js_1.Search(code);
        this.assistant = new positronAssistant_js_1.Assistant(code, this.quickaccess, this.toasts, this.modals);
        this.positConnect = new connect_js_1.PositConnect(code);
        this.databot = new databot_js_1.Databot(code, this.quickaccess);
        this.inlineDataExplorer = new inlineDataExplorer_js_1.InlineDataExplorer(code.driver.currentPage);
        this.inlineQuarto = new inlineQuarto_js_1.InlineQuarto(code, this.quickaccess, this.hotKeys);
    }
}
exports.Workbench = Workbench;
function createWorkbenchFromPage(parentCode, page) {
    const code = (0, code_1.createCodeFromPage)(parentCode, page);
    return new Workbench(code);
}
//# sourceMappingURL=workbench.js.map