name: "Download Binaries (Ark, Kallichore)"
description: "Downloads R and Python kernel binaries when using cached node_modules"

inputs:
  cache-hit:
    description: "Whether the extensions cache was hit (only download if true)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Ark and Kallichore binaries
      if: ${{ inputs.cache-hit == 'true' }}
      shell: bash
      working-directory: extensions
      run: |
        echo "Extensions cache hit detected - downloading binaries"
        # When extensions cache hits, postinstall scripts didn't run
        # Force rebuild to download platform-specific binaries
        echo "Downloading Ark binary..."
        cd positron-r && npm rebuild --foreground-scripts
        echo "Downloading Kallichore binary..."
        cd ../positron-supervisor && npm rebuild --foreground-scripts
        echo "Binaries downloaded successfully"
