export const BASH_ENV_KEY = 'VSCODE_PYTHON_BASH_ACTIVATE';
export const ZSH_ENV_KEY = 'VSCODE_PYTHON_ZSH_ACTIVATE';
export const BASH_OLD_ENV_KEY = 'VSCODE_BASH_ACTIVATE';
export const ZSH_OLD_ENV_KEY = 'VSCODE_ZSH_ACTIVATE';
export const BASH_SCRIPT_VERSION = '0.1.1';
