/*---------------------------------------------------------------------------------------------
 *  Copyright (C) 2026 Posit Software, PBC. All rights reserved.
 *  Licensed under the Elastic License 2.0. See LICENSE.txt for license information.
 *--------------------------------------------------------------------------------------------*/

//! Which keywords are worth completing where the cursor is.
//!
//! Offering every keyword at every position, which is what this replaced, means offering `ZONE`
//! and `ABSOLUTE` in the middle of a `WHERE` clause and all 1092 of sqlparser's keywords in a slot
//! where only a table name belongs. So the position has to be read off the text -- and, like
//! [`crate::sources`], off the *tokens* rather than a parse tree, because completion is only ever
//! asked about a statement halfway through being typed and sqlparser has no error recovery.
//!
//! # Where the answers come from
//!
//! sqlparser holds no data about where a keyword may appear, so none can be read out of it. Its
//! grammar lives in the control flow of a hand-written recursive descent parser; `ParserError` is
//! a `String`, the ~195 `expected(...)` sites take free-form English, and the four
//! `RESERVED_FOR_*` tables are *exclusion* sets for the parser's own alias handling. So the
//! candidate lists below are authored here.
//!
//! What sqlparser can do is *judge* a candidate: splice one in at a position and see whether its
//! parser takes it. That is what [`crate::keywords_generated`] is built from -- a table of
//! dialect x position, generated by trial parsing and committed, so the authored lists cannot
//! quietly rot and the runtime pays nothing. See `tests/keyword_table.rs` for the generator and
//! the rules it applies.
//!
//! Not every position can be judged that way. Where an expression may begin, a bare identifier is
//! itself a legal expression, so `SELECT CASE` parses as "the column named CASE" and the parser
//! cannot tell a keyword being typed from a name. Those positions are marked
//! [`Position::is_checkable`] and their lists stand unfiltered.
//!
//! # What this does not place
//!
//! The positions inside a construct whose own keywords are obligatory but whose extent this does
//! not track: the arms of a `CASE` (`WHEN`, `THEN`, `ELSE`, `END`), the `ESCAPE` of a `LIKE`, and
//! the actions of an `ALTER TABLE`. Each would need the scan to know it is inside that construct,
//! which is more than the token stream gives up cheaply. They fall to [`Position::Everything`] or
//! to the surrounding expression, so the words are still reachable by prefix -- they are simply
//! not promoted. Deliberate, and the first thing to revisit if the completions feel thin.

use sqlparser::keywords::Keyword;
use sqlparser::tokenizer::{Token, TokenWithSpan, Word};

use crate::statements::Statement;
use crate::text::TextIndex;

/// Where the cursor is, as far as the keywords that belong there are concerned.
///
/// Not a grammar. Two positions the grammar distinguishes are one variant here whenever they would
/// offer the same words, because a wrong entry costs one line in a list the user is filtering by
/// prefix anyway, while a variant costs a rule that has to be right. The granularity that survived
/// is the one at which the parser's own answers differ.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Position {
    /// The beginning of a statement: nothing typed yet, or the cursor is between two.
    StatementStart,
    /// After `CREATE`, `ALTER`, `DROP` or `TRUNCATE`, where the object kind belongs.
    Ddl,
    /// Directly after `SELECT`, or after its `DISTINCT`/`ALL`.
    SelectStart,
    /// After a complete item in the select list.
    SelectItem,
    /// Where a table or column *name* belongs, and so almost no keyword does. The slot that
    /// previously offered all 1110.
    Name,
    /// After a complete table reference in a `FROM`.
    TableItem,
    /// After a table reference that followed a `JOIN`, which additionally takes `ON`/`USING`.
    JoinedItem,
    /// After the table of an `UPDATE`, which takes `SET`.
    UpdateItem,
    /// After the table of an `INSERT INTO`, which takes `VALUES`, `SELECT` or a column list.
    InsertTarget,
    /// Where an expression may begin: after a clause keyword, a connective, an operator or a
    /// comma in an expression list.
    Value,
    /// Directly after `(`, which may open a subquery as well as an expression.
    Subquery,
    /// After a complete expression in a clause that takes one.
    Expression,
    /// After an `ORDER BY` item.
    OrderItem,
    /// Directly after `OVER (`.
    WindowSpec,
    /// In a `CREATE TABLE` column list, or after the `AS` of a `CAST`, where a type belongs.
    ColumnDefinition,
    /// After a bare `GROUP`, `ORDER` or `PARTITION`, which all take `BY`.
    ExpectingBy,
    /// After `LEFT`, `RIGHT`, `FULL`, `INNER`, `CROSS`, `OUTER` or `NATURAL`.
    ExpectingJoin,
    /// After the `NULLS` of an `ORDER BY` item.
    ExpectingNullsOrder,
    /// After the `IS` of a predicate.
    ExpectingIsPredicate,
    /// The position could not be placed, so everything is offered. Deliberately not an empty
    /// list: an empty one is indistinguishable from the extension being broken, and silently
    /// removes a completion that used to work.
    Everything,
}

/// Every position that has a generated row, in the order the generated table is indexed by.
///
/// `Everything` is absent: it answers from the whole vocabulary rather than from a row.
pub const POSITIONS: &[Position] = &[
    Position::StatementStart,
    Position::Ddl,
    Position::SelectStart,
    Position::SelectItem,
    Position::Name,
    Position::TableItem,
    Position::JoinedItem,
    Position::UpdateItem,
    Position::InsertTarget,
    Position::Value,
    Position::Subquery,
    Position::Expression,
    Position::OrderItem,
    Position::WindowSpec,
    Position::ColumnDefinition,
    Position::ExpectingBy,
    Position::ExpectingJoin,
    Position::ExpectingNullsOrder,
    Position::ExpectingIsPredicate,
];

impl Position {
    /// The name the caller logs, so a surprising list can be traced to the rule that produced it.
    pub fn name(self) -> &'static str {
        match self {
            Position::StatementStart => "statementStart",
            Position::Ddl => "ddl",
            Position::SelectStart => "selectStart",
            Position::SelectItem => "selectItem",
            Position::Name => "name",
            Position::TableItem => "tableItem",
            Position::JoinedItem => "joinedItem",
            Position::UpdateItem => "updateItem",
            Position::InsertTarget => "insertTarget",
            Position::Value => "value",
            Position::Subquery => "subquery",
            Position::Expression => "expression",
            Position::OrderItem => "orderItem",
            Position::WindowSpec => "windowSpec",
            Position::ColumnDefinition => "columnDefinition",
            Position::ExpectingBy => "expectingBy",
            Position::ExpectingJoin => "expectingJoin",
            Position::ExpectingNullsOrder => "expectingNullsOrder",
            Position::ExpectingIsPredicate => "expectingIsPredicate",
            Position::Everything => "everything",
        }
    }

    /// Index of this position's row in the generated table.
    pub fn index(self) -> Option<usize> {
        POSITIONS.iter().position(|position| *position == self)
    }

    /// The statement prefixes the generator splices candidates onto, the cursor being the end of
    /// each.
    ///
    /// More than one where a position is reachable by routes that accept different words: the
    /// `SET` of an `UPDATE` and the `WHERE` of a `SELECT` both follow a table reference. A
    /// candidate survives if *any* fixture accepts it.
    pub fn fixtures(self) -> &'static [&'static str] {
        match self {
            Position::StatementStart => &["", "SELECT 1; "],
            Position::Ddl => &["CREATE ", "DROP ", "ALTER "],
            Position::SelectStart => &["SELECT "],
            Position::SelectItem => &["SELECT total ", "SELECT count(*) "],
            Position::Name => &["SELECT * FROM ", "SELECT a AS ", "DROP TABLE ", "CREATE TABLE "],
            Position::TableItem => &["SELECT * FROM orders ", "DELETE FROM orders "],
            Position::JoinedItem => &["SELECT * FROM a JOIN b "],
            Position::UpdateItem => &["UPDATE orders "],
            Position::InsertTarget => &["INSERT INTO orders "],
            Position::Value => &["SELECT * FROM orders WHERE "],
            Position::Subquery => &["SELECT * FROM orders WHERE id IN ("],
            Position::Expression => &["SELECT * FROM orders WHERE id = 1 "],
            Position::OrderItem => &["SELECT * FROM orders ORDER BY id "],
            Position::WindowSpec => &[
                "SELECT row_number() OVER (",
                "SELECT row_number() OVER (ROWS ",
                "SELECT row_number() OVER (ORDER BY a ROWS UNBOUNDED PRECEDING ",
            ],
            Position::ColumnDefinition => &["CREATE TABLE orders (id "],
            Position::ExpectingBy => &["SELECT * FROM orders GROUP "],
            Position::ExpectingJoin => &["SELECT * FROM a LEFT ", "SELECT * FROM a INNER "],
            Position::ExpectingNullsOrder => &["SELECT * FROM orders ORDER BY id NULLS "],
            Position::ExpectingIsPredicate => &["SELECT * FROM orders WHERE a IS "],
            Position::Everything => &[],
        }
    }

    /// Whether trial parsing can judge this position.
    ///
    /// False where an expression may begin, because a bare identifier is a legal expression there:
    /// `SELECT CASE` parses as a column named `CASE`, so the parser accepts every word and its
    /// verdict says nothing. Those lists are short, near-universal, and stand as authored.
    pub fn is_checkable(self) -> bool {
        !matches!(
            self,
            Position::SelectStart
                | Position::Value
                | Position::Subquery
                | Position::ColumnDefinition
                | Position::Everything
        )
    }

    /// The keywords authored for this position, before the parser has had a say.
    pub fn candidates(self) -> Vec<&'static str> {
        let mut all: Vec<&'static str> = match self {
            Position::StatementStart => STATEMENT_START.to_vec(),
            Position::Ddl => DDL.to_vec(),
            Position::SelectStart => [VALUE_STARTERS, &["ALL", "DISTINCT", "DISTINCT ON", "TOP"]].concat(),
            Position::SelectItem => [
                OPERATORS,
                CALL_SUFFIXES,
                SET_OPERATORS,
                &["AS", "FROM", "INTO"],
            ]
            .concat(),
            Position::Name => NAME.to_vec(),
            Position::TableItem => [TABLE_TAIL, TABLE_TAIL_CLAUSES, JOINS, &["RETURNING"]].concat(),
            Position::JoinedItem => {
                [TABLE_TAIL, TABLE_TAIL_CLAUSES, JOINS, &["ON", "USING"]].concat()
            }
            Position::UpdateItem => [TABLE_TAIL, &["AS", "FROM", "SET"]].concat(),
            Position::InsertTarget => {
                ["DEFAULT VALUES", "SELECT", "VALUES", "WITH", "AS"].to_vec()
            }
            Position::Value => [VALUE_STARTERS, GROUPING_MODIFIERS].concat(),
            Position::Subquery => [
                VALUE_STARTERS,
                GROUPING_MODIFIERS,
                &["ALL", "DISTINCT", "SELECT", "VALUES", "WITH"],
            ]
            .concat(),
            Position::Expression => {
                [OPERATORS, PREDICATE_TAIL_CLAUSES, SET_OPERATORS].concat()
            }
            Position::OrderItem => [
                OPERATORS,
                &[
                    "ASC", "DESC", "NULLS FIRST", "NULLS LAST", "COLLATE", "FETCH", "FOR UPDATE",
                    "LIMIT", "OFFSET",
                ],
            ]
            .concat(),
            Position::WindowSpec => WINDOW_SPEC.to_vec(),
            Position::ColumnDefinition => [DATA_TYPES, COLUMN_CONSTRAINTS].concat(),
            Position::ExpectingBy => ["BY"].to_vec(),
            Position::ExpectingJoin => {
                ["JOIN", "OUTER", "OUTER JOIN", "ANTI JOIN", "SEMI JOIN"].to_vec()
            }
            Position::ExpectingNullsOrder => ["FIRST", "LAST"].to_vec(),
            Position::ExpectingIsPredicate => [
                "DISTINCT FROM", "FALSE", "NOT", "NOT DISTINCT FROM", "NOT FALSE", "NOT NULL",
                "NOT TRUE", "NULL", "TRUE", "UNKNOWN",
            ]
            .to_vec(),
            Position::Everything => Vec::new(),
        };
        all.sort_unstable();
        all.dedup();
        all
    }
}

/// The words a value may begin with, wherever an expression may start.
const VALUE_STARTERS: &[&str] = &[
    "ARRAY", "CASE", "CAST", "COALESCE", "COUNT", "CURRENT_DATE", "CURRENT_TIME",
    "CURRENT_TIMESTAMP", "CURRENT_USER", "DATE", "DEFAULT", "EXISTS", "EXTRACT", "FALSE",
    "INTERVAL", "MAX", "MIN", "NOT", "NULL", "NULLIF", "SUBSTRING", "SUM", "TIME", "TIMESTAMP",
    "TRIM", "TRUE", "TRY_CAST",
];

/// The operators and predicates that continue a value once one has been written.
const OPERATORS: &[&str] = &[
    "AND", "AT TIME ZONE", "BETWEEN", "COLLATE", "ILIKE", "IN", "IS",
    "IS DISTINCT FROM", "IS FALSE", "IS NOT DISTINCT FROM", "IS NOT NULL", "IS NULL", "IS TRUE",
    "LIKE", "NOT BETWEEN", "NOT ILIKE", "NOT IN", "NOT LIKE", "OR", "OVERLAPS", "RLIKE",
    "SIMILAR TO",
];

/// The clauses that may follow the `FROM` list of a query.
const TABLE_TAIL_CLAUSES: &[&str] = &[
    "FETCH", "GROUP BY", "HAVING", "LIMIT", "OFFSET", "ORDER BY", "QUALIFY", "WHERE", "WINDOW",
];

/// The clauses that may follow a complete predicate, which `WHERE` may not: it has already been
/// written by the time the cursor is here.
const PREDICATE_TAIL_CLAUSES: &[&str] = &[
    "FETCH", "FOR UPDATE", "GROUP BY", "HAVING", "LIMIT", "OFFSET", "ORDER BY", "QUALIFY", "WINDOW",
];

/// The operators that combine one query with another.
const SET_OPERATORS: &[&str] = &["EXCEPT", "INTERSECT", "MINUS", "UNION", "UNION ALL"];

/// The suffixes an aggregate or window call takes.
const CALL_SUFFIXES: &[&str] = &["FILTER", "OVER", "WITHIN GROUP"];

/// The words that may follow a complete table reference whatever clause it sits in.
const TABLE_TAIL: &[&str] = &["AS", "MATCH_RECOGNIZE", "PIVOT", "TABLESAMPLE", "UNPIVOT"];

/// Every spelling of a join.
const JOINS: &[&str] = &[
    "CROSS JOIN", "FULL JOIN", "FULL OUTER JOIN", "INNER JOIN", "JOIN", "LEFT JOIN",
    "LEFT OUTER JOIN", "NATURAL JOIN", "RIGHT JOIN", "RIGHT OUTER JOIN",
];

/// The few words that belong where a name does.
const NAME: &[&str] = &["IF EXISTS", "IF NOT EXISTS", "LATERAL", "TABLE", "UNNEST"];

/// The modifiers a `GROUP BY` list takes.
const GROUPING_MODIFIERS: &[&str] = &["CUBE", "GROUPING SETS", "ROLLUP"];

/// What a window specification is built from.
const WINDOW_SPEC: &[&str] = &[
    "CURRENT ROW", "FOLLOWING", "GROUPS", "ORDER BY", "PARTITION BY", "PRECEDING", "RANGE", "ROWS",
    "UNBOUNDED FOLLOWING", "UNBOUNDED PRECEDING",
];

/// The verbs a statement may begin with.
const STATEMENT_START: &[&str] = &[
    "ALTER TABLE", "ALTER VIEW", "ANALYZE", "BEGIN", "CALL", "COMMIT", "COPY", "CREATE",
    "CREATE INDEX", "CREATE MATERIALIZED VIEW", "CREATE OR REPLACE VIEW", "CREATE SCHEMA",
    "CREATE TABLE", "CREATE TEMPORARY TABLE", "CREATE VIEW", "DELETE FROM", "DESCRIBE",
    "DROP INDEX", "DROP TABLE", "DROP VIEW", "EXECUTE", "EXPLAIN", "GRANT", "INSERT INTO",
    "LISTEN", "MERGE INTO", "NOTIFY", "PRAGMA", "PREPARE", "REVOKE", "ROLLBACK", "SELECT", "SET",
    "SHOW", "START TRANSACTION", "TRUNCATE TABLE", "UNLISTEN", "UPDATE", "USE", "VACUUM",
    "VALUES", "WITH", "WITH RECURSIVE",
];

/// The object kinds and modifiers a DDL verb takes.
const DDL: &[&str] = &[
    "DATABASE", "EXTERNAL TABLE", "FUNCTION", "INDEX", "MATERIALIZED VIEW", "OR REPLACE",
    "PROCEDURE", "SCHEMA", "SEQUENCE", "TABLE", "TEMPORARY TABLE", "TRIGGER", "UNIQUE INDEX",
    "VIEW",
];

/// The type names a column definition may use.
const DATA_TYPES: &[&str] = &[
    "ARRAY", "BIGINT", "BLOB", "BOOLEAN", "BYTEA", "CHAR", "DATE", "DECIMAL", "DOUBLE",
    "DOUBLE PRECISION", "FLOAT", "INT", "INTEGER", "INTERVAL", "JSON", "JSONB", "NUMERIC", "REAL",
    "SMALLINT", "TEXT", "TIME", "TIMESTAMP", "TIMESTAMP WITH TIME ZONE", "TINYINT", "UUID",
    "VARCHAR",
];

/// The constraints a column definition may carry.
const COLUMN_CONSTRAINTS: &[&str] = &[
    "AUTOINCREMENT", "CHECK", "COLLATE", "COMMENT", "CONSTRAINT", "DEFAULT",
    "GENERATED ALWAYS AS", "NOT NULL", "NULL", "PRIMARY KEY", "REFERENCES", "UNIQUE",
];

/// The multi-word keywords worth offering whole.
///
/// sqlparser tokenizes each word separately and its keyword table has no notion of a phrase, so
/// none of these are in it. Collected here as well as distributed into the positions above, so
/// that the fallback list can never lack a phrase some position offers.
pub fn phrases() -> Vec<&'static str> {
    let mut all: Vec<&'static str> = POSITIONS
        .iter()
        .flat_map(|position| position.candidates())
        .filter(|keyword| keyword.contains(' '))
        .collect();
    all.sort_unstable();
    all.dedup();
    all
}

/// Every keyword the analyzer knows, sorted and deduplicated: the answer when the position cannot
/// be placed.
///
/// sqlparser keeps one keyword table for all dialects, so this does not vary with the configured
/// dialect. That over-offers, and where the position *is* known the generated rows are what avoids
/// it. Here, where it is not, over-offering is the point: a keyword a dialect does not have costs
/// an entry in a list the user is filtering by prefix anyway, and an empty list at a position the
/// scan failed to recognize would cost the user a completion that used to work, with no way to
/// tell why.
pub fn everything() -> Vec<String> {
    let mut all: Vec<String> = sqlparser::keywords::ALL_KEYWORDS
        .iter()
        .map(|keyword| (*keyword).to_string())
        .chain(phrases().iter().map(|phrase| (*phrase).to_string()))
        .collect();
    all.sort_unstable();
    all.dedup();
    all
}

/// The keywords worth completing at a position, for a dialect.
///
/// `dialect` is a [`crate::dialects::CANONICAL`] name. An unrecognized one falls back to the whole
/// vocabulary rather than to nothing, which is also what an unplaceable position does: the two
/// ways of not knowing should not differ, and neither should cost the user their completions.
pub fn offered(position: Position, dialect: &str) -> Vec<String> {
    let Some(index) = position.index() else {
        return everything();
    };
    let Some(base) = crate::keywords_generated::BASE.get(index) else {
        return everything();
    };
    let mut all: Vec<&str> = base.to_vec();
    for (row, at, added) in crate::keywords_generated::EXTRA {
        if *row == dialect && *at == index {
            all.extend_from_slice(added);
        }
    }
    all.sort_unstable();
    all.dedup();
    all.into_iter().map(ToString::to_string).collect()
}

/// The keywords worth completing at an offset in a statement.
///
/// `statement` is `None` when the offset falls between statements, which is the user starting a
/// new one.
pub fn at(statement: Option<&Statement>, offset: u32, index: &TextIndex) -> Position {
    let Some(statement) = statement else {
        return Position::StatementStart;
    };
    let tokens = completed(&statement.tokens, offset, index);
    place(tokens)
}

/// The tokens the user has finished typing, given where the cursor is.
///
/// The token under the cursor is the word being completed, not a word the statement contains: at
/// `SELECT * FROM orders WHERE` the user has typed five characters of a word that will become
/// `WHERE`, and reading it as a finished `WHERE` would answer for the position *after* the clause
/// keyword rather than the position of the keyword itself. Dropping it never hides it, because the
/// position that offers a word is by definition the position the user is in while typing it.
///
/// Only a word is dropped. Punctuation ending at the cursor is finished by construction -- there
/// is no half-typed `=` -- and `WHERE x =` must read as a value slot rather than as the position
/// after `x`.
fn completed<'a>(tokens: &'a [TokenWithSpan], offset: u32, index: &TextIndex) -> &'a [TokenWithSpan] {
    let mut end = 0;
    for (at, token) in tokens.iter().enumerate() {
        match index.span(token.span) {
            // Spans are half open, so a token occupying `[start, end)` is finished when its end
            // has been reached.
            Some((_, token_end)) if token_end > offset => break,
            _ => end = at + 1,
        }
    }
    // The word being typed ends exactly where the cursor is.
    if let Some(last) = end.checked_sub(1) {
        let ends_at_cursor = index
            .span(tokens[last].span)
            .map(|(start, token_end)| token_end == offset && start < offset)
            .unwrap_or(false);
        if ends_at_cursor && matches!(tokens[last].token, Token::Word(_)) {
            end = last;
        }
    }
    &tokens[..end]
}

/// What the parenthesis the cursor sits inside was opened by.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Group {
    /// Not inside one.
    None,
    /// After `OVER`, so the group is a window specification.
    Window,
    /// After `CAST`, `TRY_CAST` or `SAFE_CAST`, so what follows its `AS` is a type.
    Cast,
    /// In a `CREATE`, so the group is a column definition list.
    Definition,
    /// In an `INSERT INTO`, so the group is a list of column names.
    Columns,
    /// Anything else: an expression list, a function call, or a subquery.
    Other,
}

/// Reads the tokens before the cursor and decides which position they add up to.
fn place(tokens: &[TokenWithSpan]) -> Position {
    if tokens.is_empty() {
        return Position::StatementStart;
    }

    let verb = tokens.first().and_then(word).map(|word| word.keyword);

    // A forward pass: everything the decision needs is prefix state, and parentheses only match
    // reliably forwards.
    let mut group = Group::None;
    let mut stack: Vec<Group> = Vec::new();
    let mut group_start = 0usize;
    let mut group_starts: Vec<usize> = Vec::new();
    let mut clause: Option<Keyword> = None;
    let mut clauses: Vec<Option<Keyword>> = Vec::new();
    // Whether the table reference being read followed a JOIN, which is what makes `ON` legal.
    let mut joined = false;
    // Whether the token before this one introduced a name, which makes this one a name however it
    // is spelled. sqlparser's keyword table is global, so `order`, `value` and `year` are all in
    // it and all perfectly ordinary table names.
    let mut naming = false;

    for at in 0..tokens.len() {
        match &tokens[at].token {
            Token::LParen => {
                let preceding = at.checked_sub(1).and_then(|before| word(&tokens[before]));
                let opened = match preceding.map(|word| word.keyword) {
                    Some(Keyword::OVER) => Group::Window,
                    Some(Keyword::CAST | Keyword::TRY_CAST | Keyword::SAFE_CAST) => Group::Cast,
                    _ if verb == Some(Keyword::CREATE) && stack.is_empty() => Group::Definition,
                    _ if verb == Some(Keyword::INSERT) && clause == Some(Keyword::INTO) => {
                        Group::Columns
                    }
                    _ => Group::Other,
                };
                stack.push(group);
                group_starts.push(group_start);
                clauses.push(clause);
                group = opened;
                group_start = at + 1;
                clause = None;
            }
            Token::RParen => {
                group = stack.pop().unwrap_or(Group::None);
                group_start = group_starts.pop().unwrap_or(0);
                clause = clauses.pop().unwrap_or(None);
            }
            Token::Word(word) if word.quote_style.is_none() && !naming => {
                if is_join_word(word.keyword) {
                    joined = true;
                    clause = Some(Keyword::JOIN);
                } else if let Some(keyword) = clause_keyword(word.keyword) {
                    if keyword != Keyword::JOIN {
                        joined = false;
                    }
                    clause = Some(keyword);
                }
            }
            _ => {}
        }
        naming = word(&tokens[at])
            .map(|word| word.quote_style.is_none() && introduces_name(word.keyword))
            .unwrap_or(false);
    }

    let local = &tokens[group_start.min(tokens.len())..];
    decide(local, verb, group, clause, joined)
}

/// The keywords that introduce a clause, and so say what the words after them mean.
fn clause_keyword(keyword: Keyword) -> Option<Keyword> {
    matches!(
        keyword,
        Keyword::SELECT
            | Keyword::FROM
            | Keyword::WHERE
            | Keyword::GROUP
            | Keyword::ORDER
            | Keyword::HAVING
            | Keyword::QUALIFY
            | Keyword::WINDOW
            | Keyword::LIMIT
            | Keyword::OFFSET
            | Keyword::SET
            | Keyword::VALUES
            | Keyword::INTO
            | Keyword::UPDATE
            | Keyword::RETURNING
            | Keyword::ON
            | Keyword::USING
    )
    .then_some(keyword)
}

/// Whether a word is part of the spelling of a join.
fn is_join_word(keyword: Keyword) -> bool {
    matches!(
        keyword,
        Keyword::JOIN
            | Keyword::INNER
            | Keyword::LEFT
            | Keyword::RIGHT
            | Keyword::FULL
            | Keyword::CROSS
            | Keyword::OUTER
            | Keyword::NATURAL
    )
}

/// The words that dictate what comes immediately after them.
fn obligatory(keyword: Keyword) -> Option<Position> {
    match keyword {
        Keyword::GROUP | Keyword::ORDER | Keyword::PARTITION => Some(Position::ExpectingBy),
        Keyword::LEFT
        | Keyword::RIGHT
        | Keyword::FULL
        | Keyword::INNER
        | Keyword::CROSS
        | Keyword::NATURAL
        | Keyword::OUTER => Some(Position::ExpectingJoin),
        Keyword::NULLS => Some(Position::ExpectingNullsOrder),
        Keyword::IS => Some(Position::ExpectingIsPredicate),
        _ => None,
    }
}

/// Whether a word introduces a name rather than continuing the grammar.
fn introduces_name(keyword: Keyword) -> bool {
    matches!(
        keyword,
        Keyword::FROM | Keyword::JOIN | Keyword::INTO | Keyword::UPDATE | Keyword::TABLE
    )
}

/// Whether a word may be read as a name.
///
/// Deliberately not "is not a keyword", for the reason [`crate::sources`] spells out at length:
/// sqlparser's keyword table is global and over a thousand entries, so ordinary names --
/// `warehouse`, `value`, `year`, `source` -- are in it. What has to be excluded is the handful of
/// words that mean something structural right here.
fn can_be_name(word: &Word) -> bool {
    word.quote_style.is_some()
        || !(clause_keyword(word.keyword).is_some()
            || is_join_word(word.keyword)
            || obligatory(word.keyword).is_some())
}

fn word(token: &TokenWithSpan) -> Option<&Word> {
    match &token.token {
        Token::Word(word) => Some(word),
        _ => None,
    }
}

/// Whether a token finishes a value, so that what follows continues one rather than begins one.
fn completes_value(token: &Token) -> bool {
    match token {
        Token::Word(word) => can_be_name(word),
        Token::Number(_, _)
        | Token::SingleQuotedString(_)
        | Token::DoubleQuotedString(_)
        | Token::DollarQuotedString(_)
        | Token::NationalStringLiteral(_)
        | Token::HexStringLiteral(_)
        | Token::EscapedStringLiteral(_)
        | Token::RParen
        | Token::RBracket
        | Token::Placeholder(_) => true,
        // A wildcard finishes a select item; a multiplication does not, but the token before it
        // decides that and the caller has already looked.
        Token::Mul => true,
        _ => false,
    }
}

/// Decides the position from the tokens of the innermost group.
fn decide(
    local: &[TokenWithSpan],
    verb: Option<Keyword>,
    group: Group,
    clause: Option<Keyword>,
    joined: bool,
) -> Position {
    let Some(previous) = local.last() else {
        // Nothing typed inside the group yet.
        return match group {
            Group::Window => Position::WindowSpec,
            Group::Definition => Position::ColumnDefinition,
            Group::Columns => Position::Name,
            Group::Cast | Group::Other => Position::Subquery,
            Group::None => Position::StatementStart,
        };
    };

    // Whether the previous token stands where a name belongs, and so is a name whatever the
    // keyword table says about how it is spelled: `FROM order` is a table called `order`, not the
    // start of an `ORDER BY`.
    let previous_names = {
        let before = local.len().checked_sub(2);
        let after_introducer = before
            .and_then(|before| word(&local[before]))
            .map(|before| before.quote_style.is_none() && introduces_name(before.keyword))
            .unwrap_or(false);
        let after_dot = before
            .map(|before| matches!(local[before].token, Token::Period))
            .unwrap_or(false);
        matches!(previous.token, Token::Word(_)) && (after_introducer || after_dot)
    };

    if let Some(previous_word) = word(previous) {
        if previous_word.quote_style.is_none() && !previous_names {
            // A word that dictates what follows it wins over everything below.
            if let Some(position) = obligatory(previous_word.keyword) {
                return position;
            }
            if introduces_name(previous_word.keyword) || previous_word.keyword == Keyword::AS {
                return match group {
                    // The `AS` of a cast, and of a column definition, take a type rather than a
                    // name.
                    Group::Cast | Group::Definition => Position::ColumnDefinition,
                    _ => Position::Name,
                };
            }
            if previous_word.keyword == Keyword::SELECT
                || (matches!(previous_word.keyword, Keyword::DISTINCT | Keyword::ALL)
                    && clause == Some(Keyword::SELECT))
            {
                return Position::SelectStart;
            }
            if is_ddl_verb(previous_word.keyword) || is_ddl_modifier(previous_word.keyword) {
                return Position::Ddl;
            }
            if starts_value(previous_word.keyword) {
                return Position::Value;
            }
        }
    }

    match &previous.token {
        Token::Comma => {
            return match (group, clause) {
                (Group::Definition, _) | (Group::Columns, _) => Position::Name,
                (_, Some(Keyword::FROM | Keyword::JOIN | Keyword::INTO | Keyword::UPDATE)) => {
                    Position::Name
                }
                _ => Position::Value,
            }
        }
        // Anything else that is not a completed value opens one. Inverted deliberately: sqlparser
        // has some eighty operator tokens and enumerating them would rot, whereas the tokens that
        // *finish* a value are a short, stable list.
        token if !previous_names && !completes_value(token) => return Position::Value,
        _ => {}
    }

    // A completed value. What it completes depends on the clause it sits in.
    match group {
        Group::Definition => return Position::ColumnDefinition,
        Group::Window => return Position::WindowSpec,
        _ => {}
    }

    match clause {
        Some(Keyword::ORDER) => Position::OrderItem,
        Some(Keyword::FROM) | Some(Keyword::JOIN) => {
            if verb == Some(Keyword::INSERT) {
                Position::InsertTarget
            } else if joined {
                Position::JoinedItem
            } else {
                Position::TableItem
            }
        }
        Some(Keyword::INTO) => {
            if verb == Some(Keyword::INSERT) {
                Position::InsertTarget
            } else {
                Position::TableItem
            }
        }
        Some(Keyword::UPDATE) => Position::UpdateItem,
        Some(Keyword::SELECT) => Position::SelectItem,
        Some(
            Keyword::WHERE
            | Keyword::HAVING
            | Keyword::QUALIFY
            | Keyword::ON
            | Keyword::USING
            | Keyword::SET
            | Keyword::VALUES
            | Keyword::RETURNING
            | Keyword::GROUP
            | Keyword::LIMIT
            | Keyword::OFFSET
            | Keyword::WINDOW,
        ) => Position::Expression,
        // A `WITH` body that has closed leaves the statement still to be written.
        _ if verb == Some(Keyword::WITH) && matches!(previous.token, Token::RParen) => {
            Position::StatementStart
        }
        _ if verb == Some(Keyword::SELECT) => Position::SelectItem,
        _ => Position::Everything,
    }
}

/// Whether a word begins a value rather than continuing one.
fn starts_value(keyword: Keyword) -> bool {
    matches!(
        keyword,
        Keyword::AND
            | Keyword::OR
            | Keyword::NOT
            | Keyword::WHERE
            | Keyword::HAVING
            | Keyword::QUALIFY
            | Keyword::ON
            | Keyword::SET
            | Keyword::BY
            | Keyword::RETURNING
            | Keyword::WHEN
            | Keyword::THEN
            | Keyword::ELSE
            | Keyword::LIMIT
            | Keyword::OFFSET
            | Keyword::VALUES
            | Keyword::USING
    )
}

fn is_ddl_verb(keyword: Keyword) -> bool {
    matches!(
        keyword,
        Keyword::CREATE | Keyword::ALTER | Keyword::DROP | Keyword::TRUNCATE
    )
}

fn is_ddl_modifier(keyword: Keyword) -> bool {
    matches!(
        keyword,
        Keyword::TEMPORARY | Keyword::TEMP | Keyword::UNIQUE | Keyword::MATERIALIZED | Keyword::OR
    )
}
