/*---------------------------------------------------------------------------------------------
 *  Copyright (C) 2026 Posit Software, PBC. All rights reserved.
 *  Licensed under the Elastic License 2.0. See LICENSE.txt for license information.
 *--------------------------------------------------------------------------------------------*/

//! The SQL analysis the positron-sql extension runs on, compiled to WebAssembly.
//!
//! The extension loads this as a WebAssembly module inside the extension host rather than
//! starting a language server process. That is what lets the statement range provider answer
//! synchronously -- Positron asks for a range the moment the user executes code, and cannot wait
//! for a process to start -- and what makes SQL support available wherever Positron runs,
//! including the web workbench, with no runtime to find on the user's machine.
//!
//! # The interface
//!
//! One entry point, [`sql_analyze`], taking a JSON request and returning a JSON response; see
//! [`api`] for their shape. Strings cross the boundary as UTF-8 in linear memory:
//!
//! - [`sql_alloc`] reserves a buffer for the caller to write a request into.
//! - [`sql_analyze`] consumes that buffer and returns a pointer to a response buffer, whose first
//!   four bytes are its length as a little-endian `u32`, followed by that many bytes of UTF-8.
//! - [`sql_free`] releases a response buffer.
//!
//! Hand written rather than generated by wasm-bindgen: the whole interface is one string in and
//! one string out, which is less code than the glue would be, and it leaves the build a plain
//! `cargo build --target wasm32-unknown-unknown` with no toolchain pinned to a bindgen version.

pub mod api;
pub mod diagnostics;
pub mod dialects;
pub mod scopes;
pub mod sources;
pub mod statements;
pub mod text;

use std::alloc::{alloc, dealloc, Layout};

/// Bytes of length prefix on a response buffer.
const HEADER: usize = 4;

/// The layout of a byte buffer of a given size.
///
/// Buffers are allocated and released through the raw allocator rather than through `Vec`, so
/// that the size freed is exactly the size allocated. `Vec::with_capacity` is free to reserve
/// more than it was asked for, and a buffer freed at the length the other side knows about would
/// then be freed under a layout it was never allocated with.
fn layout(len: usize) -> Layout {
    // Zero-sized allocations are not valid, and an empty request or response is reachable.
    Layout::from_size_align(len.max(1), 1).expect("a byte buffer always has a valid layout")
}

/// Reserves `len` bytes in the module's memory for the caller to write a request into.
///
/// The pointer must be handed back to [`sql_analyze`], which takes ownership of it. There is no
/// separate free for a request buffer, because there is no path that allocates one without going
/// on to analyze it.
///
/// # Safety
///
/// The caller must write exactly `len` bytes of UTF-8 at the returned pointer before calling
/// [`sql_analyze`] with the same pointer and length.
#[no_mangle]
pub extern "C" fn sql_alloc(len: usize) -> *mut u8 {
    unsafe { alloc(layout(len)) }
}

/// Runs one request, returning a length-prefixed response buffer.
///
/// # Safety
///
/// `pointer` and `len` must be a buffer from [`sql_alloc`] holding `len` bytes of UTF-8. The
/// returned pointer must be released with [`sql_free`].
#[no_mangle]
pub unsafe extern "C" fn sql_analyze(pointer: *mut u8, len: usize) -> *mut u8 {
    let request = String::from_utf8_lossy(std::slice::from_raw_parts(pointer, len)).into_owned();
    // Reclaimed here rather than left to the caller: the request has been copied out, and one
    // owner for the buffer is one fewer thing for the two sides to agree about.
    dealloc(pointer, layout(len));

    let response = api::handle(&request);
    // A response that cannot be serialized is a bug in this crate, not something the caller can
    // act on, but it still has to come back as a readable message rather than as a trap.
    let json = serde_json::to_string(&response).unwrap_or_else(|error| {
        format!(r#"{{"kind":"error","message":"could not encode the response: {error}"}}"#)
    });

    let bytes = json.as_bytes();
    let total = HEADER + bytes.len();
    let buffer = alloc(layout(total));
    std::ptr::copy_nonoverlapping((bytes.len() as u32).to_le_bytes().as_ptr(), buffer, HEADER);
    std::ptr::copy_nonoverlapping(bytes.as_ptr(), buffer.add(HEADER), bytes.len());
    buffer
}

/// Releases a response buffer returned by [`sql_analyze`].
///
/// # Safety
///
/// `pointer` must be a buffer returned by [`sql_analyze`] and not already freed.
#[no_mangle]
pub unsafe extern "C" fn sql_free(pointer: *mut u8) {
    let mut length = [0u8; HEADER];
    length.copy_from_slice(std::slice::from_raw_parts(pointer, HEADER));
    dealloc(pointer, layout(HEADER + u32::from_le_bytes(length) as usize));
}
