name: "Setup Python Environment Tools"
description: "Install and build microsoft/python-environment-tools"

env:
  PET_BRANCH: "release/latest"

runs:
  using: "composite"
  steps:
      - name: Checkout Python Environment Tools
        uses: actions/checkout@v4
        with:
          repository: 'microsoft/python-environment-tools'
          path: 'extensions/positron-python/python-env-tools'
          branch: ${{ env.PET_BRANCH }}
          sparse-checkout: |
            crates
            Cargo.toml
            Cargo.lock
          sparse-checkout-cone-mode: false

      - name: Rust Tool Chain setup
        uses: dtolnay/rust-toolchain@stable

      - name: Build Native Binaries
        run: nox --noxfile extensions/positron-python/noxfile.py --session native_build
        shell: bash
