name: Build VS Code Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  package-extension:
    runs-on: ubuntu-latest
    outputs:
      vsixPath: ${{ steps.package_extension.outputs.vsixPath }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install

      - name: Package extension
        uses: HaaLeo/publish-vscode-extension@v2
        id: package_extension
        with:
          pat: not-a-real-pat
          dryRun: true
          preRelease: true

      - name: Upload extension vsix file as a workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: catalog-explorer-${{ github.sha }}
          path: ${{ steps.package_extension.outputs.vsixPath }}
          retention-days: 30
