name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '22.17.0'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          cache: 'npm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node dependencies
        run: npm ci --fetch-timeout 120000

      - name: Lint TypeScript code
        run: npm run lint-check
