// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

'use strict';

export const COMPLETION = 'COMPLETION';
export const COMPLETION_ADD_BRACKETS = 'COMPLETION.ADD_BRACKETS';
export const DEFINITION = 'DEFINITION';
export const HOVER_DEFINITION = 'HOVER_DEFINITION';
export const REFERENCE = 'REFERENCE';
export const SIGNATURE = 'SIGNATURE';
export const SYMBOL = 'SYMBOL';
export const FORMAT_SORT_IMPORTS = 'FORMAT.SORT_IMPORTS';
export const FORMAT = 'FORMAT.FORMAT';
export const FORMAT_ON_TYPE = 'FORMAT.FORMAT_ON_TYPE';
export const EDITOR_LOAD = 'EDITOR.LOAD';
export const LINTING = 'LINTING';
export const GO_TO_OBJECT_DEFINITION = 'GO_TO_OBJECT_DEFINITION';
export const UPDATE_PYSPARK_LIBRARY = 'UPDATE_PYSPARK_LIBRARY';
export const REFACTOR_RENAME = 'REFACTOR_RENAME';
export const REFACTOR_EXTRACT_VAR = 'REFACTOR_EXTRACT_VAR';
export const REFACTOR_EXTRACT_FUNCTION = 'REFACTOR_EXTRACT_FUNCTION';
export const REPL = 'REPL';
export const PYTHON_INTERPRETER = 'PYTHON_INTERPRETER';
export const WORKSPACE_SYMBOLS_BUILD = 'WORKSPACE_SYMBOLS.BUILD';
export const WORKSPACE_SYMBOLS_GO_TO = 'WORKSPACE_SYMBOLS.GO_TO';
export const EXECUTION_CODE = 'EXECUTION_CODE';
export const EXECUTION_DJANGO = 'EXECUTION_DJANGO';
export const DEBUGGER = 'DEBUGGER';
export const DEBUGGER_PERFORMANCE = 'DEBUGGER.PERFORMANCE';
export const UNITTEST_STOP = 'UNITTEST.STOP';
export const UNITTEST_RUN = 'UNITTEST.RUN';
export const UNITTEST_DISCOVER = 'UNITTEST.DISCOVER';
export const UNITTEST_VIEW_OUTPUT = 'UNITTEST.VIEW_OUTPUT';
export const PYTHON_LANGUAGE_SERVER_ENABLED = 'PYTHON_LANGUAGE_SERVER.ENABLED';
export const PYTHON_LANGUAGE_SERVER_DOWNLOADED = 'PYTHON_LANGUAGE_SERVER.DOWNLOADED';
export const PYTHON_LANGUAGE_SERVER_ERROR = 'PYTHON_LANGUAGE_SERVER.ERROR';
export const PYTHON_LANGUAGE_SERVER_STARTUP = 'PYTHON_LANGUAGE_SERVER.STARTUP';
export const PYTHON_LANGUAGE_SERVER_PLATFORM_NOT_SUPPORTED = 'PYTHON_LANGUAGE_SERVER.PLATFORM_NOT_SUPPORTED';
export const TERMINAL_CREATE = 'TERMINAL.CREATE';
