/*---------------------------------------------------------------------------------------------
 *  Copyright (C) 2024-2025 Posit Software, PBC. All rights reserved.
 *  Licensed under the Elastic License 2.0. See LICENSE.txt for license information.
 *--------------------------------------------------------------------------------------------*/

import { localize, localize2 } from '../../../../nls.js';
import { Action2, MenuId, registerAction2 } from '../../../../platform/actions/common/actions.js';
import { ContextKeyExpr } from '../../../../platform/contextkey/common/contextkey.js';
import { ServicesAccessor } from '../../../../platform/instantiation/common/instantiation.js';
import { ICommandService } from '../../../../platform/commands/common/commands.js';
import { INotificationService } from '../../../../platform/notification/common/notification.js';
import { IQuickInputService, IQuickPick, IQuickPickItem, IQuickPickSeparator } from '../../../../platform/quickinput/common/quickInput.js';
import { ThemeIcon } from '../../../../base/common/themables.js';
import { Codicon } from '../../../../base/common/codicons.js';
import { IEditorService } from '../../../services/editor/common/editorService.js';
import { CHAT_OPEN_ACTION_ID } from '../../chat/browser/actions/chatActions.js';
import { ChatModeKind } from '../../chat/common/constants.js';
import { POSITRON_NOTEBOOK_EDITOR_ID } from '../common/positronNotebookCommon.js';
import { getNotebookInstanceFromActiveEditorPane } from './notebookUtils.js';

const ASK_ASSISTANT_ACTION_ID = 'positronNotebook.askAssistant';

/**
 * Interface for quick pick items that represent assistant prompt options
 */
interface PromptQuickPickItem extends IQuickPickItem {
	query: string;
	mode: ChatModeKind;
	/** Flag to indicate this item should trigger AI suggestion generation */
	generateSuggestions?: boolean;
}

/**
 * Predefined prompt options for the assistant quick pick
 */
const ASSISTANT_PREDEFINED_ACTIONS: PromptQuickPickItem[] = [
	{
		label: localize('positronNotebook.assistant.prompt.describe', 'Describe the notebook'),
		detail: localize('positronNotebook.assistant.prompt.describe.detail', 'Get an overview of the notebook\'s contents and structure'),
		query: 'Can you describe the open notebook for me?',
		mode: ChatModeKind.Ask,
		iconClass: ThemeIcon.asClassName(Codicon.book)
	},
	{
		label: localize('positronNotebook.assistant.prompt.comments', 'Add inline comments'),
		detail: localize('positronNotebook.assistant.prompt.comments.detail', 'Add explanatory comments to the selected cell(s)'),
		query: 'Can you add inline comments to the selected cell(s)?',
		mode: ChatModeKind.Edit,
		iconClass: ThemeIcon.asClassName(Codicon.commentAdd)
	},
	{
		label: localize('positronNotebook.assistant.prompt.suggest', 'Suggest next steps'),
		detail: localize('positronNotebook.assistant.prompt.suggest.detail', 'Get recommendations for what to do next with this notebook'),
		query: 'Can you suggest next steps for this notebook?',
		mode: ChatModeKind.Ask,
		iconClass: ThemeIcon.asClassName(Codicon.lightbulb)
	},
	{
		label: localize('positronNotebook.assistant.prompt.generateSuggestions', '✨ Generate AI suggestions...'),
		detail: localize('positronNotebook.assistant.prompt.generateSuggestions.detail', 'Let AI analyze your notebook and suggest relevant actions'),
		query: '', // Will be generated by AI
		mode: ChatModeKind.Agent,
		iconClass: ThemeIcon.asClassName(Codicon.sparkle),
		generateSuggestions: true
	}
];

/**
 * Action that opens the assistant chat with predefined prompt options for the notebook.
 * Users can select a predefined prompt or type their own custom prompt.
 */
export class AskAssistantAction extends Action2 {
	constructor() {
		super({
			id: ASK_ASSISTANT_ACTION_ID,
			title: localize2('askAssistant', 'Ask Assistant'),
			tooltip: localize2('askAssistant.tooltip', 'Ask the assistant about this notebook'),
			icon: ThemeIcon.fromId('positron-assistant'),
			f1: true,
			category: localize2('positronNotebook.category', 'Notebook'),
			positronActionBarOptions: {
				controlType: 'button',
				displayTitle: false
			},
			menu: {
				id: MenuId.EditorActionsLeft,
				group: 'navigation',
				order: 50,
				when: ContextKeyExpr.and(
					ContextKeyExpr.equals('activeEditor', POSITRON_NOTEBOOK_EDITOR_ID),
					ContextKeyExpr.has('config.positron.assistant.notebookMode.enable')
				)
			}
		});
	}

	override async run(accessor: ServicesAccessor): Promise<void> {
		const commandService = accessor.get(ICommandService);
		const quickInputService = accessor.get(IQuickInputService);
		const notificationService = accessor.get(INotificationService);
		const editorService = accessor.get(IEditorService);

		// Get the active notebook instance
		const activeNotebook = getNotebookInstanceFromActiveEditorPane(editorService);
		if (!activeNotebook) {
			return;
		}

		// Create and configure the quick pick (items can include separators)
		const quickPick = quickInputService.createQuickPick<PromptQuickPickItem>();
		quickPick.title = localize('positronNotebook.assistant.quickPick.title', 'Assistant');
		quickPick.description = localize(
			'positronNotebook.assistant.quickPick.description',
			'Type your own prompt or select one of the options below.'
		);
		quickPick.placeholder = localize('positronNotebook.assistant.quickPick.placeholder', 'Type your prompt...');
		quickPick.items = ASSISTANT_PREDEFINED_ACTIONS;
		quickPick.canSelectMany = false;

		// Handle accept with veto pattern for AI generation
		quickPick.onWillAccept((e) => {
			const selected = quickPick.selectedItems[0];

			// Check if "Generate AI suggestions" was selected (type guard for PromptQuickPickItem)
			if (selected && 'generateSuggestions' in selected && selected.generateSuggestions) {
				e.veto(); // Prevent the quick pick from closing

				// Generate suggestions and update the quick pick in place
				this.handleGenerateSuggestions(
					quickPick,
					activeNotebook,
					commandService,
					notificationService
				).catch(() => {
					// Reset state on error (handleGenerateSuggestions already handles item cleanup)
					quickPick.busy = false;
					quickPick.enabled = true;
					quickPick.placeholder = localize('positronNotebook.assistant.quickPick.placeholder', 'Type your prompt...');
					// Ensure items are restored if handleGenerateSuggestions didn't complete
					if (quickPick.items.length === 0 || (quickPick.items[0] as PromptQuickPickItem).pickable === false) {
						quickPick.items = ASSISTANT_PREDEFINED_ACTIONS.filter(item => !item.generateSuggestions);
					}
				});
			}
		});

		// Wait for user selection or custom input
		const result = await new Promise<PromptQuickPickItem | undefined>((resolve) => {
			quickPick.onDidAccept(() => {
				// Check if a predefined item was selected
				const selected = quickPick.selectedItems[0];
				const customValue = quickPick.value.trim();

				if (selected) {
					// User selected a predefined prompt item
					resolve(selected);
				} else if (customValue) {
					// User typed a custom prompt - create a temporary item with their input
					// Default to 'agent' mode for custom prompts
					const customItem: PromptQuickPickItem = {
						label: customValue,
						query: customValue,
						mode: ChatModeKind.Agent
					};
					resolve(customItem);
				} else {
					// No selection and no input
					resolve(undefined);
				}
				quickPick.dispose();
			});

			quickPick.show();

			quickPick.onDidHide(() => {
				quickPick.dispose();
				resolve(undefined);
			});
		});

		// If user selected an item or typed a custom prompt, execute the chat command
		if (result) {
			// Execute the selected/custom prompt (generation suggestions are handled above via veto)
			try {
				await commandService.executeCommand(CHAT_OPEN_ACTION_ID, {
					query: result.query,
					mode: result.mode
				});
			} catch (error) {
				notificationService.error(
					localize(
						'positronNotebook.assistant.error',
						'Failed to open assistant chat: {0}',
						error instanceof Error ? error.message : String(error)
					)
				);
			}
		}
	}

	/**
	 * Handle AI-generated suggestion generation
	 * Updates the quick pick in place with generated suggestions
	 */
	private async handleGenerateSuggestions(
		quickPick: IQuickPick<PromptQuickPickItem>,
		notebook: any,
		commandService: ICommandService,
		notificationService: INotificationService
	): Promise<void> {
		// Create a loading item with animated spinner icon
		const loadingItem: PromptQuickPickItem = {
			label: localize('positronNotebook.assistant.generating.label', 'Generating AI suggestions...'),
			query: '', // Empty query since this is not selectable
			mode: ChatModeKind.Agent,
			iconClass: ThemeIcon.asClassName(ThemeIcon.modify(Codicon.loading, 'spin')),
			pickable: false // Prevent selection of the loading item
		};

		// Update quick pick to show loading state
		quickPick.busy = true;
		quickPick.enabled = false;
		quickPick.placeholder = localize('positronNotebook.assistant.generating.placeholder', 'Generating AI suggestions...');

		// Add loading item in the AI-generated suggestions section (beneath predefined items)
		const separator: IQuickPickSeparator = {
			type: 'separator',
			label: localize('positronNotebook.assistant.aiSuggestions', 'AI-Generated Suggestions')
		};

		quickPick.items = [
			...ASSISTANT_PREDEFINED_ACTIONS.filter(item => !item.generateSuggestions),
			separator as any,
			loadingItem
		];

		try {
			// Call extension command to generate suggestions
			const suggestions = await commandService.executeCommand<PromptQuickPickItem[]>(
				'positron-assistant.generateNotebookSuggestions',
				notebook.uri.toString()
			);

			if (!suggestions || suggestions.length === 0) {
				notificationService.info(
					localize(
						'positronNotebook.assistant.noSuggestions',
						'No suggestions generated. Try selecting cells or executing code first.'
					)
				);
				// Remove loading item and separator, restore original items
				quickPick.items = ASSISTANT_PREDEFINED_ACTIONS.filter(item => !item.generateSuggestions);
				return;
			}

			// Update quick pick items to show predefined actions first, then AI suggestions below
			// Replace the loading item with actual suggestions
			quickPick.items = [
				...ASSISTANT_PREDEFINED_ACTIONS.filter(item => !item.generateSuggestions),
				separator as any,
				...suggestions
			];

			quickPick.placeholder = localize('positronNotebook.assistant.selectAction', 'Select an action');

		} catch (error) {
			notificationService.error(
				localize(
					'positronNotebook.assistant.generateError',
					'Failed to generate suggestions: {0}',
					error instanceof Error ? error.message : String(error)
				)
			);
			// Remove loading item and separator, restore original items on error
			quickPick.items = ASSISTANT_PREDEFINED_ACTIONS.filter(item => !item.generateSuggestions);
		} finally {
			// Reset busy state
			quickPick.busy = false;
			quickPick.enabled = true;
		}
	}
}

registerAction2(AskAssistantAction);

