[tool.autopep8]
max_line_length = 100

[tool.black]
include = 'positron\/.*.py$|positron\/positron_ipykernel\/.*.py$|positron\/positron_ipykernel\/test_positron_.*.py$'
exclude = '''

(
  /(
    .data
    | .vscode
    | lib
    | positron/positron_ipykernel/_vendor
  )/
)
'''
line-length = 100

[tool.isort]
profile = "black"
extend_skip = ['positron/positron_ipykernel/_vendor']
known_first_party = ['positron_ipykernel']
known_third_party = ['positron_ipykernel._vendor']

[tool.pyright]
exclude = ['lib', 'positron/positron_ipykernel/_vendor']
extraPaths = ['lib/python', 'positron/positron_ipykernel/_vendor']
ignore = [
    # Ignore all pre-existing code with issues
    'get-pip.py',
    'install_debugpy.py',
    'normalizeSelection.py',
    'tensorboard_launcher.py',
    'testlauncher.py',
    'visualstudio_py_testlauncher.py',
    'testing_tools/unittest_discovery.py',
    'testing_tools/adapter/report.py',
    'testing_tools/adapter/util.py',
    'testing_tools/adapter/pytest/_discovery.py',
    'testing_tools/adapter/pytest/_pytest_item.py',
    'tests/debug_adapter/test_install_debugpy.py',
    'tests/unittestadapter/helpers.py',
    'tests/testing_tools/adapter/.data',
    'tests/testing_tools/adapter/test___main__.py',
    'tests/testing_tools/adapter/test_discovery.py',
    'tests/testing_tools/adapter/test_functional.py',
    'tests/testing_tools/adapter/test_report.py',
    'tests/testing_tools/adapter/test_util.py',
    'tests/testing_tools/adapter/pytest/test_cli.py',
    'tests/testing_tools/adapter/pytest/test_discovery.py',
    'tests/unittestadapter/.data/unittest_skip/unittest_skip_function.py',
    'tests/pytestadapter/helpers.py'
]

[tool.ruff]
line-length = 100
exclude = [
    "tests/testing_tools/adapter/.data",
    "tests/unittestadapter/.data",
    # --- Start Positron ---
    # Ignore vendored dependencies
    'lib/',
    'positron/positron_ipykernel/_vendor/',
    # --- End Positron ---
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "pep257"
# --- Start Positron ---
[tool.pytest.ini_options]
# Enable colors in the VSCode Test Results pane.
addopts = "--color=yes"
# --- End Positron ---
