/*---------------------------------------------------------------------------------------------
 *  Copyright (C) 2026 Posit Software, PBC. All rights reserved.
 *  Licensed under the Elastic License 2.0. See LICENSE.txt for license information.
 *--------------------------------------------------------------------------------------------*/

// CSS.
import './GhostCellInfoModalDialog.css';

// React.
import React from 'react';

// Other dependencies.
import { localize } from '../../../../../../nls.js';
import { isMacintosh } from '../../../../../../base/common/platform.js';
import { ResolvedChord } from '../../../../../../base/common/keybindings.js';
import { PositronModalReactRenderer } from '../../../../../../base/browser/positronModalReactRenderer.js';
import { OKModalDialog } from '../../../../../browser/positronComponents/positronModalDialog/positronOKModalDialog.js';

// Localized strings.
const dialogTitle = localize('ghostCellInfo.title', 'About Ghost Cell Suggestions');
const gotItButtonLabel = localize('ghostCellInfo.gotIt', 'Got it');

const whatAreGhostCellsHeading = localize('ghostCellInfo.whatAreHeading', 'What are ghost cell suggestions?');
const whatAreGhostCellsText = localize('ghostCellInfo.whatAreText', 'Ghost cell suggestions are AI-generated code recommendations that appear after you execute a cell in your notebook. They help you continue your analysis by suggesting relevant next steps.');

const howDoTheyWorkHeading = localize('ghostCellInfo.howWorkHeading', 'How do they work?');
const howDoTheyWorkText = localize('ghostCellInfo.howWorkText', 'The AI analyzes your notebook context - including previous cells, outputs, and the overall structure - to suggest code that logically follows your current work.');
const keyboardShortcutPrefix = localize('ghostCellInfo.keyboardShortcutPrefix', 'You can manually trigger a suggestion at any time by pressing');
const defaultShortcutChords: string[][] = [isMacintosh ? ['Cmd', 'Shift', 'G'] : ['Ctrl', 'Shift', 'G']];

const GHOST_CELL_SUGGESTION_COMMAND_ID = 'positronNotebook.requestGhostCellSuggestion';

/**
 * Extracts display labels for individual keys from a ResolvedChord.
 */
function chordToKeys(chord: ResolvedChord): string[] {
	const keys: string[] = [];
	if (chord.ctrlKey) { keys.push('Ctrl'); }
	if (chord.metaKey) { keys.push(isMacintosh ? 'Cmd' : 'Win'); }
	if (chord.shiftKey) { keys.push('Shift'); }
	if (chord.altKey) { keys.push(isMacintosh ? 'Option' : 'Alt'); }
	if (chord.keyLabel) { keys.push(chord.keyLabel); }
	return keys;
}

const howToDisableHeading = localize('ghostCellInfo.disableHeading', 'How to disable suggestions');
const howToDisableTextPart1 = localize('ghostCellInfo.disableTextPart1', 'You can disable ghost cell suggestions by clicking "Don\'t suggest again" in the dismiss dropdown, or in ');
const howToDisableTextPart2 = localize('ghostCellInfo.disableTextPart2', '.');
const settingsLinkText = localize('ghostCellInfo.settingsLink', 'settings');
const openSettingLabel = localize('ghostCellInfo.openSetting', 'Open ghost cell suggestion settings');

const currentModelHeading = localize('ghostCellInfo.currentModelHeading', 'Current model');
const currentModelText = localize('ghostCellInfo.currentModelText', 'This suggestion was generated by');
const modelExplanationText = localize('ghostCellInfo.modelExplanation', 'Ghost cell suggestions use a smaller, faster model from your selected provider to keep responses quick and costs low. This may differ from the model shown in the Assistant panel.');

/**
 * GhostCellInfoModalDialogProps interface.
 */
interface GhostCellInfoModalDialogProps {
	renderer: PositronModalReactRenderer;
	modelName?: string;
}

/**
 * GhostCellInfoModalDialog component.
 * Displays information about ghost cell suggestions and how to manage them.
 */
export const GhostCellInfoModalDialog: React.FC<GhostCellInfoModalDialogProps> = ({ renderer, modelName }) => {
	const { commandService, keybindingService } = renderer.services;

	// Resolve the keyboard shortcut dynamically so it reflects custom keybindings.
	// Returns an array of chords, where each chord is an array of key labels.
	const shortcutChords = React.useMemo(() => {
		const binding = keybindingService.lookupKeybinding(GHOST_CELL_SUGGESTION_COMMAND_ID);
		if (binding) {
			const chords = binding.getChords();
			if (chords.length > 0) {
				return chords.map(chordToKeys);
			}
		}
		return defaultShortcutChords;
	}, [keybindingService]);

	const handleClose = React.useCallback(() => {
		renderer.dispose();
	}, [renderer]);

	const handleOpenSetting = React.useCallback((e: React.MouseEvent) => {
		e.preventDefault();
		renderer.dispose(); // Close modal first
		commandService.executeCommand('workbench.action.openSettings', 'positron.assistant.notebook.ghostCellSuggestions');
	}, [renderer, commandService]);

	return (
		<OKModalDialog
			height={modelName ? 520 : 420}
			okButtonTitle={gotItButtonLabel}
			renderer={renderer}
			title={dialogTitle}
			width={480}
			onAccept={handleClose}
			onCancel={handleClose}
		>
			<div className='ghost-cell-info-content'>
				<div className='ghost-cell-info-section'>
					<div className='ghost-cell-info-heading'>{whatAreGhostCellsHeading}</div>
					<div className='ghost-cell-info-text'>{whatAreGhostCellsText}</div>
				</div>
				<div className='ghost-cell-info-section'>
					<div className='ghost-cell-info-heading'>{howDoTheyWorkHeading}</div>
					<div className='ghost-cell-info-text'>{howDoTheyWorkText}</div>
					<div className='ghost-cell-info-text'>
						{keyboardShortcutPrefix}{' '}
						{shortcutChords.map((chord, ci) => (
							<React.Fragment key={ci}>
								{ci > 0 && ' '}
								{chord.map((key, ki) => (
									<React.Fragment key={ki}>
										{ki > 0 && <span className='ghost-cell-info-kbd-separator'>+</span>}
										<kbd className='ghost-cell-info-kbd'>{key}</kbd>
									</React.Fragment>
								))}
							</React.Fragment>
						))}
						.
					</div>
				</div>
				{modelName && (
					<div className='ghost-cell-info-section'>
						<div className='ghost-cell-info-heading'>{currentModelHeading}</div>
						<div className='ghost-cell-info-text'>
							{currentModelText} <strong>{modelName}</strong>.
						</div>
						<div className='ghost-cell-info-text'>
							{modelExplanationText}
						</div>
					</div>
				)}
				<div className='ghost-cell-info-section'>
					<div className='ghost-cell-info-heading'>{howToDisableHeading}</div>
					<div className='ghost-cell-info-text'>
						{howToDisableTextPart1}
						<a
							aria-label={openSettingLabel}
							className='ghost-cell-info-settings-link'
							href=''
							onClick={handleOpenSetting}
						>
							{settingsLinkText}
						</a>
						{howToDisableTextPart2}
					</div>
				</div>
			</div>
		</OKModalDialog>
	);
};
