name: "Install System Dependencies"
description: "Installs system-level dependencies required for building and testing Positron on Ubuntu"

runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      shell: bash
      run: |
        # Prevent apt-get from hanging on interactive prompts
        export DEBIAN_FRONTEND=noninteractive

        # Configure apt-get with timeouts to prevent hanging on slow downloads
        # These options add retry logic and timeouts for network operations
        sudo tee /etc/apt/apt.conf.d/99-timeout > /dev/null <<EOF
        Acquire::http::Timeout "60";
        Acquire::https::Timeout "60";
        Acquire::ftp::Timeout "60";
        Acquire::Retries "3";
        EOF

        # Detect Ubuntu version
        UBUNTU_VERSION=$(lsb_release -rs)
        echo "Running on Ubuntu version: $UBUNTU_VERSION"

        # Install libasound2 or libasound2t64 based on version
        if [[ "$UBUNTU_VERSION" == "24.04" ]]; then
          echo "Installing libasound2t64 for Ubuntu 24.04"
          sudo apt-get update
          sudo apt-get install -y libasound2t64
        else
          echo "Installing libasound2 for older Ubuntu versions"
          sudo apt-get update
          sudo apt-get install -y libasound2
        fi
        sudo apt-get install -y \
          vim curl build-essential clang make cmake git \
          libsodium-dev libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb \
          libgtk-3-0 libgbm1 libnss3 libnspr4 libkrb5-dev libcairo-dev \
          libsdl-pango-dev libjpeg-dev libgif-dev pandoc libgtk-4-1
