name: CI

on:
  push:
    branches:
      # Run the CI workflow only on master for microsoft/vscode-python for now.
      - master

env:
  PYTHON_VERSION: 3.8
  CACHE_NPM_DEPS: cache-npm
  CACHE_OUT_DIRECTORY: cache-out-directory
  CACHE_PIP_DEPS: cache-pip
  # Key for the cache created at the end of the the 'Cache ./pythonFiles/lib/python' step.
  CACHE_PYTHONFILES: cache-pvsc-pythonFiles
  ARTIFACT_NAME_VSIX: ms-python-insiders-vsix
  COVERAGE_REPORTS: tests-coverage-reports
  TEST_RESULTS_DIRECTORY: .

jobs:
  ### Initialization: retrieve, install and cache dependencies
  python-deps:
    name: Install Python Requirements
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v1
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install Python requirements
        run: |
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python/old_ptvsd --no-cache-dir --implementation py --no-deps --upgrade 'ptvsd==4.3.2'
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python/new_ptvsd/no_wheels --no-cache-dir --implementation py --no-deps --upgrade --pre ptvsd

      - name: Install ptvsd wheels
        run: |
          python -m pip --disable-pip-version-check install -r build/debugger-install-requirements.txt
          python ./pythonFiles/install_ptvsd.py

      # Retrieve the list of ptvsd versions from PyPI in order to increase the specificity of the pip cache key,
      # so that the cache gets invalidated as necessary.
      # See https://github.com/microsoft/vscode-python/pull/9843#discussion_r373635221
      - name: curl PyPI to get ptvsd versions
        run: curl --output ptvsd.json https://pypi.org/pypi/ptvsd/json

      - name: Cache pip files
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-${{env.CACHE_PIP_DEPS}}-pip-${{env.PYTHON_VERSION}}-${{hashFiles('requirements.txt')}}-${{hashFiles('build/debugger-install-requirements.txt')}}-${{hashFiles('ptvsd.json')}}

      - name: Cache ./pythonFiles/lib/python
        uses: actions/cache@v1
        with:
          path: ./pythonFiles/lib/python
          key: ${{runner.os}}-${{env.CACHE_PYTHONFILES}}-pythonFiles-${{env.PYTHON_VERSION}}-${{hashFiles('requirements.txt')}}-${{hashFiles('build/debugger-install-requirements.txt')}}-${{hashFiles('ptvsd.json')}}

  js-ts-deps:
    name: Install npm dependencies
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies (npm ci)
        run: npm ci --prefer-offline

      - name: Cache npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

  ### Hygiene + VSIX upload
  compile-hygiene:
    name: Compile, lint, check for errors
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    needs: [js-ts-deps, python-deps]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve cached npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

      - name: Install dependencies (npm ci)
        run: npm ci --prefer-offline

      - name: Run gulp prePublishNonBundle
        run: npx gulp prePublishNonBundle

      - name: Cache the out/ directory
        uses: actions/cache@v1
        with:
          path: ./out
          key: ${{runner.os}}-${{env.CACHE_OUT_DIRECTORY}}-${{hashFiles('src/**')}}

      - name: Check dependencies
        run: npm run checkDependencies

      - name: Run linting on TypeScript code
        run: npx tslint --project tsconfig.json

      - name: Run prettier on TypeScript code
        run: npx prettier 'src/**/*.ts*' --check

      - name: Run prettier on JavaScript code
        run: npx prettier 'build/**/*.js' --check

      - name: Use Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v1
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Run Black on Python code
        run: |
          python -m pip install -U black
          python -m black . --check
        working-directory: pythonFiles

  build-vsix:
    name: Build VSIX
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    needs: [python-deps, js-ts-deps]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve cached npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

      - name: curl PyPI to get ptvsd versions
        run: curl --output ptvsd.json https://pypi.org/pypi/ptvsd/json

      - name: Retrieve cached pythonFiles/ directory
        uses: actions/cache@v1
        with:
          path: ./pythonFiles/lib/python
          key: ${{runner.os}}-${{env.CACHE_PYTHONFILES}}-pythonFiles-${{env.PYTHON_VERSION}}-${{hashFiles('requirements.txt')}}-${{hashFiles('build/debugger-install-requirements.txt')}}-${{hashFiles('ptvsd.json')}}

      - name: Install dependencies (npm ci)
        run: npm ci --prefer-offline

      - name: Clean directory
        run: npm run clean

      # Use the GITHUB_RUN_ID environment variable to update the build number.
      # GITHUB_RUN_ID is a unique number for each run within a repository.
      # This number does not change if you re-run the workflow run.
      - name: Update build number
        run: npm run updateBuildNumber -- --buildNumber $GITHUB_RUN_ID

      - name: Package the VSIX
        run: npm run package

      - uses: actions/upload-artifact@v1
        with:
          name: ${{env.ARTIFACT_NAME_VSIX}}
          path: ms-python-insiders.vsix

  ### Non-smoke tests
  tests:
    name: Tests
    # The value of runs-on is the OS of the current job (specified in the strategy matrix below) instead of being hardcoded.
    runs-on: ${{ matrix.os }}
    if: github.repository == 'microsoft/vscode-python'
    needs: [python-deps, js-ts-deps]
    strategy:
      matrix:
        # We're not running CI on macOS for now because it's one less matrix entry to lower the number of runners used,
        # macOS runners are expensive, and we assume that Ubuntu is enough to cover the UNIX case.
        os: [ubuntu-latest, windows-latest]
        # Run the tests on the oldest and most recent versions of Python.
        python: [2.7, 3.8]
        test-suite: [ts-unit, python-unit, venv, single-workspace, multi-workspace, debugger, functional]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve cached npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Retrieve cached compile output directory
        # Use an id for this step so that its cache-hit output can be accessed and checked in the next step.
        id: out-cache
        uses: actions/cache@v1
        with:
          path: ./out
          key: ${{runner.os}}-${{env.CACHE_OUT_DIRECTORY}}-${{hashFiles('src/**')}}

      - name: Compile if not cached
        run: npx gulp prePublishNonBundle
        if: steps.out-cache.outputs.cache-hit == false

      - name: Use Python ${{matrix.python}}
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python}}

      - name: curl PyPI to get ptvsd versions
        run: curl --output ptvsd.json https://pypi.org/pypi/ptvsd/json

      - name: Retrieve cached pythonFiles/ directory
        uses: actions/cache@v1
        # Use an id for this step so that its cache-hit output can be accessed and checked in the next step.
        id: pythonFiles-cache
        with:
          path: ./pythonFiles/lib/python
          key: ${{runner.os}}-${{env.CACHE_PYTHONFILES}}-pythonFiles-${{env.PYTHON_VERSION}}-${{hashFiles('requirements.txt')}}-${{hashFiles('build/debugger-install-requirements.txt')}}-${{hashFiles('ptvsd.json')}}

      - name: Install Python requirements if not cached
        run: |
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python/old_ptvsd --no-cache-dir --implementation py --no-deps --upgrade 'ptvsd==4.3.2'
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python/new_ptvsd/no_wheels --no-cache-dir --implementation py --no-deps --upgrade --pre ptvsd
        if: steps.pythonFiles-cache.outputs.cache-hit == false

      - name: Install ptvsd wheels if not cached
        run: |
          python -m pip --disable-pip-version-check install -r build/debugger-install-requirements.txt
          python ./pythonFiles/install_ptvsd.py
        if: steps.pythonFiles-cache.outputs.cache-hit == false

      - name: Install test requirements
        run: python -m pip install --upgrade -r build/test-requirements.txt

      - name: Install IPython test requirements
        run: |
          python -m pip install numpy
          python -m pip install --upgrade -r ./build/ipython-test-requirements.txt
        if: matrix.test-suite == 'python-unit'

      - name: Install functional test requirements
        run: |
          python -m pip install numpy
          python -m pip install --upgrade -r ./build/functional-test-requirements.txt
        if: matrix.test-suite == 'functional'

      - name: Prepare environment for venv tests
        env:
          TEST_FILES_SUFFIX: testvirtualenvs
          PYTHON_VIRTUAL_ENVS_LOCATION: './src/tmp/envPaths.json'
        run: |
          # venv/bin or venv\\Scripts (windows)?
          $environmentExecutableFolder = 'bin'
          if ('${{runner.os}}' -match 'windows-latest') {
            $environmentExecutableFolder = 'Scripts'
          }

          # pipenv
          python -m pip install pipenv
          python -m pipenv run python build/ci/addEnvPath.py ${{env.PYTHON_VIRTUAL_ENVS_LOCATION}} pipenvPath

          # venv
          if ('${{matrix.python}}' -like '3.?') {
            python -m venv .venv
            & ".venv/$environmentExecutableFolder/python" ./build/ci/addEnvPath.py ${{env.PYTHON_VIRTUAL_ENVS_LOCATION}} venvPath
          }

          # virtualenv
          python -m pip install virtualenv
          python -m virtualenv .virtualenv
          & ".virtualenv/$environmentExecutableFolder/python" ./build/ci/addEnvPath.py ${{env.PYTHON_VIRTUAL_ENVS_LOCATION}} virtualEnvPath

          # conda

          # 1. For `terminalActivation.testvirtualenvs.test.ts`

          $condaExecPath = Join-Path -Path $Env:CONDA -ChildPath $environmentExecutableFolder | Join-Path -ChildPath conda
          if ('${{runner.os}}' -match 'windows-latest') {
              $condaPythonPath = Join-Path -Path $Env:CONDA -ChildPath python
          } else{
              $condaPythonPath = Join-Path -Path $Env:CONDA -ChildPath $environmentExecutableFolder | Join-Path -ChildPath python
              & $condaPythonPath ./build/ci/addEnvPath.py ${{env.PYTHON_VIRTUAL_ENVS_LOCATION}} condaExecPath $condaExecPath
          }
          & $condaPythonPath ./build/ci/addEnvPath.py ${{env.PYTHON_VIRTUAL_ENVS_LOCATION}} condaPath

          # 2. For `interpreterLocatorService.testvirtualenvs.ts`

          & $condaExecPath create -n "test_env1" -y python
          & $condaExecPath create -p "./test_env2" -y python
          & $condaExecPath create -p "$Env:HOME/test_env3" -y python
        shell: pwsh
        if: matrix.test-suite == 'venv'

      # Run TypeScript unit tests only for Python 3.X.
      - name: Run TypeScript unit tests
        run: npm run test:unittests:cover
        if: matrix.test-suite == 'ts-unit' && startsWith(matrix.python, 3.)

      # Upload unit test coverage reports for later use in the "reports" job.
      - name: Upload unit test coverage reports
        uses: actions/upload-artifact@v1
        with:
          name: ${{runner.os}}-${{env.COVERAGE_REPORTS}}
          path: .nyc_output
        if: matrix.test-suite == 'ts-unit' && startsWith(matrix.python, 3.)

      # Run the Python and IPython tests in our codebase.
      - name: Run Python and IPython unit tests
        run: |
          python pythonFiles/tests/run_all.py
          python -m IPython pythonFiles/tests/run_all.py
        if: matrix.test-suite == 'python-unit'

      # The virtual environment based tests use the `testSingleWorkspace` set of tests
      # with the environment variable `TEST_FILES_SUFFIX` set to `testvirtualenvs`,
      # which is set in the "Prepare environment for venv tests" step.
      # We also use a third-party GitHub Action to install xvfb on Linux,
      # run tests and then clean up the process once the tests ran.
      # See https://github.com/GabrielBB/xvfb-action
      - name: Run venv tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run testSingleWorkspace
        if: matrix.test-suite == 'venv'

      - name: Run single-workspace tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run testSingleWorkspace
        if: matrix.test-suite == 'single-workspace'

      - name: Run multi-workspace tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run testMultiWorkspace
        if: matrix.test-suite == 'multi-workspace'

      - name: Run debugger tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run testDebugger
        if: matrix.test-suite == 'debugger'

      - name: Run functional tests
        run: npm run test:functional
        if: matrix.test-suite == 'functional'

  smoke-tests:
    name: Smoke tests
    # The value of runs-on is the OS of the current job (specified in the strategy matrix below) instead of being hardcoded.
    runs-on: ${{ matrix.os }}
    needs: [build-vsix]
    if: github.repository == 'microsoft/vscode-python'
    strategy:
      matrix:
        # We're not running CI on macOS for now because it's one less matrix entry to lower the number of runners used,
        # macOS runners are expensive, and we assume that Ubuntu is enough to cover the UNIX case.
        os: [ubuntu-latest, windows-latest]
        python: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve cached npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

      - name: Install dependencies (npm ci)
        run: npm ci --prefer-offline

      - name: Download VSIX
        uses: actions/download-artifact@v1
        with:
          name: ${{env.ARTIFACT_NAME_VSIX}}

      # Extract the artifact from its download folder (./${{env.ARTIFACT_NAME_VSIX}}) to the repo root,
      # then delete the download folder and compile the source code.
      - name: Prepare for smoke tests
        run: |
          mv ${{env.ARTIFACT_NAME_VSIX}}/* .
          rm -r ${{env.ARTIFACT_NAME_VSIX}}
          npx tsc -p ./
        shell: bash

      - name: Run smoke tests
        env:
          DISPLAY: 10
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: node ./out/test/smokeTest.js

  coverage:
    name: Coverage reports upload
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    needs: [tests, smoke-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve cached npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

      - name: Install dependencies (npm ci)
        run: npm ci --prefer-offline

      # It isn't possible to specify a regex for artifact names, so we have to download each artifact manually.
      # The name pattern is ${{runner.os}}-${{env.COVERAGE_REPORTS}}, and possible values for runner.os are `Linux`, `Windows`, or `macOS`.
      # See https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#runner-context
      - name: Download Ubuntu test coverage artifacts
        uses: actions/download-artifact@v1
        with:
          name: Linux-${{env.COVERAGE_REPORTS}}

      - name: Extract Ubuntu coverage artifacts to ./nyc_output
        run: |
          mkdir .nyc_output
          mv Linux-${{env.COVERAGE_REPORTS}}/* .nyc_output
          rm -r Linux-${{env.COVERAGE_REPORTS}}

      - name: Generate coverage reports
        run: npm run test:cover:report
        continue-on-error: true

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/cobertura-coverage.xml
