name: "Restore Build Caches"
description: "Restores caches for npm dependencies, built-in extensions, and binaries. Works on both Linux and Windows."

# Platform-Agnostic Design:
# This action automatically detects the platform (Linux/Windows) and uses appropriate
# cache paths. Cache configuration is centralized in .github/scripts/:
# - configure-npm-cache.sh: Sets up npm cache directory
# - log-cache-status.sh: Unified logging for cache operations
#
# When modifying cache paths or keys, update:
# 1. This file (restore-build-caches-v2/action.yml)
# 2. save-build-caches-v2/action.yml (to maintain restore/save parity)

inputs:
  distro:
    description: "Distribution identifier for cache key (default: ubuntu for Linux). Use 'rhel' for RHEL/Rocky Linux. Windows auto-detects to 'windows'."
    required: false
    default: 'ubuntu'
  restore-npm:
    description: "Whether to restore npm cache (default: true)"
    required: false
    default: 'true'
  restore-builtins:
    description: "Whether to restore built-in extensions cache (default: true)"
    required: false
    default: 'true'
  restore-ark:
    description: "Whether to restore Ark binary cache (default: true)"
    required: false
    default: 'true'
  restore-kallichore:
    description: "Whether to restore Kallichore binary cache (default: true)"
    required: false
    default: 'true'

outputs:
  cache-npm-core-hit:
    description: "Whether npm core dependencies cache was restored"
    value: ${{ steps.cache-npm-core.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-npm-extensions-hit:
    description: "Whether npm extensions cache was restored"
    value: ${{ steps.cache-npm-extensions.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-builtins-hit:
    description: "Whether built-in extensions cache was restored"
    value: ${{ steps.cache-builtins.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-ark-hit:
    description: "Whether Ark binary cache was restored"
    value: ${{ steps.cache-ark.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-kallichore-hit:
    description: "Whether Kallichore binary cache was restored"
    value: ${{ steps.cache-kallichore.outputs.cache-hit == 'true' && 'true' || 'false' }}
  extensions-hash:
    description: "Generated hash of all extension package-lock.json files"
    value: ${{ steps.extensions-hash.outputs.hash }}
  package-locks-hash:
    description: "Computed hash of all package-lock.json files (for DRY cache key generation)"
    value: ${{ steps.package-locks-hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: Configure npm cache
      shell: bash
      run: .github/scripts/configure-npm-cache.sh

    - name: Determine effective distro
      id: distro
      shell: bash
      run: |
        # Auto-detect distro for Windows, otherwise use input
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          EFFECTIVE_DISTRO="windows"
        else
          EFFECTIVE_DISTRO="${{ inputs.distro }}"
        fi
        echo "distro=$EFFECTIVE_DISTRO" >> "$GITHUB_OUTPUT"
        echo "Using distro: $EFFECTIVE_DISTRO"

    - name: Generate extensions cache key
      if: ${{ inputs.restore-npm == 'true' }}
      id: extensions-hash
      continue-on-error: true
      shell: bash
      run: .github/scripts/generate-extensions-hash.sh || echo "hash=fallback-$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Generate package-locks cache key
      if: ${{ inputs.restore-npm == 'true' }}
      id: package-locks-hash
      continue-on-error: true
      shell: bash
      run: .github/scripts/generate-package-locks-hash.sh || echo "hash=fallback-$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Restore npm core dependencies cache
      if: ${{ inputs.restore-npm == 'true' }}
      id: cache-npm-core
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          .npm-cache
          node_modules
          build/node_modules
          remote/node_modules
          remote/web/node_modules
          remote/reh-web/node_modules
          test/integration/browser/node_modules
          test/monaco/node_modules
          test/mcp/node_modules
        key: npm-core-v4-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ steps.package-locks-hash.outputs.hash }}

    - name: Restore npm extensions cache
      if: ${{ inputs.restore-npm == 'true' }}
      id: cache-npm-extensions
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          extensions/**/node_modules
          .vscode/**/node_modules
          extensions/positron-assistant/resources
          extensions/positron-python/python-env-tools
          extensions/positron-python/python_files
        key: npm-extensions-v6-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ steps.extensions-hash.outputs.hash }}

    - name: Restore built-in extensions cache
      if: ${{ inputs.restore-builtins == 'true' }}
      id: cache-builtins
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          .build/builtInExtensions
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}
        restore-keys: |
          builtins-${{ runner.os }}-

    - name: Restore Ark binary cache
      if: ${{ inputs.restore-ark == 'true' }}
      id: cache-ark
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          extensions/positron-r/resources/ark
        key: ark-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ hashFiles('extensions/positron-r/package.json') }}
        restore-keys: |
          ark-${{ runner.os }}-${{ steps.distro.outputs.distro }}-

    - name: Restore Kallichore binary cache
      if: ${{ inputs.restore-kallichore == 'true' }}
      id: cache-kallichore
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          extensions/positron-supervisor/resources/kallichore
        key: kallichore-v3-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ hashFiles('extensions/positron-supervisor/package.json') }}
        restore-keys: |
          kallichore-v3-${{ runner.os }}-${{ steps.distro.outputs.distro }}-

    - name: Log cache results
      if: always()
      shell: bash
      env:
        RESTORE_NPM: ${{ inputs.restore-npm }}
        RESTORE_BUILTINS: ${{ inputs.restore-builtins }}
        RESTORE_ARK: ${{ inputs.restore-ark }}
        RESTORE_KALLICHORE: ${{ inputs.restore-kallichore }}
        CACHE_NPM_CORE_HIT: ${{ steps.cache-npm-core.outputs.cache-hit }}
        CACHE_NPM_EXTENSIONS_HIT: ${{ steps.cache-npm-extensions.outputs.cache-hit }}
        CACHE_BUILTINS_HIT: ${{ steps.cache-builtins.outputs.cache-hit }}
        CACHE_ARK_HIT: ${{ steps.cache-ark.outputs.cache-hit }}
        CACHE_KALLICHORE_HIT: ${{ steps.cache-kallichore.outputs.cache-hit }}
      run: .github/scripts/log-cache-status.sh restore
