name: "Setup Build Environment, Install Dependencies, and Compile App"
description: "Installs necessary system dependencies."
runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      shell: bash
      run: |
        # Detect Ubuntu version
        UBUNTU_VERSION=$(lsb_release -rs)
        echo "Running on Ubuntu version: $UBUNTU_VERSION"

        # Install libasound2 or libasound2t64 based on version
        if [[ "$UBUNTU_VERSION" == "24.04" ]]; then
          echo "Installing libasound2t64 for Ubuntu 24.04"
          sudo apt-get update
          sudo apt-get install -y libasound2t64
        else
          echo "Installing libasound2 for older Ubuntu versions"
          sudo apt-get update
          sudo apt-get install -y libasound2
        fi
        sudo apt-get install -y \
          vim curl build-essential clang make cmake git \
          libsodium-dev libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb \
          libgtk-3-0 libgbm1 libnss3 libnspr4 libkrb5-dev libcairo-dev \
          libsdl-pango-dev libjpeg-dev libgif-dev pandoc libgtk-4-1

    - name: Install Node packages
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        POSITRON_GITHUB_RO_PAT: ${{ github.token }}
        POSITRON_PARALLEL_INSTALL: '1'
        POSITRON_NPM_CONCURRENCY: '12'
        NPM_CONFIG_AUDIT: 'false'
        NPM_CONFIG_FUND: 'false'
        NPM_CONFIG_UPDATE_NOTIFIER: 'false'
      run: |
        # Install node-gyp; this is required by some packages
        npm i --global node-gyp

        # Configure npm cache
        NPM_CONFIG_CACHE=${NPM_CONFIG_CACHE:-.npm-cache}
        mkdir -p "$NPM_CONFIG_CACHE"

        # Run npm ci commands in parallel for faster installation
        # Note: extensions/ is handled by root's postinstall script to avoid race conditions with native modules
        pids=()
        npm ci --prefer-offline --no-audit --no-fund --fetch-timeout 120000 --cache "$NPM_CONFIG_CACHE" & pids+=($!)
        npm --prefix build ci --prefer-offline --no-audit --no-fund --fetch-timeout 120000 --cache "$NPM_CONFIG_CACHE" & pids+=($!)
        npm --prefix remote ci --prefer-offline --no-audit --no-fund --fetch-timeout 120000 --cache "$NPM_CONFIG_CACHE" & pids+=($!)
        npm --prefix test/e2e ci --prefer-offline --no-audit --no-fund --fetch-timeout 120000 --cache "$NPM_CONFIG_CACHE" & pids+=($!)

        # Wait for all and check exit codes
        exit_code=0
        for pid in "${pids[@]}"; do
          if ! wait "$pid"; then
            exit_code=1
          fi
        done

        if [ $exit_code -ne 0 ]; then
          echo "One or more npm ci commands failed"
          exit 1
        fi

        echo "All npm ci commands completed successfully"

    - name: Compile and Download
      shell: bash
      run: npm exec -- npm-run-all --max_old_space_size=8192 -lp compile "electron x64" playwright-install

    - name: Set permissions on SUID sandbox helper
      shell: bash
      run: |
        ELECTRON_ROOT=.build/electron
        sudo chown root $ELECTRON_ROOT/chrome-sandbox
        sudo chmod 4755 $ELECTRON_ROOT/chrome-sandbox
        stat $ELECTRON_ROOT/chrome-sandbox

    # Although not directly part of the build environment, this configuration is essential for running unit, integration, and e2e tests.
    - name: Configure xvfb Service
      shell: bash
      run: |
        sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
        sudo chmod +x /etc/init.d/xvfb
        sudo update-rc.d xvfb defaults
        sudo service xvfb start

    # Downloads Builtin Extensions (needed for integration & e2e testing)
    - shell: bash
      run: npm run prelaunch
