/*---------------------------------------------------------------------------------------------
 *  Copyright (C) 2026 Posit Software, PBC. All rights reserved.
 *  Licensed under the Elastic License 2.0. See LICENSE.txt for license information.
 *--------------------------------------------------------------------------------------------*/

import { join } from 'path';
import { test, tags, expect } from './_test.setup';

test.use({
	suiteId: __filename
});

// Reproduces the user-reported scenario: Quarto inline output enabled, a
// notebook console attached (so static plots surface in the Plots pane), and a
// plot generated by running a chunk. The origin button names the .qmd; clicking
// it should navigate back to the source document.
test.describe('Quarto - Inline Output: Plot Attribution', {
	tag: [tags.QUARTO, tags.PLOTS, tags.ARK]
}, () => {

	const fileName = 'simple_plot_r.qmd';

	test.afterEach(async function ({ app, hotKeys }) {
		await hotKeys.closeAllEditors();
		await hotKeys.clearPlots();
		await app.workbench.plots.waitForNoPlots({ timeout: 3000 });
	});

	// FIXME: Currently failing. Root cause: a plot generated by a Quarto chunk
	// surfaces in the Plots pane as a StaticPlotClient built from the runtime
	// output message (StaticPlotClient.fromMessage), which carries no `origin`
	// -- unlike console plots, which arrive via the plot comm with a
	// backend-provided origin. So no origin button appears at all. Forwarding a
	// codeLocation from the Quarto execution manager (done) is necessary but not
	// sufficient; the plots service must also attach an origin to
	// message-sourced static plots (keyed by execution id), or the kernel must
	// include the origin in the static image message.
	test.fixme('R - Plot origin button navigates back to the Quarto source', async function ({ app, openFile, runCommand, hotKeys, r }) {
		const { editors, inlineQuarto, plots } = app.workbench;

		// The notebook console attaches a second tab named after the document, so
		// scope tab assertions to the editor part to disambiguate from it.
		const editorTab = editors.editorPart.getByRole('tab', { name: fileName });

		// Open the Quarto file and wait for the kernel to be ready.
		await openFile(join('workspaces', 'quarto_inline_output', fileName));
		await editors.waitForActiveTab(fileName);
		await inlineQuarto.expectKernelStatusVisible();

		// Attach a notebook console to the document's session. Notebook sessions
		// only surface their static plots in the Plots pane once a console is
		// attached.
		await runCommand('workbench.action.positronConsole.showNotebookConsole');

		// Run the plot chunk (refocus the editor first, since attaching the
		// console moved focus).
		await editorTab.click();
		await inlineQuarto.gotoLine(10);
		await inlineQuarto.runCurrentCell();

		// The plot surfaces in the Plots pane with an origin button naming the
		// source document.
		await plots.waitForCurrentPlot();
		await plots.expectOriginButtonVisible();
		await plots.expectOriginButtonContain(fileName);

		// Close all editors, then click the origin button. It should re-open the
		// Quarto document. (Regression: for .qmd the origin carried no usable
		// location, so clicking did nothing.)
		await hotKeys.closeAllEditors();
		await plots.clickOriginFileButton();
		await expect(editorTab).toBeVisible();
		await expect(editorTab).toHaveClass(/selected/);
	});
});
