/*---------------------------------------------------------------------------------------------
 *  Copyright (C) 2026 Posit Software, PBC. All rights reserved.
 *  Licensed under the Elastic License 2.0. See LICENSE.txt for license information.
 *--------------------------------------------------------------------------------------------*/

import { join } from 'path';
import { test, tags, expect } from './_test.setup';

test.use({
	suiteId: __filename
});

// Reproduces the user-reported scenario: a notebook console is attached to a
// Quarto document (so its static plots surface in the Plots pane), and a plot
// is generated by running a chunk. The plot's info header shows a button
// labeled with the session name, which for a notebook session is the document
// name. Clicking it should navigate to the Quarto source document rather than
// to the notebook console.
test.describe('Quarto - Plot Session Name Attribution', {
	tag: [tags.QUARTO, tags.PLOTS, tags.ARK]
}, () => {

	const fileName = 'simple_plot_r.qmd';
	const otherFileName = 'multiline_statement.r';

	test.afterEach(async function ({ app, hotKeys }) {
		await hotKeys.closeAllEditors();
		await hotKeys.clearPlots();
		await app.workbench.plots.waitForNoPlots({ timeout: 3000 });
	});

	test('R - Plot session name button navigates to the Quarto source', async function ({ app, openFile, runCommand, r }) {
		const { editors, inlineQuarto, plots } = app.workbench;

		// The notebook console attaches a second tab named after the document,
		// so scope tab assertions to the editor part to disambiguate from it.
		const qmdTab = editors.editorPart.getByRole('tab', { name: fileName });

		// Open the Quarto file and wait for the kernel to be ready.
		await openFile(join('workspaces', 'quarto_inline_output', fileName));
		await editors.waitForActiveTab(fileName);
		await inlineQuarto.expectKernelStatusVisible();

		// Attach a notebook console to the document's session. Notebook sessions
		// only surface their static plots in the Plots pane once a console is
		// attached.
		await runCommand('workbench.action.positronConsole.showNotebookConsole');

		// Run the plot chunk (refocus the editor first, since attaching the
		// console moved focus).
		await qmdTab.click();
		await inlineQuarto.gotoLine(10);
		await inlineQuarto.runCurrentCell();

		// The plot surfaces in the Plots pane. Its info header shows a button
		// labeled with the session name, which for a notebook session is the
		// document name.
		await plots.waitForCurrentPlot();
		await plots.expectSessionNameButtonVisible();
		await plots.expectSessionNameButtonContain(fileName);

		// Move the active editor off the Quarto document by opening another file,
		// so we can observe the click navigating back to it.
		await openFile(join('workspaces', 'quarto_inline_output', otherFileName));
		await expect(qmdTab).not.toHaveClass(/selected/);

		// Clicking the session-name button navigates back to the Quarto source
		// document. (Regression: for a notebook session this navigated to the
		// notebook console instead of the source.)
		await plots.clickSessionNameButton();
		await expect(qmdTab).toBeVisible();
		await expect(qmdTab).toHaveClass(/selected/);
	});
});
