name: "Setup Build Environment, Install Dependencies, and Compile App"
description: "Installs necessary system dependencies."
runs:
  using: "composite"
  steps:
    - name: Restore package stores & binaries (via cache-multi-paths)
      id: restore-node-caches
      uses: ./.github/actions/cache-multi-paths

    - name: Install Node packages
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        POSITRON_GITHUB_RO_PAT: ${{ github.token }}
        NPM_CONFIG_CACHE: /root/.npm
        NPM_CONFIG_AUDIT: 'false'
        NPM_CONFIG_FUND: 'false'
        NPM_CONFIG_UPDATE_NOTIFIER: 'false'
      run: |
        # Ensure npm cache dir exists and is writable
        mkdir -p /root/.npm
        npm ci --prefer-offline --no-audit --no-fund --fetch-timeout 120000 --cache "$NPM_CONFIG_CACHE"
        npm --prefix test/e2e ci --prefer-offline --no-audit --no-fund --fetch-timeout 120000 --cache "$NPM_CONFIG_CACHE"

    - name: Compile and Download\
      shell: bash
      run: npm exec -- npm-run-all --max_old_space_size=8192 -p compile "electron x64" playwright-install

    - name: Set permissions on SUID sandbox helper
      shell: bash
      run: |
        ELECTRON_ROOT=.build/electron
        sudo chown root $ELECTRON_ROOT/chrome-sandbox
        sudo chmod 4755 $ELECTRON_ROOT/chrome-sandbox
        stat $ELECTRON_ROOT/chrome-sandbox

    # Downloads Builtin Extensions (needed for integration & e2e testing)
    - name: Prelaunch
      shell: bash
      run: npm run prelaunch
