name: "Setup Build Environment"
description: "Sets up the build environment with all required system dependencies"
runs:
  using: "composite"
  steps:
    - name: Install Build Environment Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y vim curl build-essential clang make cmake git python3-pip python-is-python3 libsodium-dev libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1 libnss3 libnspr4 libasound2 libkrb5-dev libcairo-dev libsdl-pango-dev libjpeg-dev libgif-dev pandoc
        sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
        sudo chmod +x /etc/init.d/xvfb
        sudo update-rc.d xvfb defaults
        sudo service xvfb start

    # Instructions from: https://github.com/conda-forge/miniforge/?tab=readme-ov-file#downloading-the-installer-as-part-of-a-ci-pipeline
    - name: Install Conda (Miniforge3)
      shell: bash
      run: |
        wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
        sudo bash Miniforge3.sh -b -p "${HOME}/conda"
        echo "source \"${HOME}/conda/etc/profile.d/conda.sh\"" >> ~/.bashrc
        source "${HOME}/conda/etc/profile.d/conda.sh"

    - name: Install python dependencies
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/posit-dev/qa-example-content/main/requirements.txt --output requirements.txt
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install ipykernel trcli

    - name: Install rig and R
      shell: bash
      run: |
        curl -Ls https://github.com/r-lib/rig/releases/download/latest/rig-linux-"$(arch)"-latest.tar.gz | $(which sudo) tar xz -C /usr/local
        rig add 4.4.0

    # - name: Install rig and R
    #   shell: bash
    #   run: |
    #     if ! command -v rig &> /dev/null; then
    #       curl -Ls https://github.com/r-lib/rig/releases/download/latest/rig-linux-"$(arch)"-latest.tar.gz | $(which sudo) tar xz -C /usr/local
    #     fi
    #     rig add 4.4.0

    # - name: Set R Library Path
    #   shell: bash
    #   run: echo "R_LIBS_USER=~/.R/library" >> ~/.Renviron
