name: "Setup Build Environment"
description: "Installs necessary system dependencies."
runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          vim curl build-essential clang make cmake git \
          libsodium-dev libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb \
          libgtk-3-0 libgbm1 libnss3 libnspr4 libasound2 libkrb5-dev libcairo-dev \
          libsdl-pango-dev libjpeg-dev libgif-dev pandoc

    - name: Install Specified Python Version
      shell: bash
      env:
        PYTHON_VERSION: "3.10.12"
      run: |
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv

    - name: Set Python Alternatives
      shell: bash
      env:
        PYTHON_VERSION: "3.10.12"
      run: |
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1
        sudo update-alternatives --set python3 /usr/bin/python${PYTHON_VERSION}

    - name: Configure xvfb Service
      shell: bash
      run: |
        sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
        sudo chmod +x /etc/init.d/xvfb
        sudo update-rc.d xvfb defaults
        sudo service xvfb start
