name: "Setup Build Environment, Install Dependencies, and Compile App"
description: "Installs necessary system dependencies."
runs:
  using: "composite"
  steps:
    - name: Install Node packages
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        POSITRON_GITHUB_PAT: ${{ github.token }}
      run: |
        # Perform the main npm command; this installs all Node packages and
        # dependencies
        npm ci --fetch-timeout 120000
        npm --prefix test/e2e ci

    - name: Compile and Download
      shell: bash
      run: npm exec -- npm-run-all --max_old_space_size=4095 -lp compile "electron x64" playwright-install

    - name: Set permissions on SUID sandbox helper
      shell: bash
      run: |
        ELECTRON_ROOT=.build/electron
        sudo chown root $ELECTRON_ROOT/chrome-sandbox
        sudo chmod 4755 $ELECTRON_ROOT/chrome-sandbox
        stat $ELECTRON_ROOT/chrome-sandbox

    # Downloads Builtin Extensions (needed for integration & e2e testing)
    - shell: bash
      run: npm run prelaunch
