name: "Setup Build Environment"
description: "Installs necessary system dependencies."
runs:
  using: "composite"
  steps:
    # - name: Install System Level Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: "3.10.10"

    # - name: Set up R
    #   uses: r-lib/actions/setup-r@v2
    #   with:
    #     r-version: "4.4.0"

    - name: Install Build Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          vim curl build-essential clang make cmake git \
          libsodium-dev libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb \
          libgtk-3-0 libgbm1 libnss3 libnspr4 libasound2 libkrb5-dev libcairo-dev \
          libsdl-pango-dev libjpeg-dev libgif-dev pandoc

    - name: Configure xvfb Service
      shell: bash
      run: |
        sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
        sudo chmod +x /etc/init.d/xvfb
        sudo update-rc.d xvfb defaults
        sudo service xvfb start
