name: "Setup Python"
description: "Install Python dependencies."
runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/posit-dev/qa-example-content/main/requirements.txt --output requirements.txt
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install ipykernel trcli
        python -m pip install nox

    - name: Verify Python Version
      shell: bash
      run: |
        python3 --version
        which python
