name: "Setup Python"
description: "Install Python dependencies and alternate version."
inputs:
  alternate_version:
    description: "The alternate version of Python to install (e.g., 3.13.0)"
    required: true
    default: "3.13.0"
  install_undetectable_interpreters:
    description: "Install undetectable interpreters"
    required: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'

    # Pinning UV due to https://github.com/rstudio/reticulate/issues/1811
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.22"

    - name: Install Python dependencies
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/posit-dev/qa-example-content/main/requirements.txt --output requirements.txt
        uv pip install --system -r requirements.txt
        echo "Checking installed packages..."
        python -m pip list

    - name: Verify Python Version
      shell: bash
      run: |
        python3 --version
        which python

    - name: Install pyenv
      shell: bash
      run: |
        echo "Installing pyenv..."
        curl https://pyenv.run | bash

        # Add pyenv to PATH in bashrc (for later steps and tests)
        echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
        echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc

        # Apply changes for the current session
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv virtualenv-init -)"

        # Verify installation
        pyenv --version

    - name: Install Alternate Python Version
      shell: bash
      run: |
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv virtualenv-init -)"

        PYTHON_ALTERNATE_VERSION="${{ inputs.alternate_version }}"
        echo "Installing Python version $PYTHON_ALTERNATE_VERSION using pyenv..."
        pyenv install -s "$PYTHON_ALTERNATE_VERSION"

        pyenv versions

        pyenv global "$PYTHON_ALTERNATE_VERSION"
        python --version
        python -m pip install --upgrade pip
        python -m pip install ipykernel

        # Undo the change and reset to system Python
        echo "Resetting pyenv to system Python..."
        pyenv global system

        # Verify that Python is reset
        python --version

    - name: Setup Conda Python 3.12 env in scratch
      if: ${{ inputs.install_undetectable_interpreters == 'true' }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        python-version: 3.12.10
        activate-environment: ~/scratch/python-env
        auto-activate-base: false
        conda-remove-defaults: true
        channels: conda-forge
        channel-priority: strict

    - name: Verify Conda Python Installation
      shell: bash -el {0}
      run: |
        conda config --set channels conda-forge
        conda config --set conda-remove-defaults true
        conda config --set channel_priority strict

        conda info
        conda list

    # - name: Create Conda Environment with Python 3.12 in ~/scratch
    #   if: ${{ inputs.install_undetectable_interpreters == 'true' }}
    #   shell: bash
    #   run: |
    #     set -e  # Exit immediately if any command fails

    #     echo "Setting up Conda environment with Python 3.12..."

    #     # Ensure Conda from setup-miniconda is available
    #     source "$CONDA/etc/profile.d/conda.sh"

    #     # Clean up all channel config and enforce conda-forge only
    #     conda config --remove-key channels || true
    #     conda config --add channels conda-forge
    #     conda config --set channel_priority strict
    #     conda config --set conda-remove-defaults true

    #     # Define environment path
    #     CONDA_ENV_DIR="$HOME/scratch/python-env"

    #     # Create a new Conda environment with Python 3.12
    #     conda create -y --override-channels -c conda-forge -p "$CONDA_ENV_DIR" python=3.12.10 pip setuptools

    #     # Verify Python installation
    #     PYTHON_BIN="$CONDA_ENV_DIR/bin/python"

    #     if [[ -x "$PYTHON_BIN" ]]; then
    #         echo "Python successfully installed in Conda environment at $PYTHON_BIN"
    #         $PYTHON_BIN --version
    #     else
    #         echo "Error: Python binary not found in Conda environment!"
    #         exit 1
    #     fi

    #     # Verify Python modules are working
    #     echo "Checking if Python modules work..."
    #     $PYTHON_BIN -c "import venv, sys; print(f'Python {sys.version} modules are working!')"

    #     # Final verification
    #     echo "Final Python check..."
    #     $PYTHON_BIN -c "import sys; print(f'Python {sys.version} is working!')"

    #     echo "Miniconda-based Python 3.12 setup complete!"
