#!/usr/bin/env bash
# ============================================================================
# check-uncached-artifacts.sh - Detect Missing Cache Entries
# ============================================================================
#
# WHAT THIS DOES:
# Finds files created by npm postinstall scripts that aren't cached.
# If these files aren't cached, they'll be missing when cache hits on next run,
# causing mysterious test failures.
#
# THE PROBLEM WE'RE SOLVING:
# npm install runs postinstall scripts that can:
# • Download binaries (Ark, Kallichore, pet)
# • Generate files (Python bytecode, vendored packages)
# • Build native modules (node-gyp)
#
# If these artifacts aren't in cache-paths.sh, they vanish when caches hit!
#
# HOW IT WORKS:
# 1. Workflow captures file tree BEFORE npm install → before.txt
# 2. Workflow runs npm install (postinstall scripts run)
# 3. Workflow captures file tree AFTER npm install → after.txt
# 4. This script diffs them and checks against cache-paths.sh
# 5. Reports any files that should probably be cached
#
# WHAT TO DO IF FILES ARE DETECTED:
#
# Option A - Add to cache (if tests need these files):
#   • Core/build paths: Edit .github/cache-scripts/cache-paths.sh
#   • Volatile extensions: Edit build/npm/dirs.js (volatileExtensions array)
#   • Stable extensions: Already cached automatically!
#   • Verify: Run .github/cache-scripts/verify-cache-paths.sh
#
# Option B - Ignore (if tests don't need these files):
#   • Add pattern to IGNORE_PATTERNS below (Section 3)
#
# USAGE:
# check-uncached-artifacts.sh <before-file> <after-file>
#
# ============================================================================

set -euo pipefail

# ============================================================================
# SECTION 1: Input Validation
# ============================================================================

BEFORE_FILE="$1"
AFTER_FILE="$2"

if [[ ! -f "$BEFORE_FILE" ]] || [[ ! -f "$AFTER_FILE" ]]; then
	echo "❌ Error: File tree snapshots not found"
	echo "Usage: $0 <before-file> <after-file>"
	exit 1
fi

echo "🔍 Checking for uncached postinstall artifacts..."

# ============================================================================
# SECTION 2: Find Files Added by npm install
# ============================================================================
# Compare before/after snapshots to see what postinstall scripts created.
# Exclude node_modules and npm cache (already handled by caching system).

ADDED_FILES=$(comm -13 "$BEFORE_FILE" "$AFTER_FILE" | grep -v "\.npm-cache" | grep -v "node_modules" || true)

# ============================================================================
# SECTION 3: Build Ignore Patterns from Cache Configuration
# ============================================================================
# Load cache paths from single source of truth and build ignore list.
# Anything already in cache-paths.sh doesn't need a warning.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/cache-paths.sh"

IGNORE_PATTERNS=()

# Add all cached paths to ignore list
# (These are already covered by cache-paths.sh, so no warning needed)

while IFS= read -r path; do
	[ -z "$path" ] && continue
	IGNORE_PATTERNS+=("$path")
done <<< "$NPM_CORE_PATHS"

while IFS= read -r path; do
	[ -z "$path" ] && continue
	IGNORE_PATTERNS+=("$path")
done <<< "$NPM_EXTENSIONS_VOLATILE_PATHS"

while IFS= read -r path; do
	[ -z "$path" ] && continue
	IGNORE_PATTERNS+=("$path")
done <<< "$NPM_EXTENSIONS_STABLE_PATHS"

while IFS= read -r path; do
	[ -z "$path" ] && continue
	IGNORE_PATTERNS+=("$path")
done <<< "$BUILTINS_PATHS"

# ----------------------------------------------------------------------------
# Additional Ignore Patterns
# ----------------------------------------------------------------------------
# Files that are safe to ignore even if not explicitly in cache-paths.sh.
# Add patterns here if you're confident tests don't need them.

IGNORE_PATTERNS+=(
	# Python bytecode (auto-generated by Python, harmless to regenerate)
	".pyc"
	"__pycache__"
	".cpython-"
)

# ============================================================================
# SECTION 4: Filter Out Ignored Files
# ============================================================================
# Check each added file against ignore patterns.
# Files matching any pattern are considered "handled" and don't need warnings.

UNCACHED_FILES=""
while IFS= read -r file; do
	[ -z "$file" ] && continue

	IS_IGNORED=false
	for pattern in "${IGNORE_PATTERNS[@]}"; do
		if [[ "$file" == *"$pattern"* ]]; then
			IS_IGNORED=true
			break
		fi
	done

	if [[ "$IS_IGNORED" == false ]]; then
		UNCACHED_FILES="$UNCACHED_FILES$file\n"
	fi
done <<< "$ADDED_FILES"

# ============================================================================
# SECTION 5: Report Results
# ============================================================================
# Show summary and detailed instructions if uncached files are found.

# Count non-empty lines (|| true to handle empty input with set -e)
TOTAL_ADDED=$([ -z "$ADDED_FILES" ] && echo "0" || echo "$ADDED_FILES" | grep -vc '^$' || echo "0")
UNCACHED_COUNT=$([ -z "$UNCACHED_FILES" ] && echo "0" || echo -e "$UNCACHED_FILES" | grep -vc '^$' || echo "0")

echo "Files added outside node_modules: $TOTAL_ADDED"
echo "Files ignored by IGNORE_PATTERNS: $((TOTAL_ADDED - UNCACHED_COUNT))"

if [[ $UNCACHED_COUNT -gt 0 ]]; then
	# Found uncached files - show detailed warning with actionable instructions

	echo ""
	echo "⚠️  WARNING: npm install created $UNCACHED_COUNT files outside node_modules/"
	echo ""
	echo "These files are NOT cached and will be missing when caches hit."
	echo ""
	echo "Files (first 50):"
	echo -e "$UNCACHED_FILES" | grep -v '^$' | head -50
	echo ""
	echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	echo "ACTION REQUIRED: Choose one of the following:"
	echo ""
	echo "✅ Option A: Add to cache (if tests need these files)"
	echo ""
	echo "   For core/build/test paths:"
	echo "     → Edit .github/cache-scripts/cache-paths.sh"
	echo "       Add to NPM_CORE_PATHS or BUILTINS_PATHS section"
	echo ""
	echo "   For extension paths:"
	echo "     → Volatile extensions (python/assistant/r):"
	echo "       Edit build/npm/dirs.js → Add to volatileExtensions array"
	echo "       Entire directory will be cached automatically"
	echo ""
	echo "     → Stable extensions:"
	echo "       Already cached automatically! No action needed."
	echo "       All extension directories not in volatileExtensions are cached"
	echo ""
	echo "   Verify your changes:"
	echo "     → Run: .github/cache-scripts/verify-cache-paths.sh"
	echo ""
	echo "❌ Option B: Ignore (if tests don't need these files)"
	echo ""
	echo "   Add pattern to IGNORE_PATTERNS in this file:"
	echo "     → .github/cache-scripts/check-uncached-artifacts.sh (Section 3, line ~100)"
	echo ""
	echo "   Common patterns to ignore:"
	echo "     • Temporary files: \".tmp\", \".log\""
	echo "     • Generated docs: \"docs/generated\""
	echo "     • Test fixtures: \"test/fixtures/generated\""
	echo ""
	echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	echo ""

	# Also write to GitHub Step Summary for visibility
	if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
		{
			echo "## ⚠️ Uncached Postinstall Artifacts Detected"
			echo ""
			echo "npm install created **$UNCACHED_COUNT files** outside node_modules/ that aren't cached."
			echo ""
			echo "See the \"Check for uncached postinstall artifacts\" step for details and next steps."
		} >> "$GITHUB_STEP_SUMMARY"
	fi

	# Don't fail the build - just warn
	# Humans should decide if these files are critical
	exit 0
else
	echo "✅ No uncached artifacts detected"
	echo ""
	echo "All files created by postinstall scripts are properly cached or ignored."
fi
