/*---------------------------------------------------------------------------------------------
 *  Copyright (C) 2026 Posit Software, PBC. All rights reserved.
 *  Licensed under the Elastic License 2.0. See LICENSE.txt for license information.
 *--------------------------------------------------------------------------------------------*/

import * as assert from 'assert';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {
	detectDatabricksConfigCredentials,
	getDatabricksConfigPath,
	parseIniSections,
} from '../credentials/databricks';

const WORKBENCH_CFG = `# This file was automatically generated by Posit Workbench. Do not edit.
[workbench]
host = https://adb-1234.5.azuredatabricks.net
token = dapi-test-token
`;

suite('parseIniSections', () => {
	test('parses sections, keys, comments, and blank lines', () => {
		const sections = parseIniSections(
			'; comment\n# another\n[one]\na = 1\nb=2\n\n[two]\nc = with = equals\n'
		);
		assert.deepStrictEqual(sections.get('one'), { a: '1', b: '2' });
		assert.deepStrictEqual(sections.get('two'), { c: 'with = equals' });
	});

	test('strips optional surrounding quotes from values', () => {
		const sections = parseIniSections('[p]\ntoken = "quoted"\n');
		assert.deepStrictEqual(sections.get('p'), { token: 'quoted' });
	});

	test('ignores keys outside any section', () => {
		const sections = parseIniSections('stray = 1\n[p]\na = 2\n');
		assert.strictEqual(sections.get('p')?.a, '2');
		assert.strictEqual(sections.size, 1);
	});
});

suite('getDatabricksConfigPath', () => {
	test('prefers DATABRICKS_CONFIG_FILE', () => {
		assert.strictEqual(
			getDatabricksConfigPath({ DATABRICKS_CONFIG_FILE: '/tmp/x/databricks.cfg' }),
			'/tmp/x/databricks.cfg'
		);
	});

	test('expands a leading tilde', () => {
		assert.strictEqual(
			getDatabricksConfigPath({ DATABRICKS_CONFIG_FILE: '~/x.cfg' }),
			path.join(os.homedir(), 'x.cfg')
		);
	});

	test('falls back to ~/.databrickscfg', () => {
		assert.strictEqual(
			getDatabricksConfigPath({}),
			path.join(os.homedir(), '.databrickscfg')
		);
	});
});

suite('detectDatabricksConfigCredentials', () => {
	let dir: string;

	setup(() => {
		dir = fs.mkdtempSync(path.join(os.tmpdir(), 'databricks-cfg-'));
	});
	teardown(() => {
		fs.rmSync(dir, { recursive: true, force: true });
	});

	test('reads the workbench profile from DATABRICKS_CONFIG_FILE', async () => {
		const file = path.join(dir, 'databricks.cfg');
		fs.writeFileSync(file, WORKBENCH_CFG);
		const cred = await detectDatabricksConfigCredentials({
			DATABRICKS_CONFIG_FILE: file,
		});
		assert.deepStrictEqual(cred, {
			token: 'dapi-test-token',
			host: 'https://adb-1234.5.azuredatabricks.net',
			configFile: file,
			profile: 'workbench',
		});
	});

	test('honours DATABRICKS_CONFIG_PROFILE', async () => {
		const file = path.join(dir, 'databricks.cfg');
		fs.writeFileSync(file, '[custom]\nhost = https://h.example.com\ntoken = t\n');
		const cred = await detectDatabricksConfigCredentials({
			DATABRICKS_CONFIG_FILE: file,
			DATABRICKS_CONFIG_PROFILE: 'custom',
		});
		assert.strictEqual(cred?.token, 't');
		assert.strictEqual(cred?.profile, 'custom');
	});

	test('returns undefined when the file is missing', async () => {
		const cred = await detectDatabricksConfigCredentials({
			DATABRICKS_CONFIG_FILE: path.join(dir, 'nope.cfg'),
		});
		assert.strictEqual(cred, undefined);
	});

	test('returns undefined when the profile is absent', async () => {
		const file = path.join(dir, 'databricks.cfg');
		fs.writeFileSync(file, '[other]\ntoken = t\n');
		assert.strictEqual(
			await detectDatabricksConfigCredentials({ DATABRICKS_CONFIG_FILE: file }),
			undefined
		);
	});

	test('returns undefined when the profile has no token', async () => {
		const file = path.join(dir, 'databricks.cfg');
		fs.writeFileSync(file, '[workbench]\nhost = https://h.example.com\n');
		assert.strictEqual(
			await detectDatabricksConfigCredentials({ DATABRICKS_CONFIG_FILE: file }),
			undefined
		);
	});
});
