name: "Generate Report Directory & Send to GH Summary"
description: "Generates a unique REPORT_DIR and appends the report URL to the GitHub Step summary"
inputs:
  bucket-url:
    description: "Base URL of the S3 bucket or CDN for the report"
    required: false
    default: "https://d38p2avprg8il3.cloudfront.net"
  project:
    description: "Playwright project name (e.g., e2e-electron, e2e-firefox). The app-type is extracted from after the first hyphen."
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate REPORT_DIR
      shell: bash
      run: |
        # Strip "e2e-" prefix (or "***-" when masked) from project name
        # e.g., "e2e-electron" → "electron", but "inspect-ai" stays as "inspect-ai"
        APP_TYPE="${{ inputs.project }}"
        APP_TYPE="${APP_TYPE#e2e-}"
        APP_TYPE="${APP_TYPE#***-}"
        echo "Extracted app-type: $APP_TYPE"

        # Detect platform and distro to construct project name
        # Format: apptype-platform[-distro]
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          PROJECT_NAME="${APP_TYPE}-windows"
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          PROJECT_NAME="${APP_TYPE}-mac"
        elif [[ -f /etc/os-release ]]; then
          # Parse Linux distro from os-release
          OS_ID=$(grep "^ID=" /etc/os-release | cut -d= -f2 | tr -d '"')
          OS_ID_LIKE=$(grep "^ID_LIKE=" /etc/os-release 2>/dev/null | cut -d= -f2 | tr -d '"' || echo "")
          case "$OS_ID" in
            ubuntu) DISTRO="ubuntu" ;;
            debian) DISTRO="debian" ;;
            rhel|rocky|centos|fedora|almalinux) DISTRO="rhel" ;;
            opensuse|opensuse-leap|opensuse-tumbleweed|sles) DISTRO="suse" ;;
            *)
              # Check ID_LIKE for derivatives
              if [[ "$OS_ID_LIKE" == *"ubuntu"* ]]; then DISTRO="ubuntu"
              elif [[ "$OS_ID_LIKE" == *"debian"* ]]; then DISTRO="debian"
              elif [[ "$OS_ID_LIKE" == *"rhel"* || "$OS_ID_LIKE" == *"centos"* || "$OS_ID_LIKE" == *"fedora"* ]]; then DISTRO="rhel"
              elif [[ "$OS_ID_LIKE" == *"suse"* || "$OS_ID_LIKE" == *"opensuse"* ]]; then DISTRO="suse"
              else DISTRO="linux"
              fi
              ;;
          esac
          PROJECT_NAME="${APP_TYPE}-linux-${DISTRO}"
        else
          PROJECT_NAME="${APP_TYPE}-linux"
        fi

        REPORT_DIR="playwright-report-${{ github.run_id }}-${{ github.run_attempt }}-${PROJECT_NAME}"

        # Export REPORT_DIR for downstream steps
        echo "REPORT_DIR=$REPORT_DIR" >> $GITHUB_ENV
        echo "Generated REPORT_DIR: $REPORT_DIR"

        # Generate the REPORT_URL
        REPORT_URL="${{ inputs.bucket-url }}/$REPORT_DIR/index.html"
        echo "Report URL: $REPORT_URL"
        echo "REPORT_URL=$REPORT_URL" >> $GITHUB_ENV

        # Append REPORT_URL to the GitHub Step summary
        echo "📄 [Playwright Report]($REPORT_URL) <br>" >> $GITHUB_STEP_SUMMARY
