name: "Generate Report Directory & Send to GH Summary"
description: "Generates a unique REPORT_DIR/REPORT_URL and optionally appends to GitHub Step summary"

# Usage:
#   For sharded workflows - pass the same identifier to all shards + merge job:
#     - uses: ./.github/actions/gen-report-dir
#       with:
#         identifier: ${{ inputs.project }}  # e.g., "e2e-electron"
#
#   For non-sharded workflows - omit identifier to auto-use github.job:
#     - uses: ./.github/actions/gen-report-dir
#
# Outputs (set as environment variables):
#   REPORT_DIR  - Directory name (e.g., "playwright-report-123456-1-electron-ubuntu")
#   REPORT_URL  - Full URL (e.g., "https://...cloudfront.net/playwright-report-.../index.html")

inputs:
  bucket-url:
    description: "Base URL of the S3 bucket or CDN for the report"
    required: false
    default: "https://d38p2avprg8il3.cloudfront.net"
  identifier:
    description: "Report identifier. For sharded workflows, pass the same value to all shards. Defaults to github.job."
    required: false
    default: "${{ github.job }}"
  skip-summary:
    description: "Skip writing to GitHub Step Summary (use when setting URL before tests)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Generate REPORT_DIR
      shell: bash
      run: |
        # Format: playwright-report-{run_id}-{run_attempt}-{identifier}-{os}

        # 1. Process identifier - strip "e2e-" prefix to avoid GitHub secret masking issues
        IDENTIFIER=$(echo "${{ inputs.identifier }}" | sed -e 's/^\*\*\*-//' -e 's/^e2e-//')
        echo "Identifier: $IDENTIFIER"

        # 2. Detect OS/distro
        case "$RUNNER_OS" in
          Windows) OS_SUFFIX="windows" ;;
          macOS)   OS_SUFFIX="macos" ;;
          Linux)
            if [[ -f /etc/os-release ]]; then
              OS_ID=$(grep "^ID=" /etc/os-release | cut -d= -f2 | tr -d '"')
              case "$OS_ID" in
                ubuntu|debian) OS_SUFFIX="$OS_ID" ;;
                rhel|rocky|centos|fedora|almalinux) OS_SUFFIX="rhel" ;;
                opensuse|opensuse-leap|opensuse-tumbleweed) OS_SUFFIX="opensuse" ;;
                sles) OS_SUFFIX="sles" ;;
                *) OS_SUFFIX="linux" ;;
              esac
            else
              OS_SUFFIX="linux"
            fi
            ;;
          *) OS_SUFFIX="unknown" ;;
        esac
        echo "OS: $OS_SUFFIX"

        # 3. Build report directory and URL
        REPORT_DIR="playwright-report-${{ github.run_id }}-${{ github.run_attempt }}-${IDENTIFIER}-${OS_SUFFIX}"
        REPORT_URL="${{ inputs.bucket-url }}/$REPORT_DIR/index.html"

        echo "REPORT_DIR=$REPORT_DIR" >> $GITHUB_ENV
        echo "REPORT_URL=$REPORT_URL" >> $GITHUB_ENV
        echo "Generated: $REPORT_DIR"

        # 4. Optionally append to GitHub Step Summary
        if [[ "${{ inputs.skip-summary }}" != "true" ]]; then
          echo "📄 [Playwright Report]($REPORT_URL) <br>" >> $GITHUB_STEP_SUMMARY
        fi
