name: "Restore Build Caches"
description: "Restores caches for npm dependencies and built-in extensions. Works on both Linux and Windows."

# Platform-Agnostic Design:
# This action automatically detects the platform (Linux/Windows) and uses appropriate
# cache paths. Cache configuration is centralized in .github/scripts/:
# - configure-npm-cache.sh: Sets up npm cache directory
# - log-cache-status.sh: Unified logging for cache operations
# - cache-paths.sh: SINGLE SOURCE OF TRUTH for all cache paths
#
# IMPORTANT: When adding new cache paths:
# 1. Edit .github/scripts/cache-paths.sh ONLY (single source of truth)
# 2. That's it! This action loads paths dynamically from cache-paths.sh
# 3. Run .github/scripts/verify-cache-paths.sh to verify paths load correctly
#
# The paths are loaded at runtime via the "Load cache paths" step below,
# eliminating the need to manually sync multiple files.

inputs:
  distro:
    description: "Distribution identifier for cache key (default: ubuntu for Linux). Use 'rhel' for RHEL/Rocky Linux. Windows auto-detects to 'windows'."
    required: false
    default: 'ubuntu'
  restore-npm-core:
    description: "Whether to restore npm core dependencies cache (default: true)"
    required: false
    default: 'true'
  restore-npm-extensions:
    description: "Whether to restore npm extensions cache (default: true)"
    required: false
    default: 'true'
  restore-builtins:
    description: "Whether to restore built-in extensions cache (default: true)"
    required: false
    default: 'true'
  restore-playwright:
    description: "Whether to restore Playwright browsers cache (default: true)"
    required: false
    default: 'true'

outputs:
  cache-npm-core-hit:
    description: "Whether npm core dependencies cache was restored"
    value: ${{ steps.cache-npm-core.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-npm-extensions-volatile-hit:
    description: "Whether npm volatile extensions cache (python, assistant, r) was restored"
    value: ${{ steps.cache-npm-extensions-volatile.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-npm-extensions-stable-hit:
    description: "Whether npm stable extensions cache (all except python, assistant, r) was restored"
    value: ${{ steps.cache-npm-extensions-stable.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-builtins-hit:
    description: "Whether built-in extensions cache was restored"
    value: ${{ steps.cache-builtins.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-playwright-hit:
    description: "Whether Playwright browsers cache was restored"
    value: ${{ steps.cache-playwright.outputs.cache-hit == 'true' && 'true' || 'false' }}
  extensions-volatile-hash:
    description: "Generated hash for volatile extensions (python, assistant, r)"
    value: ${{ steps.extensions-volatile-hash.outputs.hash }}
  extensions-stable-hash:
    description: "Generated hash for stable extensions (all except python, assistant, r)"
    value: ${{ steps.extensions-stable-hash.outputs.hash }}
  package-locks-hash:
    description: "Computed hash of all package-lock.json files (for DRY cache key generation)"
    value: ${{ steps.package-locks-hash.outputs.hash }}
  playwright-version:
    description: "Detected Playwright version from package.json"
    value: ${{ steps.playwright-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Verify cache paths configuration
      shell: bash
      run: |
        echo "::group::ðŸ” Verifying cache paths"
        .github/scripts/verify-cache-paths.sh
        echo "::endgroup::"

    - name: Configure npm cache
      shell: bash
      run: .github/scripts/configure-npm-cache.sh

    - name: Determine effective distro
      id: distro
      shell: bash
      run: |
        # Auto-detect distro for Windows, otherwise use input
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          EFFECTIVE_DISTRO="windows"
        else
          EFFECTIVE_DISTRO="${{ inputs.distro }}"
        fi
        echo "distro=$EFFECTIVE_DISTRO" >> "$GITHUB_OUTPUT"
        echo "Using distro: $EFFECTIVE_DISTRO"

    - name: Load cache paths from source of truth
      id: cache-paths
      shell: bash
      run: |
        echo "::group::ðŸ“¦ Loading cache paths from cache-paths.sh"
        source .github/scripts/cache-paths.sh

        echo "âœ… npm-core: $(echo "$NPM_CORE_PATHS" | wc -l | tr -d ' ') paths"
        echo "$NPM_CORE_PATHS" | sed 's/^/  â†’ /'
        echo ""
        echo "âœ… npm-extensions: $(echo "$NPM_EXTENSIONS_PATHS" | wc -l | tr -d ' ') paths"
        echo "$NPM_EXTENSIONS_PATHS" | sed 's/^/  â†’ /'
        echo ""
        echo "âœ… builtins: $(echo "$BUILTINS_PATHS" | wc -l | tr -d ' ') paths"
        echo "$BUILTINS_PATHS" | sed 's/^/  â†’ /'

        output_to_github_actions
        echo "::endgroup::"

    - name: Generate volatile extensions cache key
      if: ${{ inputs.restore-npm-extensions == 'true' }}
      id: extensions-volatile-hash
      continue-on-error: true
      shell: bash
      run: |
        if ! .github/scripts/generate-extensions-hash.sh --filter volatile; then
          echo "::warning::Volatile extensions hash generation failed - caching will be degraded"
          echo "âš ï¸ **Cache Warning**: Volatile extensions hash generation failed" >> "$GITHUB_STEP_SUMMARY"
          echo "hash=fallback-extensions-volatile-$(date +%s)" >> "$GITHUB_OUTPUT"
        fi

    - name: Generate stable extensions cache key
      if: ${{ inputs.restore-npm-extensions == 'true' }}
      id: extensions-stable-hash
      continue-on-error: true
      shell: bash
      run: |
        if ! .github/scripts/generate-extensions-hash.sh --filter stable; then
          echo "::warning::Stable extensions hash generation failed - caching will be degraded"
          echo "âš ï¸ **Cache Warning**: Stable extensions hash generation failed" >> "$GITHUB_STEP_SUMMARY"
          echo "hash=fallback-extensions-stable-$(date +%s)" >> "$GITHUB_OUTPUT"
        fi

    - name: Generate package-locks cache key
      if: ${{ inputs.restore-npm-core == 'true' }}
      id: package-locks-hash
      continue-on-error: true
      shell: bash
      run: |
        if ! .github/scripts/generate-package-locks-hash.sh; then
          echo "::warning::Package-locks hash generation failed - caching will be degraded"
          echo "âš ï¸ **Cache Warning**: Package-locks hash generation failed" >> "$GITHUB_STEP_SUMMARY"
          echo "hash=fallback-package-locks-$(date +%s)" >> "$GITHUB_OUTPUT"
        fi

    - name: Restore npm core dependencies cache
      if: ${{ inputs.restore-npm-core == 'true' }}
      id: cache-npm-core
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.cache-paths.outputs.npm-core-paths }}
        key: npm-core-v4-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ steps.package-locks-hash.outputs.hash }}

    - name: Restore npm volatile extensions cache
      if: ${{ inputs.restore-npm-extensions == 'true' }}
      id: cache-npm-extensions-volatile
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.cache-paths.outputs.npm-extensions-volatile-paths }}
        key: npm-extensions-volatile-v1-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ steps.extensions-volatile-hash.outputs.hash }}

    - name: Restore npm stable extensions cache
      if: ${{ inputs.restore-npm-extensions == 'true' }}
      id: cache-npm-extensions-stable
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.cache-paths.outputs.npm-extensions-stable-paths }}
        key: npm-extensions-stable-v1-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ steps.extensions-stable-hash.outputs.hash }}

    - name: Restore built-in extensions cache
      if: ${{ inputs.restore-builtins == 'true' }}
      id: cache-builtins
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.cache-paths.outputs.builtins-paths }}
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}
        restore-keys: |
          builtins-${{ runner.os }}-

    - name: Get Playwright version
      if: ${{ inputs.restore-playwright == 'true' }}
      id: playwright-version
      continue-on-error: true
      shell: bash
      run: .github/scripts/get-playwright-version.sh

    - name: Restore Playwright browsers cache
      if: ${{ inputs.restore-playwright == 'true' }}
      id: cache-playwright
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.cache-paths.outputs.playwright-paths }}
        key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Detect partial cache hits (restore-key matches)
      if: always()
      id: detect-partials
      shell: bash
      run: |
        # Detect if restore-key matched (cache-hit: false but cache was restored)
        # Check if cache directories have content when cache-hit is false

        npm_core_partial="false"
        npm_extensions_volatile_partial="false"
        npm_extensions_stable_partial="false"
        builtins_partial="false"
        playwright_partial="false"

        # Check npm-core: if cache-hit is false but .npm-cache has content
        if [[ "${{ steps.cache-npm-core.outputs.cache-hit }}" == "false" ]] && \
           [[ -d ".npm-cache" ]] && [[ -n "$(ls -A .npm-cache 2>/dev/null)" ]]; then
          npm_core_partial="true"
        fi

        # Check npm-extensions-volatile: if cache-hit is false but volatile extension node_modules exist
        if [[ "${{ steps.cache-npm-extensions-volatile.outputs.cache-hit }}" == "false" ]]; then
          if [[ -d "extensions/positron-python/node_modules" ]] || \
             [[ -d "extensions/positron-assistant/node_modules" ]] || \
             [[ -d "extensions/positron-r/node_modules" ]]; then
            npm_extensions_volatile_partial="true"
          fi
        fi

        # Check npm-extensions-stable: if cache-hit is false but any stable extension node_modules exist
        if [[ "${{ steps.cache-npm-extensions-stable.outputs.cache-hit }}" == "false" ]]; then
          # Check for any extension node_modules that isn't volatile
          for dir in extensions/*/node_modules; do
            if [[ -d "$dir" ]]; then
              ext_name=$(echo "$dir" | sed 's|extensions/\(.*\)/node_modules|\1|')
              if [[ "$ext_name" != "positron-python" ]] && \
                 [[ "$ext_name" != "positron-assistant" ]] && \
                 [[ "$ext_name" != "positron-r" ]]; then
                npm_extensions_stable_partial="true"
                break
              fi
            fi
          done
        fi

        # Check builtins: if cache-hit is false but .build/builtInExtensions exists
        if [[ "${{ steps.cache-builtins.outputs.cache-hit }}" == "false" ]] && \
           [[ -d ".build/builtInExtensions" ]] && [[ -n "$(ls -A .build/builtInExtensions 2>/dev/null)" ]]; then
          builtins_partial="true"
        fi

        # Check Playwright: if cache-hit is false but ~/.cache/ms-playwright exists
        if [[ "${{ steps.cache-playwright.outputs.cache-hit }}" == "false" ]] && \
           [[ -d "$HOME/.cache/ms-playwright" ]] && [[ -n "$(ls -A $HOME/.cache/ms-playwright 2>/dev/null)" ]]; then
          playwright_partial="true"
        fi

        echo "npm-core-partial=$npm_core_partial" >> "$GITHUB_OUTPUT"
        echo "npm-extensions-volatile-partial=$npm_extensions_volatile_partial" >> "$GITHUB_OUTPUT"
        echo "npm-extensions-stable-partial=$npm_extensions_stable_partial" >> "$GITHUB_OUTPUT"
        echo "builtins-partial=$builtins_partial" >> "$GITHUB_OUTPUT"
        echo "playwright-partial=$playwright_partial" >> "$GITHUB_OUTPUT"

    - name: Log cache results
      if: always()
      shell: bash
      env:
        RESTORE_NPM_CORE: ${{ inputs.restore-npm-core }}
        RESTORE_NPM_EXTENSIONS: ${{ inputs.restore-npm-extensions }}
        RESTORE_BUILTINS: ${{ inputs.restore-builtins }}
        RESTORE_PLAYWRIGHT: ${{ inputs.restore-playwright }}
        CACHE_NPM_CORE_HIT: ${{ steps.cache-npm-core.outputs.cache-hit }}
        CACHE_NPM_EXTENSIONS_VOLATILE_HIT: ${{ steps.cache-npm-extensions-volatile.outputs.cache-hit }}
        CACHE_NPM_EXTENSIONS_STABLE_HIT: ${{ steps.cache-npm-extensions-stable.outputs.cache-hit }}
        CACHE_BUILTINS_HIT: ${{ steps.cache-builtins.outputs.cache-hit }}
        CACHE_PLAYWRIGHT_HIT: ${{ steps.cache-playwright.outputs.cache-hit }}
        CACHE_NPM_CORE_PARTIAL: ${{ steps.detect-partials.outputs.npm-core-partial }}
        CACHE_NPM_EXTENSIONS_VOLATILE_PARTIAL: ${{ steps.detect-partials.outputs.npm-extensions-volatile-partial }}
        CACHE_NPM_EXTENSIONS_STABLE_PARTIAL: ${{ steps.detect-partials.outputs.npm-extensions-stable-partial }}
        CACHE_BUILTINS_PARTIAL: ${{ steps.detect-partials.outputs.builtins-partial }}
        CACHE_PLAYWRIGHT_PARTIAL: ${{ steps.detect-partials.outputs.playwright-partial }}
      run: .github/scripts/log-cache-status.sh restore
