name: "Restore Build Caches"
description: "Restores caches for npm dependencies, Playwright browsers, Electron binaries, and built-in extensions."

inputs:
  restore-npm:
    description: "Whether to restore npm cache (default: true)"
    required: false
    default: 'true'
  restore-playwright:
    description: "Whether to restore Playwright cache (default: true)"
    required: false
    default: 'true'
  restore-electron:
    description: "Whether to restore Electron cache (default: true)"
    required: false
    default: 'true'
  restore-builtins:
    description: "Whether to restore built-in extensions cache (default: true)"
    required: false
    default: 'true'

outputs:
  cache-playwright-hit:
    description: "Whether Playwright cache was restored"
    value: ${{ steps.cache-playwright.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-npm-hit:
    description: "Whether npm cache was restored"
    value: ${{ steps.cache-npm.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-electron-hit:
    description: "Whether Electron cache was restored"
    value: ${{ steps.cache-electron.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-builtins-hit:
    description: "Whether built-in extensions cache was restored"
    value: ${{ steps.cache-builtins.outputs.cache-hit == 'true' && 'true' || 'false' }}
  extensions-hash:
    description: "Generated hash of all extension package-lock.json files"
    value: ${{ steps.extensions-hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: Configure local caches
      shell: bash
      run: |
        echo "NPM_CONFIG_CACHE=.npm-cache" >> "$GITHUB_ENV"
        echo "PIP_CACHE_DIR=.pip-cache" >> "$GITHUB_ENV"
        mkdir -p .npm-cache .pip-cache .versions

    - name: Generate extensions cache key
      if: ${{ inputs.restore-npm == 'true' }}
      id: extensions-hash
      shell: bash
      run: |
        # Generate a hash of all extension + .vscode package-lock.json files
        # Tried using hashFiles() with glob patterns, but it didn't work as expected so building own hash
        EXTENSIONS_HASH=$(find extensions .vscode -maxdepth 3 -name "package-lock.json" -type f 2>/dev/null | sort | xargs cat | sha256sum | cut -d' ' -f1)
        echo "hash=$EXTENSIONS_HASH" >> $GITHUB_OUTPUT
        echo "Generated extensions hash: $EXTENSIONS_HASH"

    - name: Restore npm dependencies cache
      if: ${{ inputs.restore-npm == 'true' }}
      id: cache-npm
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          .npm-cache  # npm's internal package tarball cache (safe to restore unconditionally)
          node_modules
          build/node_modules
          extensions
          .vscode
          remote/node_modules
          test/e2e/node_modules
        # Hash main package-lock files + programmatically generated extensions hash
        # Cache version v2 (bump to v3 when you need to invalidate all caches, e.g., major toolchain changes)
        # Note: test-unit uses hashFiles('.nvmrc') for automatic Node version invalidation
        # No restore-keys to avoid partial matches that could restore wrong extension versions
        key: npm-v2-${{ runner.os }}-${{ hashFiles('package-lock.json', 'build/package-lock.json', 'remote/package-lock.json', 'test/e2e/package-lock.json') }}-${{ steps.extensions-hash.outputs.hash }}

    - name: Restore Playwright browsers cache
      if: ${{ inputs.restore-playwright == 'true' }}
      id: cache-playwright
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/ms-playwright
          /root/.cache/ms-playwright
          /github/home/.cache/ms-playwright
        # Include the e2e lockfile too in case test/e2e has its own playwright deps
        key: playwright-v3-${{ runner.os }}-${{ hashFiles('package-lock.json', 'test/e2e/package-lock.json') }}

    - name: Restore Electron binary cache
      if: ${{ inputs.restore-electron == 'true' }}
      id: cache-electron
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
          /root/.cache/electron
          /root/.cache/electron-builder
          /github/home/.cache/electron
          /github/home/.cache/electron-builder
        # electron binaries are tied to package-lock and the electron version in package.json
        key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}

    - name: Restore built-in extensions cache
      if: ${{ inputs.restore-builtins == 'true' }}
      id: cache-builtins
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          .build/builtInExtensions
        # product.json contains the list and versions of built-in extensions
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}

    - name: Log cache results
      if: always()
      shell: bash
      run: |
        echo "Cache results:"

        # npm
        if [[ "${{ inputs.restore-npm }}" == "true" ]]; then
          echo "  npm:         hit=${{ steps['cache-npm'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  npm:         skipped (disabled)"
        fi

        # playwright
        if [[ "${{ inputs.restore-playwright }}" == "true" ]]; then
          echo "  playwright:  hit=${{ steps['cache-playwright'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  playwright:  skipped (disabled)"
        fi

        # electron
        if [[ "${{ inputs.restore-electron }}" == "true" ]]; then
          echo "  electron:    hit=${{ steps['cache-electron'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  electron:    skipped (disabled)"
        fi

        # builtins
        if [[ "${{ inputs.restore-builtins }}" == "true" ]]; then
          echo "  builtins:    hit=${{ steps['cache-builtins'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  builtins:    skipped (disabled)"
        fi
