/**
 * Kallichore API
 * Kallichore is a Jupyter kernel gateway and supervisor
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@posit.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RestartSession {
    /**
    * The desired working directory for the session after restart, if different from the session\'s working directory at startup
    */
    'workingDirectory'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workingDirectory",
            "baseName": "working_directory",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RestartSession.attributeTypeMap;
    }
}

