name: "Restore Cache: Multiple Directories"
description: "Restores cache for node_modules, build, extensions, and remote directories"
runs:
  using: "composite"
  steps:
    # Restore cache for node_modules
    - name: Restore cache for node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: root-node-modules-v6-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          root-node-modules-v6-${{ runner.os }}-

    # Restore cache for build
    - name: Restore cache for build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: build/node_modules
        key: build-node-modules-v6-${{ runner.os }}-${{ hashFiles('build/yarn.lock') }}
        restore-keys: |
          build-node-modules-v6-${{ runner.os }}-

    # Restore cache for extensions
    - name: Restore cache for extensions
      id: cache-extensions
      uses: actions/cache@v4
      with:
        path: |
          extensions
          extensions/**/node_modules
        key: extensions-v6-${{ runner.os }}-${{ hashFiles('extensions/yarn.lock') }}
        restore-keys: |
          extensions-v6-${{ runner.os }}-

    # Restore cache for remote
    - name: Restore cache for remote
      id: cache-remote
      uses: actions/cache@v4
      with:
        path: |
          remote/node_modules
          remote/**/node_modules
        key: remote-node-modules-v6-${{ runner.os }}-${{ hashFiles('remote/yarn.lock') }}
        restore-keys: |
          remote-node-modules-v6-${{ runner.os }}-
