/*---------------------------------------------------------------------------------------------
 *  Copyright (C) 2026 Posit Software, PBC. All rights reserved.
 *  Licensed under the Elastic License 2.0. See LICENSE.txt for license information.
 *--------------------------------------------------------------------------------------------*/

import { join } from 'path';
import { test, tags } from '../_test.setup';

test.use({
	suiteId: __filename
});

// Runs in the default configuration (Quarto inline output disabled), so a plot
// generated by a chunk surfaces in the Plots pane rather than inline. This
// mirrors the user-reported scenario where the plot origin button names the
// .qmd but clicking it does not navigate to the source.
test.describe('Plot File Attribution - Quarto', {
	tag: [tags.PLOTS, tags.ARK]
}, () => {

	const fileName = 'simple_plot_r.qmd';

	test.afterEach(async function ({ app, hotKeys }) {
		await hotKeys.closeAllEditors();
		await hotKeys.clearPlots();
		await app.workbench.plots.waitForNoPlots({ timeout: 3000 });
	});

	test('R - Plot origin button navigates back to the Quarto source', async function ({ app, openFile, hotKeys, r }) {
		const { editors, inlineQuarto, plots } = app.workbench;

		// Open the Quarto file and put the cursor inside the plot chunk.
		await openFile(join('workspaces', 'quarto_inline_output', fileName));
		await editors.waitForActiveTab(fileName);
		await inlineQuarto.gotoLine(10);

		// Run the current chunk. With inline output disabled this routes through
		// the Quarto extension's executeCode path.
		await hotKeys.runCurrentQuartoCell();

		// The plot surfaces in the Plots pane with an origin button naming the
		// source document.
		await plots.waitForCurrentPlot();
		await plots.expectOriginButtonVisible();
		await plots.expectOriginButtonContain(fileName);

		// Close all editors, then click the origin button. It should re-open the
		// Quarto document.
		await hotKeys.closeAllEditors();
		await plots.clickOriginFileButton();
		await editors.verifyTab(fileName, { isVisible: true, isSelected: true });
	});
});
