name: "Cache: Package Stores & Binaries"
description: "Portable caches for npm tarballs and versioned binaries (ark/kallichore)."

inputs:
  node-version:
    description: "Node.js version for cache key (e.g., 20.x)."
    required: false
    default: ""

outputs:
  cache-npm-hit:
    description: "Whether the npm cache restored a hit ('true' or 'false')."
    value: ${{ steps.cache-npm.outputs.cache-hit }}
  cache-ark-hit:
    description: "Whether the ark binary cache restored a hit ('true' or 'false')."
    value: ${{ steps.cache-binaries-ark.outputs.cache-hit }}
  cache-kallichore-hit:
    description: "Whether the kallichore binary cache restored a hit ('true' or 'false')."
    value: ${{ steps.cache-binaries-kallichore.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    # Portable cache dirs (same path on Linux/macOS/Windows runners)
    - name: Configure local caches
      shell: bash
      run: |
        echo "NPM_CONFIG_CACHE=.npm-cache" >> "$GITHUB_ENV"
        echo "PIP_CACHE_DIR=.pip-cache" >> "$GITHUB_ENV"
        mkdir -p .npm-cache .pip-cache .versions

    # Single npm tarball cache (works with `npm ci`)
    - name: Cache npm tarball store
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: .npm-cache
        key: >
          npm-cache-${{ runner.os }}-node-${{ inputs.node-version || 'unknown' }}-${{
            hashFiles('package-lock.json', 'build/package-lock.json', 'extensions/**/package-lock.json', 'remote/**/package-lock.json')
          }}
        restore-keys: |
          npm-cache-${{ runner.os }}-node-${{ inputs.node-version || 'unknown' }}-
          npm-cache-${{ runner.os }}-

    # If you want pip caching later, uncomment the block below.
    # - name: Cache pip wheels
    #   id: cache-pip
    #   uses: actions/cache@v4
    #   with:
    #     path: .pip-cache
    #     key: pip-cache-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
    #     restore-keys: |
    #       pip-cache-${{ runner.os }}-

    # -------- Versioned binaries (ark) --------
    - name: Cache ark binary
      id: cache-binaries-ark
      uses: actions/cache@v4
      with:
        # Cache both built/downloaded resources used by the extension and a repo-root dev build directory
        path: |
          extensions/positron-r/resources/ark
          ./ark
        # Use the extension package.json as the key source so updates to the declared binary version invalidates cache
        key: ark-bin-${{ runner.os }}-${{ hashFiles('extensions/positron-r/package.json') }}
        restore-keys: |
          ark-bin-${{ runner.os }}-

    # -------- Versioned binaries (kallichore) --------
    - name: Cache kallichore binary
      id: cache-binaries-kallichore
      uses: actions/cache@v4
      with:
        path: |
          extensions/positron-supervisor/resources/kallichore
          ./kallichore
        key: kallichore-bin-${{ runner.os }}-${{ hashFiles('extensions/positron-supervisor/package.json') }}
        restore-keys: |
          kallichore-bin-${{ runner.os }}-

