name: "Cache Multiple Directories"
description: "Restores/Saves cache for node_modules, build, extensions, etc"
runs:
  using: "composite"
  steps:

    - name: Cache 'root'
      id: cache-root
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: cache-root-v1-${{ runner.os }}-${{ hashFiles('./yarn.lock') }}

    - name: Cache 'build'
      id: cache-build
      uses: actions/cache@v4
      with:
        path: ./build/node_modules
        key: cache-build-v1-${{ runner.os }}-${{ hashFiles('build/yarn.lock') }}

    - name: Cache 'extensions'
      id: cache-extensions
      uses: actions/cache@v4
      with:
        path: ./extensions/node_modules
        key: cache-extensions-v1-${{ runner.os }}-${{ hashFiles('extensions/**/yarn.lock') }}

    - name: Cache 'remote'
      id: cache-remote
      uses: actions/cache@v4
      with:
        path: ./remote/node_modules
        key: cache-remote-v1-${{ runner.os }}-${{ hashFiles('remote/**/yarn.lock') }}
