name: "Cache: Package Stores & Binaries"
description: "Save and restore caches for multiple package managers and binaries."

outputs:
  cache-npm-hit:
    description: "Whether npm cache was restored"
    value: ${{ steps.cache-npm.outputs.cache-hit }}
  cache-playwright-hit:
    description: "Whether Playwright cache was restored"
    value: ${{ steps.cache-playwright.outputs.cache-hit }}
  cache-electron-hit:
    description: "Whether Electron cache was restored"
    value: ${{ steps.cache-electron.outputs.cache-hit }}
  cache-ark-hit:
    description: "Whether ark binary cache was restored"
    value: ${{ steps.cache-binaries-ark.outputs.cache-hit }}
  cache-kallichore-hit:
    description: "Whether kallichore binary cache was restored"
    value: ${{ steps.cache-binaries-kallichore.outputs.cache-hit }}
  cache-builtins-hit:
    description: "Whether built-in extensions cache was restored"
    value: ${{ steps.cache-builtins.outputs.cache-hit }}
  cache-compiled-hit:
    description: "Whether compiled output cache was restored"
    value: ${{ steps.cache-compiled.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Configure local caches
      shell: bash
      run: |
        echo "NPM_CONFIG_CACHE=.npm-cache" >> "$GITHUB_ENV"
        echo "PIP_CACHE_DIR=.pip-cache" >> "$GITHUB_ENV"
        mkdir -p .npm-cache .pip-cache .versions

    - name: Cache npm tarball store
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: .npm-cache
        key: >
          npm-cache-${{ runner.os }}-${{
            hashFiles('package-lock.json', 'build/package-lock.json', 'extensions/**/package-lock.json', 'remote/**/package-lock.json')
          }}
        restore-keys: |
          npm-cache-${{ runner.os }}-
          npm-cache-${{ runner.os }}-

    - name: Cache ark binary
      id: cache-binaries-ark
      uses: actions/cache@v4
      with:
        # Cache both built/downloaded resources used by the extension and a repo-root dev build directory
        path: |
          extensions/positron-r/resources/ark
          ./ark
        # Use the extension package.json as the key source so updates to the declared binary version invalidates cache
        key: ark-bin-${{ runner.os }}-${{ hashFiles('extensions/positron-r/package.json') }}
        restore-keys: |
          ark-bin-${{ runner.os }}-

    - name: Cache kallichore binary
      id: cache-binaries-kallichore
      uses: actions/cache@v4
      with:
        path: |
          extensions/positron-supervisor/resources/kallichore
          ./kallichore
        key: kallichore-bin-${{ runner.os }}-${{ hashFiles('extensions/positron-supervisor/package.json') }}
        restore-keys: |
          kallichore-bin-${{ runner.os }}-

    - name: Cache Playwright browsers
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        # Include the e2e lockfile too in case test/e2e has its own playwright deps
        key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json', 'test/e2e/package-lock.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Cache Electron binary
      id: cache-electron
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
        # electron binaries are tied to package-lock and the electron version in package.json
        key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}
        restore-keys: |
          electron-${{ runner.os }}-

    - name: Cache built-in extensions
      id: cache-builtins
      uses: actions/cache@v4
      with:
        path: |
          .build/builtInExtensions
        # product.json contains the list and versions of built-in extensions
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}
        restore-keys: |
          builtins-${{ runner.os }}-

    - name: Cache compiled output
      id: cache-compiled
      uses: actions/cache@v4
      with:
        path: |
          out
          out-build
        # Cache based on source files and package.json (dependencies affect compilation)
        key: compiled-${{ runner.os }}-${{ hashFiles('src/**/*.ts', 'src/**/*.js', 'extensions/**/*.ts', 'package.json', 'tsconfig*.json') }}
        restore-keys: |
          compiled-${{ runner.os }}-

