name: "Cache: Package Stores & Binaries"
description: "Save and restore caches for multiple package managers and binaries."

outputs:
  cache-playwright-hit:
    description: "Whether Playwright cache was restored"
    value: ${{ steps.cache-playwright.outputs.cache-hit }}
  cache-compiled-hit:
    description: "Whether compiled output cache was restored"
    value: ${{ steps.cache-compiled.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Configure local caches
      shell: bash
      run: |
        echo "NPM_CONFIG_CACHE=.npm-cache" >> "$GITHUB_ENV"
        echo "PIP_CACHE_DIR=.pip-cache" >> "$GITHUB_ENV"
        mkdir -p .npm-cache .pip-cache .versions

    - name: Cache npm tarball store
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: .npm-cache
        key: >
          npm-cache-${{ runner.os }}-${{
            hashFiles('package-lock.json', 'build/package-lock.json', 'extensions/**/package-lock.json', 'remote/**/package-lock.json')
          }}
        restore-keys: |
          npm-cache-${{ runner.os }}-
          npm-cache-${{ runner.os }}-

    - name: Cache ark binary
      id: cache-binaries-ark
      uses: actions/cache@v4
      with:
        # Cache both built/downloaded resources used by the extension and a repo-root dev build directory
        path: |
          extensions/positron-r/resources/ark
          ./ark
        # Use the extension package.json as the key source so updates to the declared binary version invalidates cache
        key: ark-bin-${{ runner.os }}-${{ hashFiles('extensions/positron-r/package.json') }}
        restore-keys: |
          ark-bin-${{ runner.os }}-

    - name: Cache kallichore binary
      id: cache-binaries-kallichore
      uses: actions/cache@v4
      with:
        path: |
          extensions/positron-supervisor/resources/kallichore
          ./kallichore
        key: kallichore-bin-${{ runner.os }}-${{ hashFiles('extensions/positron-supervisor/package.json') }}
        restore-keys: |
          kallichore-bin-${{ runner.os }}-

    - name: Cache Playwright browsers
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        # Include the e2e lockfile too in case test/e2e has its own playwright deps
        key: playwright-v2-${{ runner.os }}-${{ hashFiles('package-lock.json', 'test/e2e/package-lock.json') }}
        restore-keys: |
          playwright-v2-${{ runner.os }}-

    - name: Cache Electron binary
      id: cache-electron
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
        # electron binaries are tied to package-lock and the electron version in package.json
        key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}
        restore-keys: |
          electron-${{ runner.os }}-

    - name: Cache built-in extensions
      id: cache-builtins
      uses: actions/cache@v4
      with:
        path: |
          .build/builtInExtensions
        # product.json contains the list and versions of built-in extensions
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}
        restore-keys: |
          builtins-${{ runner.os }}-

    - name: Cache compiled output
      id: cache-compiled
      uses: actions/cache@v4
      with:
        path: |
          out
          out-build
        # Use commit SHA for fast, deterministic cache keys. Restore-keys enable incremental compilation
        # by reusing the most recent build from the same branch, then main, then any previous build.
        # TypeScript's incremental compilation handles the delta efficiently.
        key: compiled-v3-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          compiled-v3-${{ runner.os }}-${{ github.head_ref || github.ref_name }}-
          compiled-v3-${{ runner.os }}-main-
          compiled-v3-${{ runner.os }}-

    - name: Log cache results
      if: always()
      shell: bash
      run: |
        echo "Cache results:"
        echo "  npm:         hit=${{ steps['cache-npm'].outputs['cache-hit'] || 'false' }} matched=${{ steps['cache-npm'].outputs['cache-matched-key'] || steps['cache-npm'].outputs['cache-primary-key'] || 'n/a' }}"
        echo "  ark:         hit=${{ steps['cache-binaries-ark'].outputs['cache-hit'] || 'false' }} matched=${{ steps['cache-binaries-ark'].outputs['cache-matched-key'] || steps['cache-binaries-ark'].outputs['cache-primary-key'] || 'n/a' }}"
        echo "  kallichore:  hit=${{ steps['cache-binaries-kallichore'].outputs['cache-hit'] || 'false' }} matched=${{ steps['cache-binaries-kallichore'].outputs['cache-matched-key'] || steps['cache-binaries-kallichore'].outputs['cache-primary-key'] || 'n/a' }}"
        echo "  playwright:  hit=${{ steps['cache-playwright'].outputs['cache-hit'] || 'false' }} matched=${{ steps['cache-playwright'].outputs['cache-matched-key'] || steps['cache-playwright'].outputs['cache-primary-key'] || 'n/a' }}"
        echo "  electron:    hit=${{ steps['cache-electron'].outputs['cache-hit'] || 'false' }} matched=${{ steps['cache-electron'].outputs['cache-matched-key'] || steps['cache-electron'].outputs['cache-primary-key'] || 'n/a' }}"
        echo "  builtins:    hit=${{ steps['cache-builtins'].outputs['cache-hit'] || 'false' }} matched=${{ steps['cache-builtins'].outputs['cache-matched-key'] || steps['cache-builtins'].outputs['cache-primary-key'] || 'n/a' }}"
        echo "  compiled:    hit=${{ steps['cache-compiled'].outputs['cache-hit'] || 'false' }} matched=${{ steps['cache-compiled'].outputs['cache-matched-key'] || steps['cache-compiled'].outputs['cache-primary-key'] || 'n/a' }}"
