name: "Cache: Package Stores & Binaries"
description: "Save and restore caches for multiple package managers and binaries."

outputs:
  cache-playwright-hit:
    description: "Whether Playwright cache was restored"
    value: ${{ steps.cache-playwright.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Configure local caches
      shell: bash
      run: |
        echo "NPM_CONFIG_CACHE=.npm-cache" >> "$GITHUB_ENV"
        echo "PIP_CACHE_DIR=.pip-cache" >> "$GITHUB_ENV"
        mkdir -p .npm-cache .pip-cache .versions

    - name: Cache npm packages
      id: cache-npm
      continue-on-error: true
      uses: actions/cache@v4
      with:
        path: .npm-cache
        key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-cache-${{ runner.os }}-

    # - name: Cache ark binary
    #   id: cache-binaries-ark
    #   continue-on-error: true
    #   uses: actions/cache@v4
    #   with:
    #     # Cache both built/downloaded resources used by the extension and a repo-root dev build directory
    #     path: |
    #       extensions/positron-r/resources/ark
    #       ./ark
    #     # Use the extension package.json as the key source so updates to the declared binary version invalidates cache
    #     key: ark-bin-${{ runner.os }}-${{ hashFiles('extensions/positron-r/package.json') }}
    #     restore-keys: |
    #       ark-bin-${{ runner.os }}-

    # - name: Cache kallichore binary
    #   id: cache-binaries-kallichore
    #   continue-on-error: true
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       extensions/positron-supervisor/resources/kallichore
    #       ./kallichore
    #     key: kallichore-bin-${{ runner.os }}-${{ hashFiles('extensions/positron-supervisor/package.json') }}
    #     restore-keys: |
    #       kallichore-bin-${{ runner.os }}-

    - name: Cache Playwright browsers
      id: cache-playwright
      continue-on-error: true
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
          /root/.cache/ms-playwright
          /github/home/.cache/ms-playwright
        # Include the e2e lockfile too in case test/e2e has its own playwright deps
        key: playwright-v3-${{ runner.os }}-${{ hashFiles('package-lock.json', 'test/e2e/package-lock.json') }}
        restore-keys: |
          playwright-v3-${{ runner.os }}-

    - name: Cache Electron binary
      id: cache-electron
      continue-on-error: true
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
          /root/.cache/electron
          /root/.cache/electron-builder
          /github/home/.cache/electron
          /github/home/.cache/electron-builder
        # electron binaries are tied to package-lock and the electron version in package.json
        key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}
        restore-keys: |
          electron-${{ runner.os }}-

    # - name: Cache built-in extensions
    #   id: cache-builtins
    #   continue-on-error: true
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       .build/builtInExtensions
    #     # product.json contains the list and versions of built-in extensions
    #     key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}
    #     restore-keys: |
    #       builtins-${{ runner.os }}-

    - name: Log cache results
      if: always()
      shell: bash
      run: |
        echo "Cache results:"
        echo "  npm:         hit=${{ steps['cache-npm'].outputs['cache-hit'] || 'false' }}"
        echo "  playwright:  hit=${{ steps['cache-playwright'].outputs['cache-hit'] || 'false' }}"
        echo "  electron:    hit=${{ steps['cache-electron'].outputs['cache-hit'] || 'false' }}"
