name: "Cache Multiple Directories"
description: "Restores/Saves cache for node_modules, build, extensions, and remote"
runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: root-node-modules-v7-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

    - name: Cache build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: ./build/node_modules
        key: build-node-modules-v7-${{ runner.os }}-${{ hashFiles('build/yarn.lock') }}

    - name: Cache extensions
      id: cache-extensions
      uses: actions/cache@v4
      with:
        path: ./extensions/node_modules
        key: extensions-v7-${{ runner.os }}-${{ hashFiles('extensions/yarn.lock') }}

    - name: Cache remote
      id: cache-remote
      uses: actions/cache@v4
      with:
        path: ./remote/node_modules
        key: remote-node-modules-v7-${{ runner.os }}-${{ hashFiles('remote/yarn.lock') }}
