name: "Restore Build Caches (Windows)"
description: "Restores caches for npm dependencies, Playwright browsers, Electron binaries, and built-in extensions on Windows."

inputs:
  distro:
    description: "Distribution identifier for cache key (default: windows). Not typically changed for Windows."
    required: false
    default: 'windows'
  restore-npm:
    description: "Whether to restore npm cache (default: true)"
    required: false
    default: 'true'
  restore-playwright:
    description: "Whether to restore Playwright cache (default: true)"
    required: false
    default: 'true'
  restore-builtins:
    description: "Whether to restore built-in extensions cache (default: true)"
    required: false
    default: 'true'
  restore-ark:
    description: "Whether to restore Ark binary cache (default: true)"
    required: false
    default: 'true'
  restore-kallichore:
    description: "Whether to restore Kallichore binary cache (default: true)"
    required: false
    default: 'true'

outputs:
  cache-playwright-hit:
    description: "Whether Playwright cache was restored and verified"
    value: ${{ steps.cache-playwright.outputs.cache-hit == 'true' && steps.verify-playwright.outcome != 'failure' && 'true' || 'false' }}
  verify-playwright-outcome:
    description: "Outcome of Playwright cache verification (success/failure/skipped)"
    value: ${{ steps.verify-playwright.outcome || 'skipped' }}
  cache-npm-core-hit:
    description: "Whether npm core dependencies cache was restored"
    value: ${{ steps.cache-npm-core.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-npm-extensions-hit:
    description: "Whether npm extensions cache was restored"
    value: ${{ steps.cache-npm-extensions.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-builtins-hit:
    description: "Whether built-in extensions cache was restored"
    value: ${{ steps.cache-builtins.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-ark-hit:
    description: "Whether Ark binary cache was restored"
    value: ${{ steps.cache-ark.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-kallichore-hit:
    description: "Whether Kallichore binary cache was restored"
    value: ${{ steps.cache-kallichore.outputs.cache-hit == 'true' && 'true' || 'false' }}
  extensions-hash:
    description: "Generated hash of all extension package-lock.json files"
    value: ${{ steps.extensions-hash.outputs.hash }}
  package-locks-hash:
    description: "Computed hash of all package-lock.json files (for DRY cache key generation)"
    value: ${{ steps.package-locks-hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: Validate distro input
      shell: bash
      run: |
        if [[ "${{ runner.os }}" != "Windows" ]]; then
          echo "Error: restore-build-caches-windows action is for Windows only. Use restore-build-caches for Linux." >&2
          exit 1
        fi

    - name: Configure npm cache location
      shell: pwsh
      run: |
        # Configure npm to use a specific cache directory for consistent caching
        # This must match the path in the cache restore/save steps: ~\AppData\Roaming\npm-cache
        # Use PowerShell to ensure proper Windows path handling
        $npmCachePath = "$env:USERPROFILE\AppData\Roaming\npm-cache"
        "npm_config_cache=$npmCachePath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Host "Configured npm cache: $npmCachePath"

    - name: Generate extensions cache key
      if: ${{ inputs.restore-npm == 'true' }}
      id: extensions-hash
      continue-on-error: true
      shell: bash
      # Generate a hash of all extension + .vscode package.json files
      run: .github/scripts/generate-extensions-hash.sh || echo "hash=fallback-$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Generate package-locks cache key
      if: ${{ inputs.restore-npm == 'true' }}
      id: package-locks-hash
      continue-on-error: true
      shell: bash
      run: .github/scripts/generate-package-locks-hash.sh "${{ hashFiles('package-lock.json', 'build/package-lock.json', 'remote/package-lock.json', 'remote/web/package-lock.json', 'remote/reh-web/package-lock.json', 'test/e2e/package-lock.json', 'test/integration/browser/package-lock.json', 'test/monaco/package-lock.json', 'test/mcp/package-lock.json') }}" || echo "hash=fallback-$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Restore npm core dependencies cache
      if: ${{ inputs.restore-npm == 'true' }}
      id: cache-npm-core
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          ~\AppData\Roaming\npm-cache
          node_modules
          build/node_modules
          remote/node_modules
          remote/web/node_modules
          remote/reh-web/node_modules
          test/integration/browser/node_modules
          test/monaco/node_modules
          test/mcp/node_modules
        # Core dependencies invalidate only when package-lock files change
        # Note: test/e2e/node_modules excluded - not in postinstall dirs.js, installed separately
        # IMPORTANT: If bumping npm-core-v4 -> npm-core-v5, also update save-build-caches-windows/action.yml
        key: npm-core-v4-${{ runner.os }}-${{ inputs.distro }}-${{ steps.package-locks-hash.outputs.hash }}

    - name: Restore npm extensions cache
      if: ${{ inputs.restore-npm == 'true' }}
      id: cache-npm-extensions
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          extensions/**/node_modules
          .vscode/**/node_modules
          extensions/positron-assistant/resources
          extensions/positron-python/python-env-tools
          extensions/positron-python/python_files
        # Extensions invalidate when extension package.json files or git submodules change
        # Cache includes node_modules AND postinstall artifacts (binaries, Python libs, vendored packages)
        # Does NOT cache compiled outputs (out/) - extensions are recompiled during the "Compile Positron" step
        # IMPORTANT: If bumping npm-extensions-v6 -> npm-extensions-v7, also update save-build-caches-windows/action.yml
        key: npm-extensions-v6-${{ runner.os }}-${{ inputs.distro }}-${{ steps.extensions-hash.outputs.hash }}

    - name: Extract Playwright version
      if: ${{ inputs.restore-playwright == 'true' }}
      id: playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)")
        echo "version=$PLAYWRIGHT_VERSION" >> "$GITHUB_OUTPUT"
        echo "Playwright version: $PLAYWRIGHT_VERSION"

    # TEMPORARILY DISABLED: Playwright cache disabled for debugging
    # - name: Restore Playwright browsers cache
    #   if: ${{ inputs.restore-playwright == 'true' }}
    #   id: cache-playwright
    #   continue-on-error: true
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: ~\AppData\Local\ms-playwright
    #     # Cache key tied directly to Playwright version for precision
    #     # IMPORTANT: If bumping playwright-v2 -> playwright-v3, also update save-build-caches-windows/action.yml
    #     key: playwright-v2-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}
    #     restore-keys: |
    #       playwright-v2-${{ runner.os }}-

    # - name: Verify Playwright cache
    #   if: ${{ inputs.restore-playwright == 'true' && steps.cache-playwright.outputs.cache-hit == 'true' }}
    #   id: verify-playwright
    #   continue-on-error: true
    #   shell: bash
    #   run: |
    #     echo "Verifying Playwright cache..."
    #     # Convert Windows path to Unix path for bash
    #     PLAYWRIGHT_DIR="$USERPROFILE/AppData/Local/ms-playwright"

    #     # Check 1: Playwright CLI works
    #     if ! npx playwright --version > /dev/null 2>&1; then
    #       echo "⚠️ Playwright binary not functional"
    #       echo "⚠️ Playwright Cache Verification Failed" >> $GITHUB_STEP_SUMMARY
    #       echo "Playwright CLI failed to run. Will reinstall." >> $GITHUB_STEP_SUMMARY
    #       exit 1
    #     fi

    #     # Check 2: At least one browser binary exists
    #     BROWSER_FOUND=false
    #     for browser_dir in "$PLAYWRIGHT_DIR"/*; do
    #       if [ -d "$browser_dir" ]; then
    #         BROWSER_FOUND=true
    #         break
    #       fi
    #     done

    #     if [ "$BROWSER_FOUND" = false ]; then
    #       echo "⚠️ No browser binaries found in cache"
    #       echo "⚠️ Playwright Cache Verification Failed" >> $GITHUB_STEP_SUMMARY
    #       echo "No browser directories found. Will reinstall." >> $GITHUB_STEP_SUMMARY
    #       exit 1
    #     fi

    #     echo "✅ Playwright cache verified (CLI functional, browsers present)"

    - name: Restore built-in extensions cache
      if: ${{ inputs.restore-builtins == 'true' }}
      id: cache-builtins
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          .build/builtInExtensions
        # product.json contains the list and versions of built-in extensions
        # IMPORTANT: If bumping builtins -> builtins-v2, also update save-build-caches-windows/action.yml
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}
        restore-keys: |
          builtins-${{ runner.os }}-

    - name: Restore Ark binary cache
      if: ${{ inputs.restore-ark == 'true' }}
      id: cache-ark
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          extensions/positron-r/resources/ark
        # Ark binary version is specified in positron-r package.json
        # IMPORTANT: If bumping ark -> ark-v2, also update save-build-caches-windows/action.yml
        key: ark-${{ runner.os }}-${{ inputs.distro }}-${{ hashFiles('extensions/positron-r/package.json') }}
        restore-keys: |
          ark-${{ runner.os }}-${{ inputs.distro }}-

    - name: Log Ark version (debugging)
      if: ${{ inputs.restore-ark == 'true' && steps.cache-ark.outputs.cache-hit == 'true' }}
      continue-on-error: true
      shell: bash
      run: |
        if [ -f "extensions/positron-r/resources/ark/ark.exe" ]; then
          echo "Ark binary found, checking version..."
          ARK_VERSION=$(extensions/positron-r/resources/ark/ark.exe --version 2>&1 || echo "version check failed")
          echo "Ark version: $ARK_VERSION"
        else
          echo "Ark binary not found at expected path"
        fi

    - name: Restore Kallichore binary cache
      if: ${{ inputs.restore-kallichore == 'true' }}
      id: cache-kallichore
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          extensions/positron-supervisor/resources/kallichore
        # Kallichore binary version is specified in positron-supervisor package.json
        # IMPORTANT: If bumping kallichore-v3 -> kallichore-v4, also update save-build-caches-windows/action.yml
        key: kallichore-v3-${{ runner.os }}-${{ inputs.distro }}-${{ hashFiles('extensions/positron-supervisor/package.json') }}
        restore-keys: |
          kallichore-v3-${{ runner.os }}-${{ inputs.distro }}-

    - name: Log cache results
      if: always()
      shell: bash
      run: |
        # Track cache status for summary
        ALL_HIT=true
        ANY_MISS=false

        # npm-core
        if [[ "${{ inputs.restore-npm }}" == "true" ]]; then
          if [[ "${{ steps['cache-npm-core'].outputs['cache-hit'] }}" == "true" ]]; then
            printf "%-16s %s\n" "npm-core" "✅ hit"
          else
            printf "%-16s %s\n" "npm-core" "❌ miss"
            ALL_HIT=false
            ANY_MISS=true
          fi
        else
          printf "%-16s %s\n" "npm-core" "⏭️  skipped (disabled)"
        fi

        # npm-extensions
        if [[ "${{ inputs.restore-npm }}" == "true" ]]; then
          if [[ "${{ steps['cache-npm-extensions'].outputs['cache-hit'] }}" == "true" ]]; then
            printf "%-16s %s\n" "npm-extensions" "✅ hit"
          else
            printf "%-16s %s\n" "npm-extensions" "❌ miss"
            ALL_HIT=false
            ANY_MISS=true
          fi
        else
          printf "%-16s %s\n" "npm-extensions" "⏭️  skipped (disabled)"
        fi

        # playwright (TEMPORARILY DISABLED)
        printf "%-16s %s\n" "playwright" "🚫 disabled (debugging)"
        ALL_HIT=false
        ANY_MISS=true
        # if [[ "${{ inputs.restore-playwright }}" == "true" ]]; then
        #   HIT="${{ steps['cache-playwright'].outputs['cache-hit'] || 'false' }}"
        #   VERIFY="${{ steps['verify-playwright'].outcome || 'skipped' }}"
        #   if [[ "$HIT" == "true" && "$VERIFY" == "failure" ]]; then
        #     printf "%-16s %s\n" "playwright" "⚠️  hit (verification failed, will reinstall)"
        #     echo "::warning::Playwright cache verification failed - will reinstall browsers"
        #     ALL_HIT=false
        #   elif [[ "$HIT" == "true" ]]; then
        #     printf "%-16s %s\n" "playwright" "✅ hit"
        #   else
        #     printf "%-16s %s\n" "playwright" "❌ miss"
        #     ALL_HIT=false
        #     ANY_MISS=true
        #   fi
        # else
        #   printf "%-16s %s\n" "playwright" "⏭️  skipped (disabled)"
        # fi

        # builtins
        if [[ "${{ inputs.restore-builtins }}" == "true" ]]; then
          if [[ "${{ steps['cache-builtins'].outputs['cache-hit'] }}" == "true" ]]; then
            printf "%-16s %s\n" "builtins" "✅ hit"
          else
            printf "%-16s %s\n" "builtins" "❌ miss"
            ALL_HIT=false
            ANY_MISS=true
          fi
        else
          printf "%-16s %s\n" "builtins" "⏭️  skipped (disabled)"
        fi

        # ark
        if [[ "${{ inputs.restore-ark }}" == "true" ]]; then
          if [[ "${{ steps['cache-ark'].outputs['cache-hit'] }}" == "true" ]]; then
            printf "%-16s %s\n" "ark" "✅ hit"
          else
            printf "%-16s %s\n" "ark" "❌ miss"
            ALL_HIT=false
            ANY_MISS=true
          fi
        else
          printf "%-16s %s\n" "ark" "⏭️  skipped (disabled)"
        fi

        # kallichore
        if [[ "${{ inputs.restore-kallichore }}" == "true" ]]; then
          if [[ "${{ steps['cache-kallichore'].outputs['cache-hit'] }}" == "true" ]]; then
            printf "%-16s %s\n" "kallichore" "✅ hit"
          else
            printf "%-16s %s\n" "kallichore" "❌ miss"
            ALL_HIT=false
            ANY_MISS=true
          fi
        else
          printf "%-16s %s\n" "kallichore" "⏭️  skipped (disabled)"
        fi
