name: "Restore Build Caches (Windows)"
description: "Restores caches for npm dependencies, Playwright browsers, Electron binaries, and built-in extensions on Windows."

inputs:
  distro:
    description: "Distribution identifier for cache key (default: windows). Not typically changed for Windows."
    required: false
    default: 'windows'
  restore-npm:
    description: "Whether to restore npm cache (default: true)"
    required: false
    default: 'true'
  restore-playwright:
    description: "Whether to restore Playwright cache (default: true)"
    required: false
    default: 'true'
  restore-electron:
    description: "Whether to restore Electron cache (default: true)"
    required: false
    default: 'true'
  restore-builtins:
    description: "Whether to restore built-in extensions cache (default: true)"
    required: false
    default: 'true'

outputs:
  cache-playwright-hit:
    description: "Whether Playwright cache was restored"
    value: ${{ steps.cache-playwright.outputs.cache-hit == 'true' && 'true' || 'false' }}
  verify-playwright-outcome:
    description: "Outcome of Playwright cache verification (success/failure/skipped)"
    value: ${{ steps.verify-playwright.outcome || 'skipped' }}
  cache-npm-core-hit:
    description: "Whether npm core dependencies cache was restored"
    value: ${{ steps.cache-npm-core.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-npm-extensions-hit:
    description: "Whether npm extensions cache was restored"
    value: ${{ steps.cache-npm-extensions.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-electron-hit:
    description: "Whether Electron cache was restored"
    value: ${{ steps.cache-electron.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-builtins-hit:
    description: "Whether built-in extensions cache was restored"
    value: ${{ steps.cache-builtins.outputs.cache-hit == 'true' && 'true' || 'false' }}
  extensions-hash:
    description: "Generated hash of all extension package-lock.json files"
    value: ${{ steps.extensions-hash.outputs.hash }}
  package-locks-hash:
    description: "Computed hash of all package-lock.json files (for DRY cache key generation)"
    value: ${{ steps.package-locks-hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: Validate distro input
      shell: bash
      run: |
        if [[ "${{ runner.os }}" != "Windows" ]]; then
          echo "Error: restore-build-caches-windows action is for Windows only. Use restore-build-caches for Linux." >&2
          exit 1
        fi

    - name: Configure npm cache location
      shell: pwsh
      run: |
        # Configure npm to use a specific cache directory for consistent caching
        # This must match the path in the cache restore/save steps: ~\AppData\Roaming\npm-cache
        # Use PowerShell to ensure proper Windows path handling
        $npmCachePath = "$env:USERPROFILE\AppData\Roaming\npm-cache"
        "npm_config_cache=$npmCachePath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Host "Configured npm cache: $npmCachePath"

    - name: Generate extensions cache key
      if: ${{ inputs.restore-npm == 'true' }}
      id: extensions-hash
      continue-on-error: true
      shell: bash
      # Generate a hash of all extension + .vscode package.json files
      run: .github/scripts/generate-extensions-hash.sh || echo "hash=fallback-$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Generate package-locks cache key
      if: ${{ inputs.restore-npm == 'true' }}
      id: package-locks-hash
      continue-on-error: true
      shell: bash
      run: .github/scripts/generate-package-locks-hash.sh "${{ hashFiles('package-lock.json', 'build/package-lock.json', 'remote/package-lock.json', 'remote/web/package-lock.json', 'remote/reh-web/package-lock.json', 'test/e2e/package-lock.json', 'test/integration/browser/package-lock.json', 'test/monaco/package-lock.json', 'test/mcp/package-lock.json') }}" || echo "hash=fallback-$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Restore npm core dependencies cache
      if: ${{ inputs.restore-npm == 'true' }}
      id: cache-npm-core
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          ~\AppData\Roaming\npm-cache
          node_modules
          build/node_modules
          remote/node_modules
          remote/web/node_modules
          remote/reh-web/node_modules
          test/integration/browser/node_modules
          test/monaco/node_modules
          test/mcp/node_modules
        # Core dependencies invalidate only when package-lock files change
        # Note: test/e2e/node_modules excluded - not in postinstall dirs.js, installed separately
        # IMPORTANT: If bumping npm-core-v4 -> npm-core-v5, also update save-build-caches-windows/action.yml
        key: npm-core-v4-${{ runner.os }}-${{ inputs.distro }}-${{ steps.package-locks-hash.outputs.hash }}

    - name: Restore npm extensions cache
      if: ${{ inputs.restore-npm == 'true' }}
      id: cache-npm-extensions
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          extensions/**/node_modules
          .vscode/**/node_modules
        # Extensions invalidate when extension package.json files or git submodules change
        # Only cache node_modules, not compiled outputs (out/) or downloaded binaries (resources/)
        # Extensions are recompiled during the "Compile Positron" step
        # IMPORTANT: If bumping npm-extensions-v4 -> npm-extensions-v5, also update save-build-caches-windows/action.yml
        key: npm-extensions-v4-${{ runner.os }}-${{ inputs.distro }}-${{ steps.extensions-hash.outputs.hash }}

    - name: Extract Playwright version
      if: ${{ inputs.restore-playwright == 'true' }}
      id: playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)")
        echo "version=$PLAYWRIGHT_VERSION" >> "$GITHUB_OUTPUT"
        echo "Playwright version: $PLAYWRIGHT_VERSION"

    - name: Restore Playwright browsers cache
      if: ${{ inputs.restore-playwright == 'true' }}
      id: cache-playwright
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: ~\AppData\Local\ms-playwright
        # Cache key tied directly to Playwright version for precision
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Verify Playwright cache
      if: ${{ inputs.restore-playwright == 'true' && steps.cache-playwright.outputs.cache-hit == 'true' }}
      id: verify-playwright
      continue-on-error: true
      shell: bash
      run: |
        echo "Verifying Playwright cache..."
        # Convert Windows path to Unix path for bash
        PLAYWRIGHT_DIR="$USERPROFILE/AppData/Local/ms-playwright"
        if [ ! -d "$PLAYWRIGHT_DIR" ]; then
          echo "⚠️ Playwright cache directory missing"
          echo "### ⚠️ Playwright Cache Verification Failed" >> $GITHUB_STEP_SUMMARY
          echo "Cache was restored but directory is missing. Will reinstall." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        if [ -z "$(ls -A "$PLAYWRIGHT_DIR")" ]; then
          echo "⚠️ Playwright cache directory empty"
          echo "### ⚠️ Playwright Cache Verification Failed" >> $GITHUB_STEP_SUMMARY
          echo "Cache directory exists but is empty. Will reinstall." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        echo "✅ Playwright cache verified"

    # - name: Restore Electron binary cache
    #   if: ${{ inputs.restore-electron == 'true' }}
    #   id: cache-electron
    #   continue-on-error: true
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: |
    #       ~\AppData\Local\electron\Cache
    #       ~\AppData\Local\electron-builder\Cache
    #     # electron binaries are tied to package-lock and the electron version in package.json
    #     # IMPORTANT: If bumping electron -> electron-v2, also update save-build-caches-windows/action.yml
    #     key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}
    #     restore-keys: |
    #       electron-${{ runner.os }}-

    - name: Restore built-in extensions cache
      if: ${{ inputs.restore-builtins == 'true' }}
      id: cache-builtins
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          .build/builtInExtensions
        # product.json contains the list and versions of built-in extensions
        # IMPORTANT: If bumping builtins -> builtins-v2, also update save-build-caches-windows/action.yml
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}
        restore-keys: |
          builtins-${{ runner.os }}-

    - name: Log cache results
      if: always()
      shell: bash
      run: |
        echo "Cache results:"

        # npm-core
        if [[ "${{ inputs.restore-npm }}" == "true" ]]; then
          echo "  npm-core:       hit=${{ steps['cache-npm-core'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  npm-core:       skipped (disabled)"
        fi

        # npm-extensions
        if [[ "${{ inputs.restore-npm }}" == "true" ]]; then
          echo "  npm-extensions: hit=${{ steps['cache-npm-extensions'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  npm-extensions: skipped (disabled)"
        fi

        # playwright
        if [[ "${{ inputs.restore-playwright }}" == "true" ]]; then
          HIT="${{ steps['cache-playwright'].outputs['cache-hit'] || 'false' }}"
          VERIFY="${{ steps['verify-playwright'].outcome || 'skipped' }}"
          if [[ "$HIT" == "true" && "$VERIFY" == "failure" ]]; then
            echo "  playwright:     hit=true (⚠️ verification failed, will reinstall)"
          else
            echo "  playwright:     hit=$HIT"
          fi
        else
          echo "  playwright:     skipped (disabled)"
        fi

        # electron (disabled - downloaded during compile)
        echo "  electron:       skipped (disabled)"

        # builtins
        if [[ "${{ inputs.restore-builtins }}" == "true" ]]; then
          echo "  builtins:       hit=${{ steps['cache-builtins'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  builtins:       skipped (disabled)"
        fi
