name: "Restore Build Caches (Windows)"
description: "Restores caches for npm dependencies, Playwright browsers, Electron binaries, and built-in extensions on Windows."

inputs:
  restore-npm:
    description: "Whether to restore npm cache (default: true)"
    required: false
    default: 'true'
  restore-playwright:
    description: "Whether to restore Playwright cache (default: true)"
    required: false
    default: 'true'
  restore-electron:
    description: "Whether to restore Electron cache (default: true)"
    required: false
    default: 'true'
  restore-builtins:
    description: "Whether to restore built-in extensions cache (default: true)"
    required: false
    default: 'true'

outputs:
  cache-playwright-hit:
    description: "Whether Playwright cache was restored"
    value: ${{ steps.cache-playwright.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-npm-hit:
    description: "Whether npm cache was restored"
    value: ${{ steps.cache-npm.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-electron-hit:
    description: "Whether Electron cache was restored"
    value: ${{ steps.cache-electron.outputs.cache-hit == 'true' && 'true' || 'false' }}
  cache-builtins-hit:
    description: "Whether built-in extensions cache was restored"
    value: ${{ steps.cache-builtins.outputs.cache-hit == 'true' && 'true' || 'false' }}
  extensions-hash:
    description: "Generated hash of all extension package-lock.json files"
    value: ${{ steps.extensions-hash.outputs.hash }}
  package-locks-hash:
    description: "Computed hash of all package-lock.json files (for DRY cache key generation)"
    value: ${{ steps.package-locks-hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: Generate extensions cache key
      if: ${{ inputs.restore-npm == 'true' }}
      id: extensions-hash
      shell: bash
      # Generate a hash of all extension + .vscode package.json files
      run: .github/scripts/generate-extensions-hash.sh

    - name: Generate package-locks cache key
      if: ${{ inputs.restore-npm == 'true' }}
      id: package-locks-hash
      shell: bash
      run: .github/scripts/generate-package-locks-hash.sh "${{ hashFiles('package-lock.json', 'build/package-lock.json', 'remote/package-lock.json', 'remote/web/package-lock.json', 'remote/reh-web/package-lock.json', 'test/e2e/package-lock.json', 'test/integration/browser/package-lock.json', 'test/monaco/package-lock.json', 'test/mcp/package-lock.json') }}"

    - name: Restore npm dependencies cache
      if: ${{ inputs.restore-npm == 'true' }}
      id: cache-npm
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          ~\AppData\Roaming\npm-cache
          node_modules
          build/node_modules
          extensions
          .vscode
          remote/node_modules
          test/e2e/node_modules
        # Hash main package-lock files + programmatically generated extensions hash
        # No restore-keys to avoid partial matches that could restore wrong extension versions
        # Package-locks hash is calculated once in the "Generate package-locks cache key" step above (DRY)
        # IMPORTANT: If bumping npm-v3 -> npm-v4, also update save-build-caches-windows/action.yml
        key: npm-v3-${{ runner.os }}-${{ steps.package-locks-hash.outputs.hash }}-${{ steps.extensions-hash.outputs.hash }}

    - name: Restore Playwright browsers cache
      if: ${{ inputs.restore-playwright == 'true' }}
      id: cache-playwright
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          ~\AppData\Local\ms-playwright
        # Include the e2e lockfile too in case test/e2e has its own playwright deps
        # IMPORTANT: If bumping playwright-v3 -> playwright-v4, also update save-build-caches-windows/action.yml
        key: playwright-v3-${{ runner.os }}-${{ hashFiles('package-lock.json', 'test/e2e/package-lock.json') }}

    - name: Restore Electron binary cache
      if: ${{ inputs.restore-electron == 'true' }}
      id: cache-electron
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          ~\AppData\Local\electron\Cache
          ~\AppData\Local\electron-builder\Cache
        # electron binaries are tied to package-lock and the electron version in package.json
        # IMPORTANT: If bumping electron -> electron-v2, also update save-build-caches-windows/action.yml
        key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}

    - name: Restore built-in extensions cache
      if: ${{ inputs.restore-builtins == 'true' }}
      id: cache-builtins
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: |
          .build/builtInExtensions
        # product.json contains the list and versions of built-in extensions
        # IMPORTANT: If bumping builtins -> builtins-v2, also update save-build-caches-windows/action.yml
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}

    - name: Log cache results
      if: always()
      shell: bash
      run: |
        echo "Cache results:"

        # npm
        if [[ "${{ inputs.restore-npm }}" == "true" ]]; then
          echo "  npm:         hit=${{ steps['cache-npm'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  npm:         skipped (disabled)"
        fi

        # playwright
        if [[ "${{ inputs.restore-playwright }}" == "true" ]]; then
          echo "  playwright:  hit=${{ steps['cache-playwright'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  playwright:  skipped (disabled)"
        fi

        # electron
        if [[ "${{ inputs.restore-electron }}" == "true" ]]; then
          echo "  electron:    hit=${{ steps['cache-electron'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  electron:    skipped (disabled)"
        fi

        # builtins
        if [[ "${{ inputs.restore-builtins }}" == "true" ]]; then
          echo "  builtins:    hit=${{ steps['cache-builtins'].outputs['cache-hit'] || 'false' }}"
        else
          echo "  builtins:    skipped (disabled)"
        fi
