name: "Setup Rig, R, and R Packages"
description: "Install a specified R version using Rig, with an option to install additional R packages."
inputs:
  version:
    description: "The R version to install (e.g., 4.4.0)"
    required: false
    default: "4.4.0"
  alternate_version:
    description: "The alternate R version to install (e.g., 4.4.2)"
    required: false
    default: "4.4.2"
  install_undetectable_interpreters:
    description: "Install undetectable interpreters"
    required: true
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Install Rig and R
      shell: bash
      run: |
        R_VERSION="${{ inputs.version }}"
        echo "Installing R version $R_VERSION using Rig..."
        curl -Ls https://github.com/r-lib/rig/releases/download/latest/rig-linux-"$(arch)"-latest.tar.gz | sudo tar xz -C /usr/local
        rig add "$R_VERSION"

    - name: Configure Posit PPM for Ubuntu 24.04 with Custom HTTP User-Agent
      shell: bash
      run: |
        echo "Configuring R to use Posit Package Manager for Ubuntu 24.04..."
        cat <<EOF > ~/.Rprofile
        options(
          repos = c(RSPM = "https://packagemanager.posit.co/cran/__linux__/noble/latest"),
          HTTPUserAgent = sprintf(
            "R/%s (%s) R (%s)",
            getRversion(), "ubuntu-2404",
            paste(getRversion(), R.version\$platform, R.version\$arch, R.version\$os)
          )
        )
        EOF

    - name: Check R Installation
      shell: bash
      run: |
        R --version

    - name: Install R Packages
      shell: bash
      run: |
        echo "Installing R development packages..."
        curl -s https://raw.githubusercontent.com/posit-dev/qa-example-content/main/DESCRIPTION --output DESCRIPTION
        Rscript -e "if (!requireNamespace('pak', quietly = TRUE)) install.packages('pak', repos = 'https://cran.rstudio.com')"
        Rscript -e "options(pak.install_binary = TRUE); pak::local_install_dev_deps(ask = FALSE)"

    - name: Install alternate R version
      shell: bash
      run: |
        R_ALTERNATE_VERSION="${{ inputs.alternate_version }}"
        echo "Installing R version $R_ALTERNATE_VERSION using Rig..."
        rig add "$R_ALTERNATE_VERSION"

    - name: Install Prebuilt R in ~/scratch (Using Tarball)
      if: ${{ inputs.install_undetectable_interpreters == 'true' }}
      shell: bash
      run: |
        echo "Installing R in ~/scratch..."

        # Set installation path
        BASE_DIR="$HOME/scratch"
        INSTALL_DIR="$BASE_DIR/R-4.4.1"
        mkdir -p $INSTALL_DIR

        # Define R version and OS identifier
        R_VERSION="4.4.1"
        OS_IDENTIFIER="ubuntu-2404"

        # Construct the tarball URL
        TAR_URL="https://cdn.posit.co/r/${OS_IDENTIFIER}/R-${R_VERSION}-${OS_IDENTIFIER}.tar.gz"
        echo "Downloading R from $TAR_URL"

        # Download the tarball
        curl -fLO "$TAR_URL"

        # Extract the tarball into ~/scratch/R-4.4.1
        tar -xzf R-${R_VERSION}-${OS_IDENTIFIER}.tar.gz -C $INSTALL_DIR --strip-components=1

        # Debug: Check the extracted contents
        echo "Extracted directory structure:"
        ls -R $INSTALL_DIR

        # Force R to use the correct installation path
        export R_HOME="$INSTALL_DIR/lib/R"
        export PATH="$INSTALL_DIR/bin:$PATH"

        # Patch the R script to override hardcoded paths
        sed -i "s|/opt/R/4.4.1|$INSTALL_DIR|g" "$INSTALL_DIR/bin/R"
        sed -i "s|/opt/R/4.4.1|$INSTALL_DIR|g" "$INSTALL_DIR/lib/R/etc/Renviron"

        # Ensure R is executable
        chmod +x $INSTALL_DIR/bin/R

        # Verify R installation
        if [[ -x "$INSTALL_DIR/bin/R" ]]; then
            echo "R successfully extracted."
            R --version
        else
            echo "Error: R binary not found in extracted directory."
            exit 1
        fi

        echo "Custom R installed at $INSTALL_DIR"


