name: "Setup Rig, R, and R Packages"
description: "Install a specified R version using rig, with an option to install additional R packages."
inputs:
  version:
    description: "The R version to install (e.g., 4.4.0)"
    required: false
    default: "4.4.0"
runs:
  using: "composite"
  steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "${{ inputs.version }}"

    - name: Configure Posit PPM for Ubuntu 22.04 with Custom HTTP User-Agent
      shell: bash
      run: |
        echo "Configuring R to use Posit Package Manager for Jammy..."
        cat <<EOF > ~/.Rprofile
        options(
          repos = c(RSPM = "https://packagemanager.posit.co/cran/__linux__/ubuntu-2404/latest"),
          HTTPUserAgent = sprintf(
            "R/%s (%s) R (%s)",
            getRversion(), "ubuntu-2404",
            paste(getRversion(), R.version\$platform, R.version\$arch, R.version\$os)
          )
        )
        EOF

    - name: Check R Installation
      shell: bash
      run: |
        R --version

    - name: Install R Packages
      shell: bash
      run: |
        echo "Installing R development packages..."
        curl -s https://raw.githubusercontent.com/posit-dev/qa-example-content/main/DESCRIPTION --output DESCRIPTION
        Rscript -e "if (!requireNamespace('pak', quietly = TRUE)) install.packages('pak', repos = 'https://cran.rstudio.com')"
        Rscript -e "options(pak.install_binary = TRUE); pak::local_install_dev_deps(ask = FALSE)"
