name: "Setup E2E Test Environment"
description: "Install necessary dependencies for E2E testing"
inputs:
  aws-role-to-assume:
    description: "The AWS role to assume for S3 access"
    required: true
  aws-region:
    description: "The AWS region for S3"
    required: true

runs:
  using: "composite"
  steps:
    - name: Compile E2E Tests
      shell: bash
      run: npm --prefix test/e2e run compile

    - name: Setup AWS S3 Access
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Xvfb
      shell: bash
      run: |
        # Start Xvfb in the background
        /usr/bin/Xvfb :10 -ac -screen 0 2560x1440x24 > /tmp/Xvfb.out 2>&1 &

        # Wait until Xvfb is ready
        export DISPLAY=:10
        for i in {1..10}; do
          if xdpyinfo > /dev/null 2>&1; then
            echo "Xvfb is ready"
            break
          fi
          echo "Waiting for Xvfb to start..."
          sleep 1
        done

        # Export the DISPLAY variable for subsequent steps
        echo "DISPLAY=:10" >> $GITHUB_ENV
