name: "Setup E2E Test Environment"
description: "Install necessary dependencies for E2E testing"
inputs:
  aws-role-to-assume:
    description: "The AWS role to assume for S3 access"
    required: true
  aws-region:
    description: "The AWS region for S3"
    required: true
  github-token:
    description: "GitHub Token for accessing private repositories or APIs"
    required: true

runs:
  using: "composite"
  steps:
    # --- Needed by E2E Tests ---
    # AWS S3 Access, Graphviz, Quarto, Conda, Python + Python Deps, R + R Deps

    # --- Needed by Integration Tests ---
    # R + R Deps

    - name: Setup AWS S3 Access
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2.0.2

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      with:
        tinytex: true

    - name: Install Conda (Miniforge3)
      shell: bash
      run: |
        wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
        sudo bash Miniforge3.sh -b -p "${HOME}/conda"
        echo "source \"${HOME}/conda/etc/profile.d/conda.sh\"" >> ~/.bashrc
        source "${HOME}/conda/etc/profile.d/conda.sh"

    # - name: Install Python
    #   uses: ./.github/actions/setup-python-xvfb
    #   with:
    #     version: "3.10"

    # - name: Install Python dependencies
    #   shell: bash
    #   run: |
    #     python -m pip install --upgrade pip
    #     python -m pip install -r requirements.txt
    #     python -m pip install ipykernel trcli

    # # Install R and R pkgs with cache
    # - name: Install rig, R
    #   shell: bash
    #   env:
    #     R_VERSION: "4.4.0"
    #   run: |
    #     curl -Ls https://github.com/r-lib/rig/releases/download/latest/rig-linux-"$(arch)"-latest.tar.gz | $(which sudo) tar xz -C /usr/local
    #     rig add "$R_VERSION"

    # - name: Install R packages
    #   shell: bash
    #   run: |
    #     curl https://raw.githubusercontent.com/posit-dev/qa-example-content/main/DESCRIPTION --output DESCRIPTION
    #     Rscript -e "pak::local_install_dev_deps(ask = FALSE)"

    # Use the custom composite action to install R with or without packages

    - name: Setup Python
      uses: ./.github/actions/install-python
      with:
        version: "3.10"

    - name: Setup R
      uses: ./.github/actions/install-r
      with:
        r-version: "4.4.0"
        install-pkgs: "true"
