name: "Setup E2E Test Environment"
description: "Install necessary dependencies for E2E testing"
inputs:
  aws-role-to-assume:
    description: "The AWS role to assume for S3 access"
    required: true
  aws-region:
    description: "The AWS region for S3"
    required: true

runs:
  using: "composite"
  steps:
    - name: Ensure compiled E2E tests exist (install+compile if missing)
      shell: bash
      run: |
        # If compiled outputs are present (either in repo or extracted artifact), skip compile.
        if [ -d "./test/e2e/out" ] || [ -d "/__w/positron/test/e2e/out" ]; then
          echo "Found compiled E2E outputs; skipping install+compile"
          exit 0
        fi

        echo "No compiled E2E outputs found; installing dependencies and compiling"
        if [ -f test/e2e/package-lock.json ]; then
          npm ci --prefix test/e2e --prefer-offline --no-audit --no-fund
        else
          npm install --prefix test/e2e --no-audit --no-fund
        fi

        # Try compiling; if tsc cannot be found because typescript is a repo-root dep,
        # attempt to install root dev deps and retry once.
        if npm --prefix test/e2e run compile; then
          echo "E2E compile succeeded"
        else
          echo "Initial compile failed; attempting to install repo-root dev deps and retry"
          # Install dev deps at repo root (best-effort). This is a fallback for
          # projects which expect typescript at ../../node_modules/typescript.
          if [ -f package-lock.json ]; then
            npm ci --prefer-offline --no-audit --no-fund || true
          else
            npm install --no-audit --no-fund || true
          fi
          npm --prefix test/e2e run compile || true
        fi

    - name: Setup AWS S3 Access
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Xvfb
      uses: ./.github/actions/setup-xvfb
