name: "Setup E2E Test Environment"
description: "Install necessary dependencies for E2E testing"
inputs:
  aws-role-to-assume:
    description: "The AWS role to assume for S3 access"
    required: true
  aws-region:
    description: "The AWS region for S3"
    required: true
  github-token:
    description: "GitHub Token for accessing private repositories or APIs"
    required: true
  install_undetectable_interpreters:
    description: "Install undetectable interpreters"
    required: true
runs:
  using: "composite"
  steps:
    - name: Compile E2E Tests
      shell: bash
      run: npm --prefix test/e2e run compile

    - name: Setup AWS S3 Access
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2.0.2

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      with:
        tinytex: true

    # Miniforge avoids Anaconda ToS and defaults to conda-forge
    - name: Setup Conda (Miniforge3)
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        auto-activate-base: false
        channels: conda-forge,defaults  # Defaults included only to suppress warnings; all packages are still resolved from conda-forge
        conda-remove-defaults: "true"
        channel-priority: strict

    - name: Setup Python
      uses: ./.github/actions/install-python
      with:
        alternate_version: "3.13.0"
        install_undetectable_interpreters: ${{ inputs.install_undetectable_interpreters }}

    - name: Setup R
      uses: ./.github/actions/install-r
      with:
        version: "4.4.0"
        alternate_version: "4.4.2"
        install_undetectable_interpreters: ${{ inputs.install_undetectable_interpreters }}
