name: "Save Build Caches"
description: "Saves caches for npm dependencies, Playwright browsers, Electron binaries, and built-in extensions. Only saves caches that were restored but missed (cache-*-hit == 'false')."

inputs:
  distro:
    description: "Linux distribution identifier for cache key (default: ubuntu). Use 'rhel' for RHEL/Rocky Linux."
    required: false
    default: 'ubuntu'
  cache-npm-core-hit:
    description: "Whether npm core cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-npm-extensions-hit:
    description: "Whether npm extensions cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-playwright-hit:
    description: "Whether Playwright cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-electron-hit:
    description: "Whether Electron cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-builtins-hit:
    description: "Whether builtins cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-ark-hit:
    description: "Whether Ark binary cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-kallichore-hit:
    description: "Whether Kallichore binary cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  extensions-hash:
    description: "Extensions hash from restore step (required only if saving npm extensions cache)"
    required: false
    default: ''
  package-locks-hash:
    description: "Package-locks hash from restore step (required only if saving npm core cache)"
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Validate distro input
      shell: bash
      run: |
        if [[ "${{ runner.os }}" != "Linux" ]]; then
          echo "Error: save-build-caches action is for Linux only. Use save-build-caches-windows for Windows." >&2
          exit 1
        fi

    - name: Save npm core dependencies cache
      if: ${{ inputs.cache-npm-core-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          .npm-cache
          node_modules
          build/node_modules
          remote/node_modules
          remote/web/node_modules
          remote/reh-web/node_modules
          test/integration/browser/node_modules
          test/monaco/node_modules
          test/mcp/node_modules
        # Package-locks hash comes from restore step (DRY - single source of truth)
        # Note: test/e2e/node_modules excluded - not in postinstall dirs.js, installed separately
        # IMPORTANT: If bumping npm-core-v4 -> npm-core-v5, also update restore-build-caches/action.yml
        key: npm-core-v4-${{ runner.os }}-${{ inputs.distro }}-${{ inputs.package-locks-hash }}

    - name: Save npm extensions cache
      if: ${{ inputs.cache-npm-extensions-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          extensions/**/node_modules
          .vscode/**/node_modules
          extensions/positron-assistant/resources
          extensions/positron-python/python-env-tools
          extensions/positron-python/python_files
        # Extensions hash comes from restore step (DRY - single source of truth)
        # Cache includes node_modules AND postinstall artifacts (binaries, Python libs, vendored packages)
        # Does NOT cache compiled outputs (out/) - extensions are recompiled during the "Compile Positron" step
        # IMPORTANT: If bumping npm-extensions-v6 -> npm-extensions-v7, also update restore-build-caches/action.yml
        key: npm-extensions-v6-${{ runner.os }}-${{ inputs.distro }}-${{ inputs.extensions-hash }}

    # - name: Extract Playwright version
    #   if: ${{ inputs.cache-playwright-hit == 'false' }}
    #   id: playwright-version
    #   shell: bash
    #   run: |
    #     PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)")
    #     echo "version=$PLAYWRIGHT_VERSION" >> "$GITHUB_OUTPUT"
    #     echo "Playwright version: $PLAYWRIGHT_VERSION"

    # - name: Save Playwright browsers cache
    #   if: ${{ inputs.cache-playwright-hit == 'false' }}
    #   continue-on-error: true
    #   uses: actions/cache/save@v4
    #   with:
    #     path: ~/.cache/ms-playwright
    #     # Cache key tied directly to Playwright version and distro (Ubuntu vs RHEL have different deps)
    #     key: ${{ runner.os }}-${{ inputs.distro }}-playwright-${{ steps.playwright-version.outputs.version }}

    # - name: Save Electron binary cache
    #   if: ${{ inputs.cache-electron-hit == 'false' }}
    #   continue-on-error: true
    #   uses: actions/cache/save@v4
    #   with:
    #     path: |
    #       ~/.cache/electron
    #       ~/.cache/electron-builder
    #       /root/.cache/electron
    #       /root/.cache/electron-builder
    #       /github/home/.cache/electron
    #       /github/home/.cache/electron-builder
    #     # IMPORTANT: If bumping electron -> electron-v2, also update restore-build-caches/action.yml
    #     key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}

    - name: Save built-in extensions cache
      if: ${{ inputs.cache-builtins-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          .build/builtInExtensions
        # IMPORTANT: If bumping builtins -> builtins-v2, also update restore-build-caches/action.yml
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}

    - name: Verify Ark binary before saving
      if: ${{ inputs.cache-ark-hit == 'false' }}
      id: verify-ark
      continue-on-error: true
      shell: bash
      run: |
        if [ -f "extensions/positron-r/resources/ark/ark" ] && extensions/positron-r/resources/ark/ark --version 2>/dev/null; then
          echo "✅ Ark binary verified and functional"
          echo "verified=true" >> $GITHUB_OUTPUT
        else
          echo "⚠️ Ark binary missing or not functional - skipping cache save"
          echo "verified=false" >> $GITHUB_OUTPUT
        fi

    - name: Save Ark binary cache
      if: ${{ inputs.cache-ark-hit == 'false' && steps.verify-ark.outputs.verified == 'true' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          extensions/positron-r/resources/ark
        # IMPORTANT: If bumping ark -> ark-v2, also update restore-build-caches/action.yml
        key: ark-${{ runner.os }}-${{ inputs.distro }}-${{ hashFiles('extensions/positron-r/package.json') }}

    - name: Verify Kallichore binary before saving
      if: ${{ inputs.cache-kallichore-hit == 'false' }}
      id: verify-kallichore
      continue-on-error: true
      shell: bash
      run: |
        if [ -f "extensions/positron-supervisor/resources/kallichore/kcserver" ]; then
          echo "✅ Kallichore binary verified"
          echo "verified=true" >> $GITHUB_OUTPUT
        else
          echo "⚠️ Kallichore binary missing - skipping cache save"
          echo "verified=false" >> $GITHUB_OUTPUT
        fi

    - name: Save Kallichore binary cache
      if: ${{ inputs.cache-kallichore-hit == 'false' && steps.verify-kallichore.outputs.verified == 'true' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          extensions/positron-supervisor/resources/kallichore
        # IMPORTANT: If bumping kallichore-v3 -> kallichore-v4, also update restore-build-caches/action.yml
        key: kallichore-v3-${{ runner.os }}-${{ inputs.distro }}-${{ hashFiles('extensions/positron-supervisor/package.json') }}

    - name: Log cache save results
      if: always()
      shell: bash
      run: |
        echo "Cache save results:"

        # npm-core
        if [[ "${{ inputs.cache-npm-core-hit }}" == "false" ]]; then
          echo "  npm-core:       saved"
        elif [[ "${{ inputs.cache-npm-core-hit }}" == "true" ]]; then
          echo "  npm-core:       skipped (cache hit)"
        else
          echo "  npm-core:       skipped (not restored)"
        fi

        # npm-extensions
        if [[ "${{ inputs.cache-npm-extensions-hit }}" == "false" ]]; then
          echo "  npm-extensions: saved"
        elif [[ "${{ inputs.cache-npm-extensions-hit }}" == "true" ]]; then
          echo "  npm-extensions: skipped (cache hit)"
        else
          echo "  npm-extensions: skipped (not restored)"
        fi

        # playwright
        if [[ "${{ inputs.cache-playwright-hit }}" == "false" ]]; then
          echo "  playwright:     saved"
        elif [[ "${{ inputs.cache-playwright-hit }}" == "true" ]]; then
          echo "  playwright:     skipped (cache hit)"
        else
          echo "  playwright:     skipped (not restored)"
        fi

        # electron
        if [[ "${{ inputs.cache-electron-hit }}" == "false" ]]; then
          echo "  electron:       saved"
        elif [[ "${{ inputs.cache-electron-hit }}" == "true" ]]; then
          echo "  electron:       skipped (cache hit)"
        else
          echo "  electron:       skipped (not restored)"
        fi

        # builtins
        if [[ "${{ inputs.cache-builtins-hit }}" == "false" ]]; then
          echo "  builtins:       saved"
        elif [[ "${{ inputs.cache-builtins-hit }}" == "true" ]]; then
          echo "  builtins:       skipped (cache hit)"
        else
          echo "  builtins:       skipped (not restored)"
        fi

        # ark
        if [[ "${{ inputs.cache-ark-hit }}" == "false" ]]; then
          if [[ "${{ steps.verify-ark.outputs.verified }}" == "true" ]]; then
            echo "  ark:            saved"
          else
            echo "  ark:            skipped (verification failed)"
          fi
        elif [[ "${{ inputs.cache-ark-hit }}" == "true" ]]; then
          echo "  ark:            skipped (cache hit)"
        else
          echo "  ark:            skipped (not restored)"
        fi

        # kallichore
        if [[ "${{ inputs.cache-kallichore-hit }}" == "false" ]]; then
          if [[ "${{ steps.verify-kallichore.outputs.verified }}" == "true" ]]; then
            echo "  kallichore:     saved"
          else
            echo "  kallichore:     skipped (verification failed)"
          fi
        elif [[ "${{ inputs.cache-kallichore-hit }}" == "true" ]]; then
          echo "  kallichore:     skipped (cache hit)"
        else
          echo "  kallichore:     skipped (not restored)"
        fi
