name: "Save Build Caches"
description: "Saves caches for npm dependencies, built-in extensions, and binaries. Works on both Linux and Windows. Only saves caches that were restored but missed (cache-*-hit == 'false')."

# Platform-Agnostic Design:
# This action automatically detects the platform (Linux/Windows) and uses appropriate
# cache paths. Cache configuration is centralized in .github/scripts/:
# - verify-binary.sh: Platform-aware binary verification
# - log-cache-status.sh: Unified logging for cache operations
#
# When modifying cache paths or keys, update:
# 1. restore-build-caches-v2/action.yml (to maintain restore/save parity)
# 2. This file (save-build-caches-v2/action.yml)

inputs:
  distro:
    description: "Distribution identifier for cache key (default: ubuntu for Linux). Use 'rhel' for RHEL/Rocky Linux. Windows auto-detects to 'windows'."
    required: false
    default: 'ubuntu'
  cache-npm-core-hit:
    description: "Whether npm core cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-npm-extensions-hit:
    description: "Whether npm extensions cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-builtins-hit:
    description: "Whether builtins cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-ark-hit:
    description: "Whether Ark binary cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-kallichore-hit:
    description: "Whether Kallichore binary cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  extensions-hash:
    description: "Extensions hash from restore step (required only if saving npm extensions cache)"
    required: false
    default: ''
  package-locks-hash:
    description: "Package-locks hash from restore step (required only if saving npm core cache)"
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Determine effective distro
      id: distro
      shell: bash
      run: |
        # Auto-detect distro for Windows, otherwise use input
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          EFFECTIVE_DISTRO="windows"
        else
          EFFECTIVE_DISTRO="${{ inputs.distro }}"
        fi
        echo "distro=$EFFECTIVE_DISTRO" >> "$GITHUB_OUTPUT"
        echo "Using distro: $EFFECTIVE_DISTRO"

    - name: Save npm core dependencies cache
      if: ${{ inputs.cache-npm-core-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          .npm-cache
          node_modules
          build/node_modules
          remote/node_modules
          remote/web/node_modules
          remote/reh-web/node_modules
          test/integration/browser/node_modules
          test/monaco/node_modules
          test/mcp/node_modules
        key: npm-core-v4-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ inputs.package-locks-hash }}

    - name: Save npm extensions cache
      if: ${{ inputs.cache-npm-extensions-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          extensions/**/node_modules
          .vscode/**/node_modules
          extensions/positron-assistant/resources
          extensions/positron-python/python-env-tools
          extensions/positron-python/python_files
        key: npm-extensions-v6-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ inputs.extensions-hash }}

    - name: Save built-in extensions cache
      if: ${{ inputs.cache-builtins-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          .build/builtInExtensions
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}

    - name: Verify Ark binary before saving
      if: ${{ inputs.cache-ark-hit == 'false' }}
      id: verify-ark
      continue-on-error: true
      shell: bash
      run: .github/scripts/verify-binary.sh ark

    - name: Save Ark binary cache
      if: ${{ inputs.cache-ark-hit == 'false' && steps.verify-ark.outputs.verified == 'true' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          extensions/positron-r/resources/ark
        key: ark-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ hashFiles('extensions/positron-r/package.json') }}

    - name: Verify Kallichore binary before saving
      if: ${{ inputs.cache-kallichore-hit == 'false' }}
      id: verify-kallichore
      continue-on-error: true
      shell: bash
      run: .github/scripts/verify-binary.sh kallichore

    - name: Save Kallichore binary cache
      if: ${{ inputs.cache-kallichore-hit == 'false' && steps.verify-kallichore.outputs.verified == 'true' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          extensions/positron-supervisor/resources/kallichore
        key: kallichore-v3-${{ runner.os }}-${{ steps.distro.outputs.distro }}-${{ hashFiles('extensions/positron-supervisor/package.json') }}

    - name: Log cache save results
      if: always()
      shell: bash
      env:
        CACHE_NPM_CORE_HIT: ${{ inputs.cache-npm-core-hit }}
        CACHE_NPM_EXTENSIONS_HIT: ${{ inputs.cache-npm-extensions-hit }}
        CACHE_BUILTINS_HIT: ${{ inputs.cache-builtins-hit }}
        CACHE_ARK_HIT: ${{ inputs.cache-ark-hit }}
        CACHE_KALLICHORE_HIT: ${{ inputs.cache-kallichore-hit }}
        VERIFY_ARK: ${{ steps.verify-ark.outputs.verified }}
        VERIFY_KALLICHORE: ${{ steps.verify-kallichore.outputs.verified }}
      run: .github/scripts/log-cache-status.sh save
