name: "Save Build Caches"
description: "Saves caches for npm dependencies, Playwright browsers, Electron binaries, and built-in extensions. Only saves caches that were restored but missed (cache-*-hit == 'false')."

inputs:
  cache-npm-hit:
    description: "Whether npm cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-playwright-hit:
    description: "Whether Playwright cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-electron-hit:
    description: "Whether Electron cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  cache-builtins-hit:
    description: "Whether builtins cache was hit during restore (from restore-build-caches output). If 'false', will save. If 'true' or empty, will skip."
    required: false
    default: ''
  extensions-hash:
    description: "Extensions hash from restore step (required only if saving npm cache)"
    required: false
    default: ''
  package-locks-hash:
    description: "Package-locks hash from restore step (required only if saving npm cache)"
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Save npm dependencies cache
      if: ${{ inputs.cache-npm-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          .npm-cache
          node_modules
          build/node_modules
          extensions
          .vscode
          remote/node_modules
          test/e2e/node_modules
        # Package-locks hash comes from restore step (DRY - single source of truth)
        # IMPORTANT: If bumping npm-v3 -> npm-v4, also update restore-build-caches/action.yml
        key: npm-v3-${{ runner.os }}-${{ inputs.package-locks-hash }}-${{ inputs.extensions-hash }}

    - name: Save Playwright browsers cache
      if: ${{ inputs.cache-playwright-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cache/ms-playwright
          /root/.cache/ms-playwright
          /github/home/.cache/ms-playwright
        # IMPORTANT: If bumping playwright-v3 -> playwright-v4, also update restore-build-caches/action.yml
        key: playwright-v3-${{ runner.os }}-${{ hashFiles('package-lock.json', 'test/e2e/package-lock.json') }}

    - name: Save Electron binary cache
      if: ${{ inputs.cache-electron-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
          /root/.cache/electron
          /root/.cache/electron-builder
          /github/home/.cache/electron
          /github/home/.cache/electron-builder
        # IMPORTANT: If bumping electron -> electron-v2, also update restore-build-caches/action.yml
        key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}

    - name: Save built-in extensions cache
      if: ${{ inputs.cache-builtins-hit == 'false' }}
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
          .build/builtInExtensions
        # IMPORTANT: If bumping builtins -> builtins-v2, also update restore-build-caches/action.yml
        key: builtins-${{ runner.os }}-${{ hashFiles('product.json') }}

    - name: Log cache save results
      if: always()
      shell: bash
      run: |
        echo "Cache save results:"

        # npm
        if [[ "${{ inputs.cache-npm-hit }}" == "false" ]]; then
          echo "  npm:         saved"
        elif [[ "${{ inputs.cache-npm-hit }}" == "true" ]]; then
          echo "  npm:         skipped (cache hit)"
        else
          echo "  npm:         skipped (not restored)"
        fi

        # playwright
        if [[ "${{ inputs.cache-playwright-hit }}" == "false" ]]; then
          echo "  playwright:  saved"
        elif [[ "${{ inputs.cache-playwright-hit }}" == "true" ]]; then
          echo "  playwright:  skipped (cache hit)"
        else
          echo "  playwright:  skipped (not restored)"
        fi

        # electron
        if [[ "${{ inputs.cache-electron-hit }}" == "false" ]]; then
          echo "  electron:    saved"
        elif [[ "${{ inputs.cache-electron-hit }}" == "true" ]]; then
          echo "  electron:    skipped (cache hit)"
        else
          echo "  electron:    skipped (not restored)"
        fi

        # builtins
        if [[ "${{ inputs.cache-builtins-hit }}" == "false" ]]; then
          echo "  builtins:    saved"
        elif [[ "${{ inputs.cache-builtins-hit }}" == "true" ]]; then
          echo "  builtins:    skipped (cache hit)"
        else
          echo "  builtins:    skipped (not restored)"
        fi
