name: "Setup E2E Test Environment"
description: "Sets up the Quarto CLI, TinyTeX, Graphviz, and configures AWS S3 access."
runs:
  using: "composite"
  steps:

    - name: Setup AWS S3 Access
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.QA_AWS_RO_ROLE }}
        aws-region: ${{ secrets.QA_AWS_REGION }}

    - name: Install Quarto CLI
      shell: bash
      run: |
        TEMP_DEB="$(mktemp)" &&
        wget -O "$TEMP_DEB" 'https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.57/quarto-1.5.57-linux-amd64.deb' &&
        sudo dpkg -i "$TEMP_DEB"
        rm -f "$TEMP_DEB"

    - name: Install TinyTeX
      shell: bash
      run: quarto install tinytex

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2.0.2
