name: On Reopen
on:
  issues:
    types: [reopened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode-github-triage-actions"
          ref: stable
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: Check for Validity
        uses: ./actions/validity-checker
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
