name: "Positron: CI - Pull Request"

on:
  pull_request:
    branches:
      - main
      - 'prerelease/**'

jobs:
  positron-ci:
    uses: ./.github/workflows/positron-merge-to-branch.yml
    secrets: inherit
    with:
      smoketest_target: smoketest-pr
