name: "Positron: CI - Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/positron-merge-to-main.yml
    secrets: inherit
    with:
      e2e_grep: "@pr"
