name: "Test: Pull Request"

on:
  pull_request:
    branches:
      - main
      - 'prerelease/**'

jobs:
  tests:
    uses: ./.github/workflows/positron-merge-to-branch.yml
    secrets: inherit
    with:
      e2e_grep: "@critical"
