name: "Test: PR"

on:
  pull_request:
    branches:
      - main
      - 'prerelease/**'

jobs:
  e2e-electron:
    name: e2e
    uses: ./.github/workflows/test-e2e-linux.yml
    with:
      grep: "@pr"
      project: "e2e-electron"
      display_name: "electron (linux)"
      currents_tags: "electron/linux"
    secrets: inherit

  unit-tests:
    name: test
    uses: ./.github/workflows/test-unit.yml
    secrets: inherit

  integration-tests:
    name: test
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit



