name: "Test: PR"

on:
  pull_request:
    branches:
      - main
      - 'prerelease/**'

jobs:
  pr-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.extract-tags.outputs.tags }}
    steps:
      - name: Extract PR Body
        # if @all, set to ""
        # else append @critical
        run: |
          echo "Extracting PR body..."
          PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH" | tr '\n' ' ' | sed 's/"/\\"/g')
          echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      - name: Parse Tags from PR Description
        id: extract-tags
        run: |
          echo "Extracting tags from PR description..."
          # Parse tags starting with '&' and convert to '@'
          TAGS=$(echo "$PR_BODY" | grep -o "&[a-zA-Z0-9_-]*" | sed 's/&/@/g' | tr '\n' ',' | sed 's/,$//')
          echo "Extracted Tags: $TAGS"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
        env:
          PR_BODY: ${{ env.PR_BODY }}

  e2e-electron:
    name: e2e
    uses: ./.github/workflows/test-e2e-linux.yml
    needs: pr-tags
    with:
      grep: "@critical,${{ needs.pr-tags.outputs.tags }}"
      display_name: "electron (linux)"
      currents_tags: "electron/linux,$TAGS"
    secrets: inherit

  unit-tests:
    name: test
    uses: ./.github/workflows/test-unit.yml
    secrets: inherit

  integration-tests:
    name: test
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit



