name: "Test: PR / Merge"

on:
  pull_request:
    branches:
      - main
      - 'prerelease/**'
  push:
    branches:
      - main
      - 'prerelease/**'

permissions:
  id-token: write
  contents: read

jobs:
  e2e-electron:
    name: e2e
    uses: ./.github/workflows/test-e2e-linux.yml
    with:
      grep: ${{ github.event_name == 'pull_request' && '@pr' || github.event_name == 'push' && '' }}
      project: "e2e-electron"
      display_name: "electron (linux)"
      currents_tags: ${{ github.event_name == 'pull_request' && '@pr,@electron/linux' || github.event_name == 'push' && '@push,@electron/linux' }}
    secrets: inherit

  unit-tests:
    name: test
    uses: ./.github/workflows/test-unit.yml
    secrets: inherit

  integration-tests:
    name: test
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit

  slack-notify:
    # if: ${{ failure() && inputs.e2e_grep == '' }}
    needs: [unit-tests, integration-tests, e2e-electron]
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: midleman/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.POSITRON_GITHUB_PAT }}
          slack_webhook_url: ${{ secrets.SLACK_MARIE_WEBHOOK_URL }}
          notify_on: "failure"


